### ISSUE TITLE
Background annotated method with return type not just void

### ISSUE THREAD

**Issue by parmalazs** [androidannotations/androidannotations#1172]
Do you have any plan to do this?

**Comment by josejuanmontiel** [comment]
Hi, i think @parmalazs  refer to mix https://github.com/excilys/androidannotations/wiki/Adapters-and-lists with https://github.com/excilys/androidannotations/wiki/Rest-API where InMemoryPersonFinder its a RestPersonFinder

@EBean
public class RestPersonFinder implements PersonFinder {

    @RestService
    PersonRestClient myRestClient; //Inject it
    @Override
    public List<Person> getPersons() {
        List<Person> persons = myRestClient.getPersons();

        if (persons!=null) {
            return persons;
        } else {
            return Collections.emptyList();
        }
    }

and in PersonListAdapter we need @Background for the restriction of network on uithred...

    @AfterInject
    @Background
    void initAdapter() {
        persons = personFinder.getPersons();
    }

and if we background... it continues... and 

    @Override
    public int getCount() {
        return persons.size();
    }

its called before rest service response...
