### ISSUE TITLE
@Trace annotation customization

### ISSUE THREAD

**Issue by athkalia** [androidannotations/androidannotations#1200]
Hello

I noticed that in some cases the @Trace annotation is polluting my log. You see, I don't want to know when some methods exit, especially when they don't have a return value. Also, in most of the cases (probably always) I don't care about the duration of methods. 

I am wondering if there is a way to create a few options for the @Trace annotations:
- Option to disable method duration.
- Option to only display the "exiting method" log statement when there is a return value for that method
- Option to completely disable the "exiting method" log statement.

While you are at it, does the @Trace annotation support slf4j ?

**Comment by gauravsak** [comment]
@WonderCsabo If this isn't being implemented, could you please close the issue? Thanks!
