### ISSUE TITLE
Support for RecyclerView

### ISSUE THREAD

**Issue by josescgar** [androidannotations/androidannotations#1210]
Starting with Android 5.0 (and backwards with appcompat v21), Google intends to shift the focus from ListView to RecyclerView, a much more efficient implementation of the first one. Right now it is a bit of a pain to properly set up a RecyclerView and unfortunately there isn't support for that. For example, @ItemClick and such are no longer valid since the RecyclerView itself doesn't handle the list clicks.

**Comment by dodgex** [comment]
in my project i enhanced the suggested approach a little bit:

i added `Binder<T>` and require it to be implemented by the `View`.
```java
public class ViewWrapper<T, V extends View & ViewWrapper.Binder<T>> extends RecyclerView.ViewHolder {

	private V view;

	public ViewWrapper(V itemView) {
		super(itemView);
		view = itemView;
	}

	public V getView() {
		return view;
	}

	public interface Binder<T> {
		void bind(T data);
	}
}
```
and let the `RecyclerViewAdapterBase` take care of the `onBindViewHolder` calls.
```java
public abstract class RecyclerViewAdapterBase<T, V extends View & ViewWrapper.Binder<T>> extends RecyclerView.Adapter<ViewWrapper<T, V>> {

	protected List<T> items = new ArrayList<T>();

	@Override
	public final ViewWrapper<T, V> onCreateViewHolder(ViewGroup parent, int viewType) {
		return new ViewWrapper<T, V>(onCreateItemView(parent, viewType));
	}

	protected abstract V onCreateItemView(ViewGroup parent, int viewType);

	@Override
	public final void onBindViewHolder(ViewWrapper<T, V> viewHolder, int position) {
		V view = viewHolder.getView();
		T data = items.get(position);

		view.bind(data);
	}

	@Override
	public int getItemCount() {
		return items.size();
	}

	public void add(T item) {
		items.add(item);
		notifyDataSetChanged();
	}
	
	public void addAll(Collection<T> items) {
		items.addAll(items);
		notifyDataSetChanged();
	}

	public void clear() {
		items.clear();
	}
}
```

the result is less code in the actual adapter:
```java
@EBean
public class TrackListAdapter extends RecyclerViewAdapterBase<TracklistEntry, TrackView> {

	@RootContext
	Context ctx;

	@Override
	protected TrackView onCreateItemView(ViewGroup parent, int viewType) {
		return TrackView_.build(ctx);
	}
}
```

**Comment by WonderCsabo** [comment]
Nice, this is what i meant in my last sentence in the wiki.

**Comment by dodgex** [comment]
havnt read that :D but yeah. there you go.

**Comment by easyspeak** [comment]
I tried using dodgex's solution which mostly works, however I cannot get it to inflate my item views correctly when I have the layout_width set to match parent. To get the right layout I am currently using the following code in my Adapter:

```
    @Override
    public ViewHolder onCreateViewHolder(ViewGroup parent, int viewType) {
        LayoutInflater layoutInflater = LayoutInflater.from(parent.getContext());
        View layout = layoutInflater.inflate(R.layout.comment_list_item, parent, false);

        return new ViewHolder(layout);
    }
```
 
Does anyone know how to integrate this same functionality into dodgex's solution? I have tried multiple times without success. I am fairly new to Android so I am hoping I am missing something simple.

**Comment by dodgex** [comment]
@easyspeak i think this is currently not possible due to how AA inflates the layout for a custom ViewGroup. also i'm not sure if it is possible to change the way AA inflates the layout to support your case.

**Comment by WonderCsabo** [comment]
@easyspeak i did not use `RecyclerView` yet, only `ListView`, but it works for me with `match_parent`:
```xml
<?xml version="1.0" encoding="utf-8"?>
<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:layout_height="?android:attr/listPreferredItemHeight" >
>
...

</RelativeLayout>
```
```java
@EViewGroup(R.layout.list_item_package)
public class CustomView extends LinearLayout {
...
}
```

And then you can build it to return in the adapter:
```java
CustomView_.build(context);
```

I know this is suboptimal, because we are creating two view layers instead of one...

**Comment by easyspeak** [comment]
Thanks for the quick responses. @dodgex I agree with your comment. Unfortunately the inflate() method in the generated AA code is not configurable to allow for this type of layout. I was hoping maybe there was something that i was missing. Thanks for the confirmation.

@WonderCsabo I may try your suggestion in the future. For now I am going to create my RecyclerViews without AA when I need to match_parent.

**Comment by Rainer-Lang** [comment]
Any news?

**Comment by WonderCsabo** [comment]
@Rainer-Lang this issue is closed. You can easily fuse](https://github.com/excilys/androidannotations/wiki/Adapters-and-lists#recyclerview-and-viewholder) `RecyclerView` with AA.

**Comment by kaiyan910** [comment]
@easyspeak are you using LinearLayout for the item view? I did face the same match_parent problem when I use LinearLayout, but it solve if you change to RelativeLayout

**Comment by mrmans0n** [comment]
@kaiyan910 great suggestion - I had the same problem and changing LinearLayout to RelativeLayout did the work, you saved me hours there! :)

**Comment by Scott110** [comment]
@kaiyan910  Thanks for a lot  I solve my question

**Comment by LuizGadao** [comment]
What is the best pattern for add click in ViewHolder?

**Comment by WonderCsabo** [comment]
As you can see in the [wiki page](https://github.com/excilys/androidannotations/wiki/Adapters-and-lists#recyclerview-and-viewholder), we suggest to use an `EViewGroup`, and wrap that in to the `ViewHolder`. Then you can use all the annotation within the `EViewGroup`.

**Comment by LuizGadao** [comment]
Yes, I'm use it. I say the activity that have a adapter. How best practise to notify this activity when viewholder is clicked?

**Comment by WonderCsabo** [comment]
You can use an event bus for that purpose, as i already suggested it in [this](https://gitter.im/excilys/androidannotations?at=559ac5810edc4b6a7986e8f3) discussion. Or you can just create a listener/subscriber yourself.

> Please next time for usage questions use other channels, like [stackoverflow](http://stackoverflow.com/questions/tagged/android-annotations) or the [mailing list](http://groups.google.com/group/androidannotations). GitHub issues is not a place for these kind of questions, we discuss development (bugs, new features, etc) here. We already show you [this information](https://github.com/excilys/androidannotations/wiki/HowToWriteAnIssue) (guidelines on contributing) on the top of the [new issue page](https://github.com/excilys/androidannotations/issues/new).

**Comment by WonderCsabo** [comment]
@LouisCo if you have suggestion to enhance our solution in the wiki, please share it here.

**Comment by komissarovdenis** [comment]
@kaiyan910 thank you a lot! RelativeLayout is only one decision to keep items match_parent with AA

**Comment by WonderCsabo** [comment]
This is not true. You can use any layout, and set the layout parameters
manually to match_parent in your custom viewgroup's constructor.

**Comment by komissarovdenis** [comment]
@WonderCsabo what's wrong in this sample? In result I've still got a wrap_content views by width 

```
@EViewGroup(R.layout.view_custon)
public class CustomItemView extends FrameLayout {
    private final FrameLayout.LayoutParams layoutParams;
    
    @ViewById(R.id.parent_layout)
    protected ViewGroup parentLayout;
    
    public CustomItemView(Context context) {
        super(context);
        layoutParams = new FrameLayout.LayoutParams(LayoutParams.MATCH_PARENT, LayoutParams.WRAP_CONTENT);
    }

    @AfterViews
    protected void init() {
        parentLayout.setLayoutParams(layoutParams);
    }
}
```

**Comment by WonderCsabo** [comment]
Just call setLayoutParams() on this. Also make sure the layout  has
match_parent.

Csabi

**Comment by LouisCAD** [comment]
You can also remove the layout `@EViewGroup` layout resId parameter, add the generated `@EViewGroup` in the layout xml file, and call `LayoutInflater.from(context).inflate(R.layout.yourLayout, parent, false)` to inflate the recycler view list item

**Comment by komissarovdenis** [comment]
Thank you guys!

**Comment by LouisCAD** [comment]
@komissarovdenis You're welcome. Let us know if it works for you

**Comment by komissarovdenis** [comment]
I'd like to use setLayoutParams() (it's work fine) 
this way because I've use adapter by [wiki suggestions](https://github.com/excilys/androidannotations/wiki/Adapters-and-lists#recyclerview-and-viewholder) where V onCreateItemView(ViewGroup parent, int viewType); is need to be casted to my custom view.

**Comment by LouisCAD** [comment]
@komissarovdenis I used this pattern, but I now built another, very similar, but which allows using xml attributes to the parent (which removes lots of unnecessary boilerplate without making things worse). I replaced `V onCreateItemView(ViewGroup parent, int viewType);` by a `@LayoutRes int getLayout(int viewType)`. You can see [here](https://github.com/LouisCAD/PopularMovies/blob/master/app/src/main/java/xyz/louiscad/popularmovies/util/recyclerview/RecyclerViewAdapterBase.java) My implementation of `RecyclerViewBaseAdapter`

**Comment by komissarovdenis** [comment]
@LouisCAD thanks again for good explanation :smile:
