### ISSUE TITLE
Got error use @EApplication when enable android multidex support

### ISSUE THREAD

**Issue by paxleung** [androidannotations/androidannotations#1247]
I enable android multidex in my project. follow the google android development guide
http://developer.android.com/tools/building/multidex.html

But I got error when use @EApplication. sample code as follow 
@EApplication
public class MyApplication extends Application
.....

I got the following error on android studio gradle build: 
 error: No application class registered in the AndroidManifest.xml

My AndroidManifest.xml as follow:
....
<application
        android:name="android.support.multidex.MultiDexApplication"
.....

**Comment by himamis** [comment]
Hello. I have the same problem. My custom application extends MultiDexApplication, and in the AndroidManifest.xml I have .MyCustomApplication_. I still get the "The AndroidManifest.xml file contains the original component, and not the AndroidAnnotations generated component. Please register..." message.

**Comment by WonderCsabo** [comment]
Recompile the project, the error marker should go away.

**Comment by himamis** [comment]
I tried doing that. But it seems it's an eclipse problem, maven could compile without a problem.

**Comment by WonderCsabo** [comment]
Try to refresh the files, clean the project etc in Eclipse. It seems it still sees the old state.

**Comment by himamis** [comment]
Thanks, solved it.

**Comment by JackDinealKIM** [comment]
Thanks, It works.
