### ISSUE TITLE
Remove view annotation support from EBean

### ISSUE THREAD

**Issue by WonderCsabo** [androidannotations/androidannotations#1477]

**Comment by LouisCo** [comment]
Only if You add it for RecyclerView ViewHolders.

How I use `@ViewById` for my RecyclerViews now
```java
@EBean
public static class MyViewHolder extends RecyclerView.ViewHolder implements HasViews {

    @ViewById
    TextView titleTV, descTV;

    @ViewById
    ImageView icon;

    private static tmpParent;

    public static MyViewHolder newInstance(ViewGroup parent) {
        tmpParent = parent;
        MyViewHolder newHolder = MyViewHolder_.getInstance_(parent.getContext());
        tmpParent = null;
        return newHolder;
    }

    protected MyViewHolder(Context context) {
        super(LayoutInflater.from(context).inflate(R.layout.my_list_item, tmpParent, false));
        ((OnViewChangedListener) this).onViewChanged(this);
    }

    @Override
    public View findViewById(int id) {
        return itemView.findViewById(id);
    }
```

It's a little ugly, but it's less boilerplate than standard implementation, so please, don't remove EBan view annotations if you don't provide a @EViewHolder annotation, with the ability to tell AA when to findViewsById on itemView

**Comment by dodgex** [comment]
@LouisCo you should either refactor your code to [this](https://github.com/excilys/androidannotations/wiki/Adapters-and-lists#recyclerview-and-viewholder) approach or you can use my [slightly improved version](https://github.com/excilys/androidannotations/issues/1210#issuecomment-68483114) where in my case the `TrackView` is a `@EViewGroup` that can use `@ViewById` for its childs.

**Comment by LouisCo** [comment]
@dodgex your version isn't very straighforward for thos wanting to add `@ViewById` and implies boilerplate for each project anyway... Why don't you provide a modified RecyclerViewAdapterBase with abstract `getItem(int position)` in place of the ArrayList, and your ViewVrapper in AA? Also, I think a usage example of using `@EViewGroup` in the doc would help developers to use the good approach

**Comment by gauravsak** [comment]
@WonderCsabo If this issue is resolved, could you please mark it closed? Thanks!
