### ISSUE TITLE
Android DataBinding support

### ISSUE THREAD

**Issue by egslava** [androidannotations/androidannotations#1627]
Please, add/document support of Android DataBinding.

There're only two changes:
1. It needs to use `DataBindingUtil.setContentView` instead of `Activity.setContentView`.
2. We need access to result of `setContentView`.

**Comment by WonderCsabo** [comment]
Unfortunately data binding has problems when annotation processors are used (see [last comments](https://bitbucket.org/hvisser/android-apt/issues/38/android-apt-breaks-brand-new-data-binding)). That is why i think it is not worth adding this feature to AA.

Moreover, this fix is not trivial from AA side. We would have to add a new parameter to `@EActivity` and `@EFragment` to instruct AA to use data binding. Also passing the result binding object to so a method for example annotated with `@AfterViews` or such. These changes only remove one line from the user's code... Also data binding is still kind of experimental.

However, please not new annotations now can be easily added by creating a simple AA plugin.

**Comment by guitcastro** [comment]
@WonderCsabo If the problem related with the annotation process is fixed, you will consider add support for data binding, if it comes to be stable ?

I would love to use AA and data binding on my projects

**Comment by WonderCsabo** [comment]
Well, it is not trivial to add it, but of course, it would be nice.

**Comment by qazt482** [comment]
Any update on this? I would really like to use databinding.

**Comment by guitcastro** [comment]
You can use Jack and Jill new annotation processor. It is compatible with Android DataBinding.
I've success used AA with Jack and Jill following this [example](https://github.com/nickwph/annotation-processor-with-java8-jack-and-jill-android/blob/master/app/build.gradle#L56-L73).

**Comment by SimenB** [comment]
Jack doesn't work with data binding. 

https://code.google.com/p/android/issues/detail?id=210615

**Comment by guitcastro** [comment]
Oh, my bad. @SimenB is right.

**Comment by rkmax** [comment]
some update, now that the annotation processor is included on android gradle

**Comment by brainscript** [comment]
**+1** I'd like to see this feature to.

**Comment by gauravsak** [comment]
@WonderCsabo Please change the status of this issue according to the needed efforts. Thanks!

**Comment by WonderCsabo** [comment]
I only experimented in with Android data binding. If you want this feature, please help us by designing the new annotations and parameters, and the generated code. Thanks!

**Comment by smaugho** [comment]
The framework can detect if Data Binding is enabled, if so, I think that it should not only to use `Activity.setContentView.`, but @Bean and ViewById can use this mechanism as well.

It could use its methods to Inject the Views. The @Bean mechanism should offer support to bind the field to the layout, simply setting a parameter in the annotation:

```java
@Bean(bind=true)
User user;
```

From there, all the annotations from data binding itself can be used within the class User. 

There can be an annotation to access to the Binding object:

```java
@Binding
ActivityMainBinding binding;
```

This can use the default  layout specified to @EActivity and @EFragment, probably  it would be good idea to pass the layout as a parameter too:

```java
@Binding(R.layout.main_activity)
ActivityMainBinding binding;
```

@WonderCsabo, @dodgex I'm very interested in implementing this features, please could you check if the 
the suggested changes would be a good start to support this feature?

**Comment by dodgex** [comment]
While in general this sounds good I have trouble to imagine how it should work. The problem is that i never used the Data Binding feature and not even read much about it. All I know is that it exists. :/

Maybe you could start with a prototype of how the generated code could look like and maybe even in a small sample project that we can have a quick look on data binding at all. 

Thanks! :)

**Comment by smaugho** [comment]
Agree, I'll be working on it (slow pace, but definitely I will)... I want first also to read all the documentation again about Data Binding in Google, the lib have a lot of features that could be integrated as well. 

There's some articles of 1min-2min reading to have a basic idea of the feature.. for instance [Android Data Binding](https://android.jlelse.eu/android-data-binding-8d0eb34b9bad)

Basically the features mentioned in this article would be the first one that I would like to implement.

**Comment by dodgex** [comment]
Thank you for that link. I already knew the concept of data binding (from outside of android development) but this short blog presented the how to use for android pretty good i think. Looks interesting. I think I would have used this feature in my app if it would be worth it. I do not have that much data to display and id would have been more work to switch to data binding that it would have make my code nicer. :D

We'd be happy to see your contribution on this feature. :+1:

**Comment by WonderCsabo** [comment]
Hey guys,

I managed to allocate some time to finally implement this.
The annotated code would look like this:

```java
@DataBound
@EActivity(R.layout.databound_activity)
public class DataBoundActivity extends Activity {

    @AfterDataBinding
    void afterDataBinding(DataBoundActivityBinding binding) {
        binding.setVariable(variable);
    }
}
```

The same would work for `@EFragment` and `EViewGroup` as well.
Is this API support your needs?

**Comment by smaugho** [comment]
It sounds great! Thanks, this would be already highly useful for using Data Binding library. Were checks done regarding to availability of the DataBindingLibrary?, in the validations of @DataBound for instance. 

Thanks!.

**Comment by WonderCsabo** [comment]
I did not start to implement the features, i will do it tomorrow.
Yes, it is a good idea to check if the data binding library is on the classpath. 👍

**Comment by smaugho** [comment]
@WonderCsabo I was just checking something, with DataBinding, typically the layout is set in the activity with:

DataBoundActivityBinding binding = DataBindingUtil.setContentView(this, R.layout.databound_activity);

for instance, this will conflict with @EActivity(R.layout.databound_activity) which will try to set the layout with setContentView. So I guess if this is like this, it would make more sense to prepare @EActivity itself to support databinding (through a boolean for instance, in the annotation). Then the @EActivity itself will set it content properly, and it could initialize the DataBoundActivityBinding object correctly (in this sense, the @DataBound annotation would be not necessary).

I know the idea is not messing around with @EActivity, but since DataBinding changes the way to set the activity content view, I guess some change should be done there anyway.

**Comment by WonderCsabo** [comment]
I would rather not add a new parameter to `@EActivity`. Yes, i am aware that setting the content view is different when using data binding. In my proposal, `@EActivity` would check the presence of   the `@DataBound` annotation, and change the code.

**Comment by dodgex** [comment]
Thank you Csaba! :)
