### ISSUE TITLE
@SharedPref dynamic naming

### ISSUE THREAD

**Issue by couchcrew-thomas** [androidannotations/androidannotations#1675]
Hello everyone.

It would be great if the @SharedPref annotation could be used with dynamic names. Either using a string value inside the annotation or as a setter similar to setRootUrl() of the Rest interface.

Would this be possible?

**Comment by dodgex** [comment]
I'm not sure what you want to achiev? Could you provide a small sample of what you would like to do?

**Comment by couchcrew-thomas** [comment]
Currently the name of the preferences is fetched from the class:

    @SuppressWarnings("unused")
    @SharedPref(SharedPref.Scope.UNIQUE)
    public interface SessionStore {

        String sessionId();
    }

This creates a session file "SessionStore". This can cause the following errors:
* The Preferences are lost when a refactoring renames the class
* The Preferences could conflict with a "SessionStore" preferences used in another module

To cirumvent the following I'd like to specify the name of the session store manually:

    @SuppressWarnings("unused")
    @SharedPref(name="MyNamedPreferencesFile")
    public interface SessionStore {

        String sessionId();
    }

This way the refactoring error is eliminated. The naming conflict could persist but can be easily cirumvented.

My personal use cases are the following:
* Eliminating the possible refactoring bug. Because refactoring is done quiet regularly on a large scale app.
* Using the AA Preference system on legacy preference files that were created without using AA.


Additionally, supporting non-constant naming of the preferences file would be usefull. Something like:

    SessionStore_.from("UserPreferences"+userId)...

Could serve the same interface for different preference files.

**Comment by WonderCsabo** [comment]
The generated files are not meant to be used in this case, only with injecting using the `@Pref` annotation.

But i think we can add a `name` parameter, possibly with a corresponding scope to avoid errors? @dodgex @yDelouis WDYT?

**Comment by dodgex** [comment]
I'm okay with adding such a parameter.

**Comment by dodgex** [comment]
@WonderCsabo i checked `ShardPrefHandler` the inteface name is only used fore scopes  `ACTIVITY` and `UNIQUE`. I'd say we add the `name` parameter overriding the interface name for those scopes and in validation add a warning (i think error is a bit to hard?) that the `name` param is only used with those scopes if a not supporte one is used.

wdyt?
