### ISSUE TITLE
AndroidWear - WatchViewStub not working

### ISSUE THREAD

**Issue by matthewcarlreetz** [androidannotations/androidannotations#1678]
In AndroidWear you must use WatchViewStub to support both round and rectangular layouts.  AndroidAnnotations does not currently find these subviews.

This is how I'm currently handling it...

```
@AfterViews
    public void setup() {
        stub.setOnLayoutInflatedListener(new WatchViewStub.OnLayoutInflatedListener() {
            @Override
            public void onLayoutInflated(WatchViewStub stub) {
                listView = (ListView) stub.findViewById(R.id.listView);
            }
        });
    }
```

**Comment by WonderCsabo** [comment]
What class `setup()` is in?

**Comment by dodgex** [comment]
@WonderCsabo i think his problem is, that he wants to inject views from inside a `WatchViewStub` with `@ViewById` but AA does not support injecting views from `WatchViewStub`.

**Comment by WonderCsabo** [comment]
@dodgex yes, of course we do not support that. But we may can add support, although as i am looking i am not sure if it is possible.

**Comment by matthewcarlreetz** [comment]
'setup()' is in an activity. @dodgex yes, you are correct.

**Comment by WonderCsabo** [comment]
I am afraid we cannot support this because it is too complicated for compile time

1. we have to know this is a watch Activity/Fragment etc
2. we have to know the view ID of the stub
3. we have to change the generation code using that knowledge to listen for the stub inflation

**Comment by dodgex** [comment]
for the `@ViewById` it is to complicated. But one could create a plugin for wear (with this and maybe other features?).

But that would need more experience with the Wear SDK. unfortunately I currently have not that much spare time to use for *random* contributions with no direct personal use - and no wear experience.

**Comment by gauravsak** [comment]
@WonderCsabo @dodgex Should this be tagged as "ContributionWelcome" and "Enhancement" then?

**Comment by WonderCsabo** [comment]
This is rather complicated, and also changes the core generation of normal AA code, we will not implement this, sorry.

However, you can add new annotations in a new [AA plugin](https://github.com/androidannotations/androidannotations/wiki/Creating-an-AndroidAnnotations-plugin) which can generate arbitrary code.
