### ISSUE TITLE
Android annotation Content Type Problem

### ISSUE THREAD

**Issue by erishforG** [androidannotations/androidannotations#1743]
In case of Android annotation 3.2,

`
@Rest(rootUrl = Host.url, converters = MappingJackson2HttpMessageConverter.class, interceptors = BasicAuthorizationInterceptor.class, requestFactory = customClientHttpRequestFactory.class)
public interface SignInRest {

```
@Post("/oauth/token")
@RequiresHeader("tmp")
public Token getToken(MultiValueMap form);
```

}
`

I used this function like this. And the usage of this function is like this.

`
MultiValueMap map = new LinkedMultiValueMap();

```
    map.add("grant_type", "password");
    map.add("username", prefsManager.userId().get());
    map.add("password", prefsManager.password().get());

    try {
        Token result = testRest.getToken(map);
        return;
    } catch(HttpClientErrorException e) {
        viewLoadingEnd();

        if(e.getStatusCode().value() == 404) {
            serverDialog();
            return;
        }
    } catch(Exception e) {
        viewLoadingEnd();
        alertDialog();
        return;
    }
```

`

And sending data form and request header form will be this.

> request header // {Accept=[application/json, application/_+json, application/json, application/_+json], tmp=[null], Content-Type=[application/x-www-form-urlencoded], Content-Length=[104]}
> request data // grant_type=password&username=12345&password=QWERTY

But when Android annotation upgrades to 3.3.+, the function does not work well.
In version of 3.3.+ Android annotation request header and request data,

> request header // {Accept=[application/json, application/*+json], tmp=[null], Content-Type=[application/json;charset=UTF-8], Content-Length=[124]}
> request data // {"grant_type":["password"],"username":["12345"],"password":["QWERTY"]}

The request data form is json form not x-www-form-urlencoded! And when I tried to change Content-Type to x-www-form-urlencoded, but the result was same. Is it bug or is there any solution for this?

**Comment by WonderCsabo** [comment]
@erishforG does this error happen in AA 4.0.0?

**Comment by erishforG** [comment]
@WonderCsabo not tested yet. I'm trying to check moving on to 3.3 first and then move to 4.0.0.

**Comment by WonderCsabo** [comment]
@erishforG please check it with the latest version, bugs should be always opened against the latest (actually the development) version, because it is possible things changed since an older version.

**Comment by WonderCsabo** [comment]
@erishforG could you check this with 4.0.0?

**Comment by erishforG** [comment]
@WonderCsabo 
Oops! Sorry, I forgot it.
I'll check it from now on! And I think it will be done until next week.

**Comment by erishforG** [comment]
Still same with Android Annotation 4.0.0

**Comment by WonderCsabo** [comment]
@erishforG we support [form url encoded requests](https://github.com/excilys/androidannotations/wiki/Rest%20API#field).
