### ISSUE TITLE
@Put 406 error - RestAPI - JSON

### ISSUE THREAD

**Issue by Nico11Riv** [androidannotations/androidannotations#1834]
Hello everyone! :)

I'm actually writing an app with the Rest module of AA 4.0 and today I added a @Put request to my RestAPI and after seting up the infos needed and the app builded, the app crashed just at the RestAPI call with the 406 error.

I tried to use the @Accept annotation to indicate that "application/json" who is expected and eaven use the @Header annotation to manualy setup the "Accept" header info expected to json or everything "_/_"...

My other @Get and @Post directives are perfectly working and the "application-type" rerurned by my JSON API is allways "apllication/json".

It seams that the problem is linked to @Put annotation because in the AA list of annotations and at the @Accept informations, it's indicated that the annotation @Accept is only used for @Get and @Post...

Can someone help me? 6 hours of Googling and still nothing...

If wou want more informations, din't hesitate to tell me! :) (i'm on my phone while I'm writing this lines and I don't have access to my Android Studio project.

Thanks in advance for your help.

Nicolas

**Comment by WonderCsabo** [comment]
Does it work if you remove all accept headers? By the way indicating you
are accepting any type is */*.

**Comment by Nico11Riv** [comment]
By removing the @Accept annotation? And by the way I mistyped in my first message the "*/*"... :)
