### ISSUE TITLE
ImageGetter and TagHandler for @HtmlRes and @FromHtml

### ISSUE THREAD

**Issue by optisamit** [androidannotations/androidannotations#1836]
Please add these two optional parameters to html-related annotations.
[Html.fromHtml()](https://developer.android.com/reference/android/text/Html.html#fromHtml%28java.lang.String, int, android.text.Html.ImageGetter, android.text.Html.TagHandler%29)

**Comment by WonderCsabo** [comment]
How we could add those in annotation parameters?

**Comment by optisamit** [comment]
E.g. like this:
`@FromHtml(res=R.string.html_res, imgGetter=ImgGetterBean.class, tagHandler=TagHandlerBean.class)`

**Comment by dodgex** [comment]
`.class` would not help as you have to pass an instance to `fromHtml()`

**Comment by WonderCsabo** [comment]
Of course we can create an instance of the class as we do in the Rest API for interceptors and friends. However i think this complicated cases should not be handled by annotations.

**Comment by optisamit** [comment]
Of course, in the generated enhanced file you would instantiate

**Comment by optisamit** [comment]
I don't think they are that complicated and they don't complicate the usage of annotations, after all. It is up to you, of course, whether to honor the request :)
