### ISSUE TITLE
Receiver not registered on pause

### ISSUE THREAD

**Issue by trramsiq** [androidannotations/androidannotations#1843]
I'm getting a rare error when adding a receiver for Network changes. Here is what I've added to my activity:

@Receiver(actions = ConnectivityManager.CONNECTIVITY_ACTION, registerAt = Receiver.RegisterAt.OnResumeOnPause)
    void networkChanges() {
        SyncController.syncUnsetData();
    }

And here is the Exception I get for some users.

Fatal Exception: java.lang.RuntimeException: Unable to pause activity {com.app/com.app.activities.main.MainActivity_}: java.lang.IllegalArgumentException: Receiver not registered: com.app.activities.main.l@6a9bd89
       at android.app.ActivityThread.performPauseActivity(ActivityThread.java:4379)
       at android.app.ActivityThread.performPauseActivity(ActivityThread.java:4338)
       at android.app.ActivityThread.handlePauseActivity(ActivityThread.java:4313)
       at android.app.ActivityThread.access$1200(ActivityThread.java:197)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1692)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:145)
       at android.app.ActivityThread.main(ActivityThread.java:6872)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1404)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1199)
Caused by java.lang.IllegalArgumentException: Receiver not registered: com.app.activities.main.l@6a9bd89
       at android.app.LoadedApk.forgetReceiverDispatcher(LoadedApk.java:871)
       at android.app.ContextImpl.unregisterReceiver(ContextImpl.java:2103)
       at android.content.ContextWrapper.unregisterReceiver(ContextWrapper.java:529)
       at com.app.activities.main.MainActivity_.onPause(MainActivity_.java:154)
       at android.app.Activity.performPause(Activity.java:6706)
       at android.app.Instrumentation.callActivityOnPause(Instrumentation.java:1324)
       at android.app.ActivityThread.performPauseActivity(ActivityThread.java:4365)
       at android.app.ActivityThread.performPauseActivity(ActivityThread.java:4338)
       at android.app.ActivityThread.handlePauseActivity(ActivityThread.java:4313)
       at android.app.ActivityThread.access$1200(ActivityThread.java:197)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1692)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:145)
       at android.app.ActivityThread.main(ActivityThread.java:6872)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1404)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1199)

**Comment by WonderCsabo** [comment]
Can you post the generated code?

**Comment by trramsiq** [comment]
//
// DO NOT EDIT THIS FILE.
// Generated using AndroidAnnotations 4.1.0.
// 
// You can create a larger work that contains this file and distribute that work under terms of your choice.
//

package com.soudfa.activities.main;

import java.util.ArrayList;
import android.app.Activity;
import android.content.BroadcastReceiver;
import android.content.Context;
import android.content.Intent;
import android.content.IntentFilter;
import android.os.Bundle;
import android.support.v4.app.ActivityCompat;
import android.support.v4.widget.DrawerLayout;
import android.support.v7.widget.Toolbar;
import android.view.View;
import android.view.View.OnClickListener;
import android.view.ViewGroup.LayoutParams;
import android.widget.AdapterView;
import android.widget.AdapterView.OnItemClickListener;
import android.widget.ImageView;
import android.widget.ListView;
import android.widget.RelativeLayout;
import com.soudfa.Models.MainMenu.NavItem;
import com.soudfa.R;
import org.androidannotations.api.builder.ActivityIntentBuilder;
import org.androidannotations.api.builder.PostActivityStarter;
import org.androidannotations.api.view.HasViews;
import org.androidannotations.api.view.OnViewChangedListener;
import org.androidannotations.api.view.OnViewChangedNotifier;
import org.joda.time.DateTime;

public final class MainActivity_
    extends MainActivity
    implements HasViews, OnViewChangedListener
{
    private final OnViewChangedNotifier onViewChangedNotifier_ = new OnViewChangedNotifier();
    private final IntentFilter intentFilter1_ = new IntentFilter();
    private final BroadcastReceiver networkChangesReceiver_ = new BroadcastReceiver() {

        public void onReceive(Context context, Intent intent) {
            MainActivity_.this.networkChanges();
        }
    }
    ;

    @Override
    public void onCreate(Bundle savedInstanceState) {
        OnViewChangedNotifier previousNotifier = OnViewChangedNotifier.replaceNotifier(onViewChangedNotifier_);
        init_(savedInstanceState);
        super.onCreate(savedInstanceState);
        OnViewChangedNotifier.replaceNotifier(previousNotifier);
        setContentView(R.layout.activity_main_activity_menu);
    }

    private void init_(Bundle savedInstanceState) {
        OnViewChangedNotifier.registerOnViewChangedListener(this);
        restoreSavedInstanceState_(savedInstanceState);
        intentFilter1_.addAction("android.net.conn.CONNECTIVITY_CHANGE");
    }

    @Override
    public void setContentView(int layoutResID) {
        super.setContentView(layoutResID);
        onViewChangedNotifier_.notifyViewChanged(this);
    }

    @Override
    public void setContentView(View view, LayoutParams params) {
        super.setContentView(view, params);
        onViewChangedNotifier_.notifyViewChanged(this);
    }

    @Override
    public void setContentView(View view) {
        super.setContentView(view);
        onViewChangedNotifier_.notifyViewChanged(this);
    }

    public static MainActivity_.IntentBuilder_ intent(Context context) {
        return new MainActivity_.IntentBuilder_(context);
    }

    public static MainActivity_.IntentBuilder_ intent(android.app.Fragment fragment) {
        return new MainActivity_.IntentBuilder_(fragment);
    }

    public static MainActivity_.IntentBuilder_ intent(android.support.v4.app.Fragment supportFragment) {
        return new MainActivity_.IntentBuilder_(supportFragment);
    }

    @Override
    public void onViewChanged(HasViews hasViews) {
        this.toolbar = ((Toolbar) hasViews.findViewById(R.id.toolbar));
        this.menuList = ((ListView) hasViews.findViewById(R.id.menuList));
        this.drawerPane = ((RelativeLayout) hasViews.findViewById(R.id.drawerPane));
        this.drawerLayout = ((DrawerLayout) hasViews.findViewById(R.id.drawerLayout));
        this.logo = ((ImageView) hasViews.findViewById(R.id.logo));
        if (this.logo!= null) {
            this.logo.setOnClickListener(new OnClickListener() {

                @Override
                public void onClick(View view) {
                    MainActivity_.this.logo();
                }
            }
            );
        }
        if (this.menuList!= null) {
            ((AdapterView<?> ) this.menuList).setOnItemClickListener(new OnItemClickListener() {

                @Override
                public void onItemClick(AdapterView<?> parent, View view, int position, long id) {
                    MainActivity_.this.menuList(position);
                }
            }
            );
        }
        afterViews();
    }

    @Override
    public void onSaveInstanceState(Bundle bundle_) {
        super.onSaveInstanceState(bundle_);
        bundle_.putSerializable("navItems", navItems);
        bundle_.putInt("inAppBillingSetupResult", inAppBillingSetupResult);
        bundle_.putSerializable("lastLoginDate", lastLoginDate);
        bundle_.putSerializable("nextRatingDate", nextRatingDate);
    }

    @SuppressWarnings("unchecked")
    private void restoreSavedInstanceState_(Bundle savedInstanceState) {
        if (savedInstanceState == null) {
            return;
        }
        navItems = ((ArrayList<NavItem> ) savedInstanceState.getSerializable("navItems"));
        inAppBillingSetupResult = savedInstanceState.getInt("inAppBillingSetupResult");
        lastLoginDate = ((DateTime) savedInstanceState.getSerializable("lastLoginDate"));
        nextRatingDate = ((DateTime) savedInstanceState.getSerializable("nextRatingDate"));
    }

    @Override
    public void onResume() {
        super.onResume();
        this.registerReceiver(networkChangesReceiver_, intentFilter1_);
    }

    @Override
    public void onPause() {
        this.unregisterReceiver(networkChangesReceiver_);
        super.onPause();
    }

    public static class IntentBuilder_
        extends ActivityIntentBuilder<MainActivity_.IntentBuilder_>
    {
        private android.app.Fragment fragment_;
        private android.support.v4.app.Fragment fragmentSupport_;

        public IntentBuilder_(Context context) {
            super(context, MainActivity_.class);
        }

        public IntentBuilder_(android.app.Fragment fragment) {
            super(fragment.getActivity(), MainActivity_.class);
            fragment_ = fragment;
        }

        public IntentBuilder_(android.support.v4.app.Fragment fragment) {
            super(fragment.getActivity(), MainActivity_.class);
            fragmentSupport_ = fragment;
        }

        @Override
        public PostActivityStarter startForResult(int requestCode) {
            if (fragmentSupport_!= null) {
                fragmentSupport_.startActivityForResult(intent, requestCode);
            } else {
                if (fragment_!= null) {
                    fragment_.startActivityForResult(intent, requestCode, lastOptions);
                } else {
                    if (context instanceof Activity) {
                        Activity activity = ((Activity) context);
                        ActivityCompat.startActivityForResult(activity, intent, requestCode, lastOptions);
                    } else {
                        context.startActivity(intent, lastOptions);
                    }
                }
            }
            return new PostActivityStarter(context);
        }
    }
}

**Comment by WonderCsabo** [comment]
This is strange because as you can see from the code, the receiver is indeed registered in the `onResume()` method.

**Comment by trramsiq** [comment]
Exactly! It is weird...

**Comment by trramsiq** [comment]
Shouldn't it be reported as bug?

**Comment by miszmaniac** [comment]
My fabric also discovered this bug. 
Weird thing is that it looks like its lifecycle issue, but AFAIK nothing looks suspicious in generated class.

**Comment by WonderCsabo** [comment]
We cannot fix this until there is a reproducing method. The generated class is okay and tested. I do not know how it happens, maybe some devices calling the lifecycle methods in odd order. 😕

**Comment by suomiy** [comment]
Exactly this exception happens to me when I forget to destroy loader in  `onPause()`. The exception does not happen every time, but occurs more often if I change between landscape/portrait mode and close the activity at the same time.

The code skeleton looks like this and exception occurs  in `MyFragment`'s `onPause()`:

```java
public class MyActivity extends android.support.v7.app.ActionBarActivity {
    @AfterViews
    void init() {        
        FragmentListPagerAdapter pagerAdapter = new FragmentListPagerAdapter( // which is android.support.v4.app.FragmentPagerAdapter
                getSupportFragmentManager(), TITLES, new MyFragment_());
        android.support.v4.content.Loader.getLoaderManager().initLoader(LOADER, args, this);
        viewPager.setAdapter(pagerAdapter);
    }

    @Override
    public void onPause() {
        super.onPause();
        // getLoaderManager().destroyLoader(LOADER);
    }

    @Receiver(actions = {Broadcasts.BROADCAST},
            registerAt = Receiver.RegisterAt.OnResumeOnPause)
    public void show(
            @Receiver.Extra(Broadcasts.Extras.EXTRA) String extra,
            @Receiver.Extra(Broadcasts.Extras.EXTRA2) boolean extra2) {
    }
}

public class MyFragment extends android.support.v4.app.Fragment{

    @AfterViews
    protected void init() {
    }
    
    @Background
    @Receiver(actions = Broadcasts.BROADCAST2, registerAt = Receiver.RegisterAt.OnResumeOnPause)
    protected void changed(@Receiver.Extra(Broadcasts.Extras.EXTRA3) boolean extra3) {
    }
}
```

Not sure if this has any relation to the original problem though, but it produces the same exception.

**Comment by dodgex** [comment]
@suomiy it might help if you could produce a full project where this issue is reproducible. also have you tested this on diffrent devices or emulator?

**Comment by suomiy** [comment]
The last comment isn't valid anymore. The exception occured again, but in a different place and I am having a hard time reproducing it.

Now, the problem was that  Fragment's `onPause()` called  `getLoaderManager().destroyLoader(0)`; which called `onPause()`  again. So  `unregisterReceiver()` gets called twice , when this happens. 

It is probably an android problem http://stackoverflow.com/a/9084506.

The fix to this issue could be something similar to this http://stackoverflow.com/a/24986171.

I am attaching the exception (occured on android 4.4.2):
[exception.txt](https://github.com/androidannotations/androidannotations/files/628930/exception.txt)

**Comment by trr-amsiq** [comment]
@dodgex what about surrounding it with try catch?
