### ISSUE TITLE
StickyListHeadersListView has build error with AA 4.1.0

### ISSUE THREAD

**Issue by TomWangTW** [androidannotations/androidannotations#1845]
Hi AA team,
I found AA 4.1 has build error with lib:StickyListHeaders and it works fine when AA 4.0.
soucrce:https://github.com/emilsjolander/StickyListHeaders

When i have an object which like:
@ViewById
 StickyListHeadersListView lvStickyList;

and then i set it ItemClick as below:
@ItemClick(R.id.lvStickyList)
 void itemClick(int position) {

It will cause build error as 
error: incompatible types: StickyListHeadersListView cannot be converted to AdapterView<?>
            ((AdapterView<?> ) this.lvStickyList).setOnItemClickListener(new OnItemClickListener() {
...

Maybe it is a side effect by #1785 Cast views to the required type when adding callbacks.
Any solution for this? Thx.

**Comment by dodgex** [comment]
first of all sorry for the late response.

yeah this is indeed a side effect of #1785. unfortunately I currently have no idea for a good fix.

one possible way is to allow a class parameter to the annotation to specify the class to be used for the cast.

e.g.
```
@ItemClick(value = R.id.lvStickyList, castTo = StickyListHeadersListView.class)
void itemClick(int position) {
}
```
and then generate the cast like
```
((StickyListHeadersListView) this.lvStickyList).setOnItemClickListener(new OnItemClickListener() {
   //...
}
```

but this does not feel clean... @WonderCsabo do you have an idea how to fix this issue?

**Comment by WonderCsabo** [comment]
The `castTo` parameter is horrible. However i am not sure why this error is happening. Why the class cannot be cast to its parent class? 😕

**Comment by dodgex** [comment]
[`StickyListHeadersListView`](https://github.com/emilsjolander/StickyListHeaders/blob/master/library/src/se/emilsjolander/stickylistheaders/StickyListHeadersListView.java#L38) is not a child of `AdapterView` and I'm pretty sure this is also true for `PullToRefreshListView` mentioned in #1871

**Comment by WonderCsabo** [comment]
I am not sure we want to support these badly designed fake `ListView` classes.

**Comment by TomWangTW** [comment]
Well, after i traced the source code of AA, i think it is very hard to support customize view gracefully...
But so many projects used third-party customize view, so if you make sure AA doesn't support it, 
maybe should be written in 4.1 documents or use **instanceof** to check these views could cast to AdapterView or not.

**Comment by WonderCsabo** [comment]
I am closing this one, as i think we should put effort into supporting some `ListView`-ish classes, as development moved to the much robust `RecyclerView` class.
