### ISSUE TITLE
auto-clear previous @UiThread and @Background tasks when delay is present

### ISSUE THREAD

**Issue by dadaeu** [androidannotations/androidannotations#1846]
Hello,

Thank you for this very useful tool.

I have an improvement suggestion.

Example: Launch a task to load some data from network according to what user typed. I use a delayed @Background because the user may continue to write, and cancel that task whenever he/she types another key.

Because @Background annotated method gets overridden, now I create another ( @SupposeUiThread or @UiThread annotated ) method to cancel the task using
BackgroundExecutor.cancelAll( id )
then call the @Background annotated method (which gets overridden).

I would enjoy having this feature implemented in annotation, maybe like this:
@Background( id="an_id", delay=500, autoCancel="true", autoCancelAllowInterrupt="true|false" ... )
I could come with some other names for the parameter: singleTask, unique, cancelExisting, cancelQueued

I guess it could be made by inserting in the generated code
BackgroundExecutor.cancelAll( id, ... )
before 
BackgroundExecutor.execute(...)

A similar change can benefit @UiThread, too.

Thank you

**Comment by WonderCsabo** [comment]
Sorry, but we do not want to further enhance `@Background`. It already has too much parameters. It is for simple cases, for complicated ones, you have to rely on a more serious tool.
