### ISSUE TITLE
Element methodOne(int,int) invalidated by BackgroundHandler

### ISSUE THREAD

**Issue by Everhustle** [androidannotations/androidannotations#1851]
Hello.

Thank you for such an interesting and useful lib.
But, trying to use it, I run into some obstacle, which can not solve by my one. So is it possible to be done with your assistance?
I am confused already with solving this problem which occurse when I use @Backgound annotation. It responds me with "Element methodOne(int,int) invalidated by BackgroundHandler" error, which I can not google..
Use Android Studio, WIN7. 

Regards,
Pavel S.

**Comment by WonderCsabo** [comment]
You should check the error log, there is a real error message which displays what is the problem.

**Comment by WonderCsabo** [comment]
Closing due to lack of response.

**Comment by mayankzen123** [comment]
Please make sure you are using public access specifier before method name. Change

private void methodName() 
to 
public void methodName()
