### ISSUE TITLE
Dynamic URL in Rest services (@Url)

### ISSUE THREAD

**Issue by Sylwekqaz** [androidannotations/androidannotations#1864]
At this moment there is no option to pass URL as parameter to request.
For example how its works in retrofit 

```
public interface APIService {
    @GET
    Call<Users> getUsers(@Url String url);
}
```

**Comment by WonderCsabo** [comment]
I agree, this would be a nice feature. I do not have to develop new features currently, but pull requests are very much welcome.

**Comment by Sylwekqaz** [comment]
I wondered if I could do it, but when I look in source code my brain threw `TooMuchMagicException`

P.S. recently I started to learn Android

**Comment by WonderCsabo** [comment]
@Sylwekqaz after thinking this through, this feature is the same as path parameters, there is no need for a new annotation to achieve what you want:
```java
@Get("{url}")
void callUrl(@Path String url)
```
