### ISSUE TITLE
@ViewById can not user in method

### ISSUE THREAD

**Issue by ceowt** [androidannotations/androidannotations#1866]
such as 
@ViewById
  void set(TextView tv){
//do something
}

warnnig can not found R.id.set.

**Comment by dodgex** [comment]
The Massage says that there is no view with the id `set`. The annotation tries to use the Method Name for Injektion. Use the correct id as Name or better use the view id as annotation Parameter.

**Comment by WonderCsabo** [comment]
Closing due to lack of response.

**Comment by dodgex** [comment]
You forgot to close? :D

**Comment by WonderCsabo** [comment]
Yep, thanks.
