### ISSUE TITLE
Make it easier to use androidannotations in MVP

### ISSUE THREAD

**Issue by bobdeng** [androidannotations/androidannotations#1875]
In MVP mode, I used @EBean as a presenter，but I need to set bean's interface in Activity or View. I want to declare a field in EBean, like this:

  @ViewInterface
  IMyViewInterface viewInterface;

and my Activity or View, implements  the interface. In EBean's generated code, maybe like this:

```
private Context context_;
private Object view_;

private ContactsActions_(Context context, Object view) {
    context_ = context;
    view_ = view;
    init_();
}

public static ContactsActions_ getInstance_(Context context, Object view) {
    return new ContactsActions_(context, view);
}

private void init_() {
  viewInterface = (IMyViewInterface)view_;
}
```

then I can invoke the method in Activity via IMyViewInterface and don't need any set method.

**Comment by bobdeng** [comment]
I already did this in my forked branch

**Comment by dodgex** [comment]
Not sure what exactly you want to achieve but from the [readme](https://github.com/bobdeng/androidannotations/blob/master/README.md) in your fork it looks like you can implement this with a custom plugin.

**Comment by bobdeng** [comment]
No, I must to modify the holder of EBean

**Comment by WonderCsabo** [comment]
You can extend the already existing holders from plugins, [here](https://github.com/androidannotations/androidannotations/blob/b1e1903307d143b22f985d61c8b8e552d9c1c291/AndroidAnnotations/androidannotations-roboguice/roboguice/src/main/java/org/androidannotations/roboguice/handler/RoboGuiceHandler.java#L75) is how.
