### ISSUE TITLE
find error too wast time.

### ISSUE THREAD

**Issue by AllenCoder** [androidannotations/androidannotations#1880]
sometime , i remove some viewid ,but android studio not show where is invalid ,when i build my project , i often get much of error ,to resolve the error , it too long to find. i have to use  git compare where is my change affect 。 can you print the log to find the error .where is valid.

I will be very grateful to you

**Comment by WonderCsabo** [comment]
We log all errors to androidannotations.log by default.

Also, it is possible that you do not see the log in the console, because the error is cut out. See [this](https://github.com/androidannotations/androidannotations/issues/1868#issuecomment-252416119) comment for that.
