### ISSUE TITLE
how can i cancel a network request in @Background?

### ISSUE THREAD

**Issue by chenyusheng** [androidannotations/androidannotations#1882]
i find my app will crash everytime when i destroy a fragment before the request finish.
i try to find the error and i thought it may be network request do not finish , so that after the request finish , the context has be destroy.

**Comment by WonderCsabo** [comment]
You can cancel background tasks with `BackgroundExecutor`, however it just interrupts the thread, which may not help. You have to cancel the network request itself, but using the methods of the network library.
