### ISSUE TITLE
@ItemSelect fails for AutoCompleteTextView

### ISSUE THREAD

**Issue by vgrichina** [androidannotations/androidannotations#1889]
When I try to use `@ItemSelect` with `AutoCompleteTextView` it gives following exception:

`java.lang.ClassCastException: android.support.v7.widget.AppCompatAutoCompleteTextView cannot be cast to android.widget.AdapterView`

Looks like it makes sense to provide special case handling for AutoCompleteTextView, as it has ability to set the same listeners as AdapterView.

**Comment by dodgex** [comment]
There is already a feature request to support AutoCompleteTextView in #1791. I'm closing this issue in favour of the already existing one.
