### ISSUE TITLE
Using @TextChange and @Trace causes compile error.

### ISSUE THREAD

**Issue by ytakahashi1981** [androidannotations/androidannotations#1891]
Hello.
I found a very very small problem on AA 4.1.0.

```java
@Trace
@TextChange(R.id.text)
void onTextChange(int start) {
   // do something
}
```

This code causes compile error because AA makes this code, the variable named 'start' already declared.

```java
@Override
void onTextChange(final int start) {
  :
    long start = System.currentTimeMillis();
  :
}
```

And I couldn't change the argument name because AA processor says

`Unrecognized parameter name. You can only have start, before, or count parameter name. Try to pick a parameter from the android.text.TextWatcher.onTextChanged() method.`

So I can't use `@TextChange` and `@Trace` on the same method.

Thank you.

**Comment by dodgex** [comment]
Thank you for the report. This one should be easy to fix on our side! :)

**Comment by dodgex** [comment]
I just openend PR #1893 to fix this issue.

**Comment by WonderCsabo** [comment]
Fixed. Thanks @dodgex !
