### ISSUE TITLE
Consider using Maven Wrapper

### ISSUE THREAD

**Issue by dodgex** [androidannotations/androidannotations#1894]
We should consider to use [Maven Wrapper](https://github.com/takari/maven-wrapper). :)

Why?
I wanted to do an AndroidAnnotations Build on my Laptop but did not have maven installed there (only worked on projects with gradlew or mvnw on it so far). I added maven wrapper to my local copy and I'd think it would be a good idea to add it to the repo as a easier start and to not need a local maven installation :D

@WonderCsabo wdyt?

**Comment by WonderCsabo** [comment]
I already thought of it. It is a good idea, simplifies the building env setup. Can you contribute?

**Comment by dodgex** [comment]
PR up
