### ISSUE TITLE
Nullpointer with default intent.getExtra methods

### ISSUE THREAD

**Issue by rickbijkerk** [androidannotations/androidannotations#1898]
See code below i have an activity which has a setResult with a byte[] as argument. However when i press the back button on said activity it crashes in the generated class because the intent is null. See code below for the error:

` Bundle extras_ = (((data!= null)&&(data.getExtras()!= null))?data.getExtras():new Bundle());
 byte[] bitmap = data.getByteArrayExtra(BITMAPRESULTKEY_EXTRA);
 ChatFragment_.this.onPictureTaken(resultCode, bitmap);`

the extras_ argument isn't used and the data.getByteArrayExtra gives a nullpointer on backpress of the activity.

**Comment by WonderCsabo** [comment]
Can you post the annotated code?

**Comment by rickbijkerk** [comment]
this is the code that should receive the result:

`	@OnActivityResult(REQUEST_PICTURE)
	void onPictureTaken(int resultCode, @OnActivityResult.Extra(value = TakePictureActivity.BITMAP_RESULT_KEY) final byte[] bitmap)`

and this is where i sent it

`Intent intent = new Intent();
		intent.putExtra(BITMAP_RESULT_KEY, PhotoService.convertPhotoToJPEG(photo));

		setResult(RESULT_OK, intent);

		finish();`

**Comment by rickbijkerk** [comment]
this is the currently generated code:
`Bundle extras_ = (((data!= null)&&(data.getExtras()!= null))?data.getExtras():new Bundle());
                    byte[] bitmap = data.getByteArrayExtra(BITMAPRESULTKEY_EXTRA);`

while i think it should be 

`Bundle extras_ = (((data!= null)&&(data.getExtras()!= null))?data.getExtras():new Bundle());
                    byte[] bitmap = (byte[]) extras_.get(BITMAPRESULTKEY_EXTRA);`

as the extras_ variable bundle is currently unused. Note the cast in the above statement

**Comment by Zulqurnain** [comment]
i facing similar issue , @OnActivityResult annotated method never get's called

**Comment by Zulqurnain** [comment]
Well i fixed that , by passing 'this' instead of 'context' in Activity_.initent(this).start();

**Comment by WonderCsabo** [comment]
@rickbijkerk hmm, we should indeed use the `extras_` variable. @dodgex wdyt?

**Comment by dodgex** [comment]
@WonderCsabo I think this is a good idea

**Comment by WonderCsabo** [comment]
Can you contribute?

**Comment by dodgex** [comment]
I'll see what I can do the next days.

**Comment by dodgex** [comment]
I just opened a PR to correct this.

**Comment by WonderCsabo** [comment]
Fixed, thanks to @dodgex !

**Comment by rickbijkerk** [comment]
looking good thanks!
