### ISSUE TITLE
Update the wiki page to contain the correct quote and a reference to the source

### ISSUE THREAD

**Issue by cagdasgerede** [androidannotations/androidannotations#1899]
Update Home.md of wiki page to have the corrected quote and a reference to the book:

**Robert C. Martin** wrote in "Clean Code: A Handbook of Agile Software Craftsmanship":

> _The ratio of time spent reading [code] versus writing is well over 10 to 1. We are constantly reading old code as part of the effort to write new code. ... [Therefore,] making it easy to read makes it easier to write._

**Comment by dodgex** [comment]
You are right. Mentioning the book is a good idea! :)

But I think I'd do it like this.

<hr/>
**Robert C. Martin** wrote in "Clean Code: A Handbook of Agile Software Craftsmanship":

> _The ratio of time spent reading [code] versus writing is well over 10 to 1. [...] Of course there’s no way to write code without reading it, so making it easy to read actually makes it easier to write._


<hr/>

Full quote / section of the book:
> You get the drift. Indeed, the ratio of time spent reading vs. writing is well over 10:1. We are _constantly_ reading old code as part of the effort to write new code.

> Because this ratio is so high, we want the reading of code to be easy, even if it makes the writing harder. Of course there’s no way to write code without reading it, so _making it easy to read actually makes it easier to write._

@WonderCsabo wdyt?

**Comment by WonderCsabo** [comment]
Good idea, can you contribute @dodgex ?

**Comment by dodgex** [comment]
Wiki updated.

**Comment by WonderCsabo** [comment]
Cool thanks!
