### ISSUE TITLE
Update Wiki page for @FragmentArg

### ISSUE THREAD

**Issue by Zulqurnain** [androidannotations/androidannotations#1900]
According to given docs 

// it should work , but **its not** 
@FragmentArg
  void setOneFragmentArg(@FragmentArg("myStringArgument") String myMessage){
    // do something with myMessage
  }

Correct way
@FragmentArg("myStringArgument")
  void setOneFragmentArg( String myMessage){
    // do something with myMessage
  }

Update the misguided docs , maybe it's a typo

**Comment by dodgex** [comment]
Thank you for the report. I fixed the wiki.
