### ISSUE TITLE
Views are Null in @FragmentArg Method

### ISSUE THREAD

**Issue by Zulqurnain** [androidannotations/androidannotations#1901]
I have following code in my fragment:

@FragmentArg("SOME_KEY")
    public void setsomething(String s) {
        globalVar = s;
        this.myTextView.setText(s.someMethod());
    }

'myTextView' is null here , views are available in @AfterViews i know , but don't you think here purpose of method method fragmentArg die , if we can't update a view ?

**Comment by WonderCsabo** [comment]
Nope. This method only injects the field, that is the only reason. This method is called when we extract the args from the bundle, and at that point the views are not yet available. You have to save to a field in this method, and use that field in `@AfterViews`.
