### ISSUE TITLE
Wrong POST parameters sent (JSON)

### ISSUE THREAD

**Issue by YMonnier** [androidannotations/androidannotations#1903]
Hello,

I try to send JSON body parameter from @POST

I have my RestService:

``` java
@Rest(rootUrl = "http://xxx.herokuapp.com/api", converters = { MyGsonHttpMessageConverter.class})
public interface APIRestService extends RestClientErrorHandling {
    @Post("/login")
    @Accept(MediaType.APPLICATION_JSON)
    @Header(name = "Content-Type", value = "application/json")
    ResponseEntity<JsonElement> login(@Body Map<String, Object> formData);
}
```

And I want to sent this body: 

```json
{
	"auth": {
		"email": "mail@mail.com",
		"password": "mySuperPassword"
	}
}
```

So to create a JSON body I use `MultiValueMap`:

```java
MultiValueMap<String, Object> authParams = new LinkedMultiValueMap<>(); //auth root
MultiValueMap<String, String> sub = new LinkedMultiValueMap<>();

sub("email", email); // {"email" => "mail@mail.com"}
sub("password", password); { // {"email" => "mail@mail.com", "password" => "mySuperPassword"}
authParams.set("auth", params); // {"auth" => {"email" => "mail@mail.com", "password" => "mySuperPassword"}}


ResponseEntity<JsonElement> responseEntity = APIRestService.login(authParams.toSingleValueMap());
```

My problem is when the server receive the request I have this parameter from the login request: 

==> I receive an *array* of string for email field instead of string...
```Parameters: {"auth"=>{"email"=>["test@test.com"], "password"=>"[FILTERED]"}```
instead of 
```Parameters: {"auth"=>{"email"=>"test@test.com", "password"=>"[FILTERED]"}```

Maybe I did a mistake.

Thank you,
YM

**Comment by YMonnier** [comment]
OK
I **solved** my problem by using simple `HashMap` structure instead of `LinkedMultiValueMap `.

```java
Map<String, Object> auth = new HashMap<>();
Map<String, String> sub = new HashMap<>();

sub.set("email", email);
sub.set("password", password); {
auth.put("auth", sub)


ResponseEntity<JsonElement> responseEntity = APIRestService.login(auth);
```

**Comment by dodgex** [comment]
I think this is not actually an androidannotations issue but an issue with the spring rest client or its converter used in background.

If you plan to do more json transfers you might want to consider using classes to represent your json objects instead of self built `Map`s
