### ISSUE TITLE
Extra List = "Unrecognized type", but it extends Parcable

### ISSUE THREAD

**Issue by matecode** [androidannotations/androidannotations#1910]
Hi! I cant build (4.1.0) with this code:
```@EActivity(R.layout.activity_reader)
@OptionsMenu(R.menu.reader_menu)
public class Reader extends Activity  {
    @Extra
    List<SearchResult> searchResults;
...
```
The class SearchResult implements Parcelable, but I get "Error:(73, 5) error: Unrecognized type. Please let your attribute be primitive or implement Serializable or Parcelable or an annotated Parceler bean."

What else can i submit to find/fix the error? Building with 4.1.0 / 4.0.0 give the error. Building up to 3.2 is ok.
So is from 3.3 upwards i cant use the above code.

**Comment by dodgex** [comment]
The Error message tells you what to do. 

Your `SearchResult` class has to implement `Serializable` or `Parcelable` or it needs the `@Parceler` annotation.

**Comment by WonderCsabo** [comment]
@matecode already said `SearchResult` does indeed implement `Parcelable`. The problem here is that `List` is used, which is not implementing `Parcelable` or `Serializable`. `ArrayList` should be used instead.

**Comment by dodgex** [comment]
Oh sorry! My bad. :( 

Thank you for correcting my fail @WonderCsabo :)

**Comment by matecode** [comment]
Many thanks for the help! It's working now 👍

**Comment by SiXuManYan** [comment]
thank you
