### ISSUE TITLE
Remove dead feature branches?

### ISSUE THREAD

**Issue by dodgex** [androidannotations/androidannotations#1914]
Hey @WonderCsabo,

what do you think about removing the (very) old feature branches?

### 129_PackageScan
Last commit 22. Nov. 2011 
Not sure if #129 is actally the related issue... 

### 16_Maven_Archetype
Last commit 2. Feb. 2012
related [issue](https://github.com/androidannotations/androidannotations/issues/16) closed on 20. Jan. 2014 as "wont fix"

### 466_AddExtraInService
Last commit 8. Feb. 2013 
related [PR](https://github.com/androidannotations/androidannotations/pull/500) closed on 21. May 2013  as "wont fix"
related [issue](https://github.com/androidannotations/androidannotations/issues/466) close on 10. Nov. 2014 as "wont fix"

**Comment by WonderCsabo** [comment]
I deleted all of them. Thanks for pointing out!
