### ISSUE TITLE
build is no work

### ISSUE THREAD

**Issue by romantiskt** [androidannotations/androidannotations#1923]
This morning, didn't appear this kind of situation, the project can't build
version:4.2.0
Androidstudio : 2.2
【log:】

`Error:Could not find org.androidannotations:androidannotations:4.2.0-SNAPSHOT.
Searched in the following locations:
    file:/C:/Users/romantiskt/AppData/Local/Android/Sdk/extras/m2repository/org/androidannotations/androidannotations/4.2.0-SNAPSHOT/maven-metadata.xml
    file:/C:/Users/romantiskt/AppData/Local/Android/Sdk/extras/m2repository/org/androidannotations/androidannotations/4.2.0-SNAPSHOT/androidannotations-4.2.0-SNAPSHOT.pom
    file:/C:/Users/romantiskt/AppData/Local/Android/Sdk/extras/m2repository/org/androidannotations/androidannotations/4.2.0-SNAPSHOT/androidannotations-4.2.0-SNAPSHOT.jar
    file:/C:/Users/romantiskt/AppData/Local/Android/Sdk/extras/google/m2repository/org/androidannotations/androidannotations/4.2.0-SNAPSHOT/maven-metadata.xml
    file:/C:/Users/romantiskt/AppData/Local/Android/Sdk/extras/google/m2repository/org/androidannotations/androidannotations/4.2.0-SNAPSHOT/androidannotations-4.2.0-SNAPSHOT.pom
    file:/C:/Users/romantiskt/AppData/Local/Android/Sdk/extras/google/m2repository/org/androidannotations/androidannotations/4.2.0-SNAPSHOT/androidannotations-4.2.0-SNAPSHOT.jar
    file:/C:/Users/romantiskt/AppData/Local/Android/Sdk/extras/android/m2repository/org/androidannotations/androidannotations/4.2.0-SNAPSHOT/maven-metadata.xml
    file:/C:/Users/romantiskt/AppData/Local/Android/Sdk/extras/android/m2repository/org/androidannotations/androidannotations/4.2.0-SNAPSHOT/androidannotations-4.2.0-SNAPSHOT.pom
    file:/C:/Users/romantiskt/AppData/Local/Android/Sdk/extras/android/m2repository/org/androidannotations/androidannotations/4.2.0-SNAPSHOT/androidannotations-4.2.0-SNAPSHOT.jar
    file:/D:/Android/Android Studio/gradle/m2repository/org/androidannotations/androidannotations/4.2.0-SNAPSHOT/maven-metadata.xml
    file:/D:/Android/Android Studio/gradle/m2repository/org/androidannotations/androidannotations/4.2.0-SNAPSHOT/androidannotations-4.2.0-SNAPSHOT.pom
    file:/D:/Android/Android Studio/gradle/m2repository/org/androidannotations/androidannotations/4.2.0-SNAPSHOT/androidannotations-4.2.0-SNAPSHOT.jar
    https://jcenter.bintray.com/org/androidannotations/androidannotations/4.2.0-SNAPSHOT/maven-metadata.xml
    https://jcenter.bintray.com/org/androidannotations/androidannotations/4.2.0-SNAPSHOT/androidannotations-4.2.0-SNAPSHOT.pom
    https://jcenter.bintray.com/org/androidannotations/androidannotations/4.2.0-SNAPSHOT/androidannotations-4.2.0-SNAPSHOT.jar
    https://repo1.maven.org/maven2/org/androidannotations/androidannotations/4.2.0-SNAPSHOT/maven-metadata.xml
    https://repo1.maven.org/maven2/org/androidannotations/androidannotations/4.2.0-SNAPSHOT/androidannotations-4.2.0-SNAPSHOT.pom
    https://repo1.maven.org/maven2/org/androidannotations/androidannotations/4.2.0-SNAPSHOT/androidannotations-4.2.0-SNAPSHOT.jar
    file:/C:/Users/romantiskt/.m2/repository/org/androidannotations/androidannotations/4.2.0-SNAPSHOT/maven-metadata.xml
    file:/C:/Users/romantiskt/.m2/repository/org/androidannotations/androidannotations/4.2.0-SNAPSHOT/androidannotations-4.2.0-SNAPSHOT.pom
    file:/C:/Users/romantiskt/.m2/repository/org/androidannotations/androidannotations/4.2.0-SNAPSHOT/androidannotations-4.2.0-SNAPSHOT.jar
    https://oss.sonatype.org/content/repositories/snapshots/org/androidannotations/androidannotations/4.2.0-SNAPSHOT/maven-metadata.xml
    https://oss.sonatype.org/content/repositories/snapshots/org/androidannotations/androidannotations/4.2.0-SNAPSHOT/androidannotations-4.2.0-SNAPSHOT.pom
    https://oss.sonatype.org/content/repositories/snapshots/org/androidannotations/androidannotations/4.2.0-SNAPSHOT/androidannotations-4.2.0-SNAPSHOT.jar
    https://jitpack.io/org/androidannotations/androidannotations/4.2.0-SNAPSHOT/maven-metadata.xml
    https://jitpack.io/org/androidannotations/androidannotations/4.2.0-SNAPSHOT/androidannotations-4.2.0-SNAPSHOT.pom
    https://jitpack.io/org/androidannotations/androidannotations/4.2.0-SNAPSHOT/androidannotations-4.2.0-SNAPSHOT.jar
【my build.gradle】
`apply plugin: 'com.android.application'
buildscript {
    repositories {
        mavenCentral()
    }
    dependencies {
        // replace with the current version of the Android plugin
        classpath 'com.android.tools.build:gradle:2.2.0'
        // the latest version of the android-apt plugin
        classpath 'com.neenbedankt.gradle.plugins:android-apt:1.8'
    }
}

repositories {
    mavenCentral()
    mavenLocal()
    maven {
        url = 'https://oss.sonatype.org/content/repositories/snapshots'
    }
}

apply plugin: 'com.android.application'
apply plugin: 'com.neenbedankt.android-apt'
def AAVersion = '4.2.0-SNAPSHOT' // change this to your desired version, for example the latest stable: 3.3.2
apt {
    arguments {
        androidManifestFile variant.outputs[0]?.processResources?.manifestFile
        // if you have multiple outputs (when using splits), you may want to have other index than 0
        // If you're using flavors you should use the following line instead of hard-coded packageName
        // resourcePackageName android.defaultConfig.packageName

        // You can set optional annotation processing options here, like these commented options:
        // logLevel 'INFO'
        // logFile '/var/log/aa.log'
    }
}
android {
    compileSdkVersion 23
    buildToolsVersion "23.0.3"

    defaultConfig {
       
        minSdkVersion 15
        targetSdkVersion 22
        multiDexEnabled true
        versionCode 1
        versionName "1.0"
    }
dependencies {
    compile "org.androidannotations:androidannotations-api:$AAVersion"
    apt "org.androidannotations:androidannotations:$AAVersion"
}`

**Comment by dodgex** [comment]
AndroidAnnotations 4.2.0 has been released this weeked. you should change `def AAVersion = '4.2.0-SNAPSHOT'` to `def AAVersion = '4.2.0'`

**Comment by gauravsak** [comment]
@romantiskt Has @dodgex's solution working for you? If yes, please close this bug. Thanks!

**Comment by WonderCsabo** [comment]
Closing due to lack of response.
