### ISSUE TITLE
cannot generated class

### ISSUE THREAD

**Issue by jielundewode** [androidannotations/androidannotations#1924]
i use the androidannotations in my project，but now ,it cannot generated _.class

**Comment by jielundewode** [comment]
here is the log
F:\workspace\Parents2\app\src\main\java\com\beisai\parents\ClassActivity.java:17: 错误: 找不到符号
import com.beisai.fragments.AlertFragment_;
                           ^
  符号:   类 AlertFragment_
  位置: 程序包 com.beisai.fragments
F:\workspace\Parents2\app\src\main\java\com\beisai\parents\BaseActivity.java:14: 错误: 找不到符号
import com.beisai.app.ParentsApp_;
                     ^
  符号:   类 ParentsApp_
  位置: 程序包 com.beisai.app
F:\workspace\Parents2\app\src\main\java\com\beisai\parents\CourseActivity.java:13: 错误: 找不到符号
import com.beisai.fragments.AlertFragment_;
                           ^
  符号:   类 AlertFragment_
  位置: 程序包 com.beisai.fragments
F:\workspace\Parents2\app\src\main\java\com\beisai\adapter\DishAdapter.java:13: 错误: 找不到符号
import com.beisai.parents.DishPicActivity_;
                         ^
  符号:   类 DishPicActivity_
  位置: 程序包 com.beisai.parents
F:\workspace\Parents2\app\src\main\java\com\beisai\adapter\DishPageAdapter.java:8: 错误: 找不到符号
import com.beisai.fragments.DishFragment_;
                           ^
  符号:   类 DishFragment_
  位置: 程序包 com.beisai.fragments
F:\workspace\Parents2\app\src\main\java\com\beisai\fragments\BaseFragment.java:7: 错误: 找不到符号
import com.beisai.parents.LoginActivity_;
                         ^
  符号:   类 LoginActivity_
  位置: 程序包 com.beisai.parents
F:\workspace\Parents2\app\src\main\java\com\beisai\adapter\MainPageAdapter.java:8: 错误: 找不到符号
import com.beisai.fragments.ContactFragment_;
                           ^
  符号:   类 ContactFragment_
  位置: 程序包 com.beisai.fragments
F:\workspace\Parents2\app\src\main\java\com\beisai\adapter\MainPageAdapter.java:9: 错误: 找不到符号
import com.beisai.fragments.GroupFragment_;
                           ^
  符号:   类 GroupFragment_
  位置: 程序包 com.beisai.fragments
F:\workspace\Parents2\app\src\main\java\com\beisai\adapter\MainPageAdapter.java:10: 错误: 找不到符号
import com.beisai.fragments.MainFragment_;
                           ^
  符号:   类 MainFragment_
  位置: 程序包 com.beisai.fragments
F:\workspace\Parents2\app\src\main\java\com\beisai\adapter\MainPageAdapter.java:11: 错误: 找不到符号
import com.beisai.fragments.SettingFragment_;
                           ^
  符号:   类 SettingFragment_
  位置: 程序包 com.beisai.fragments
F:\workspace\Parents2\app\src\main\java\com\beisai\adapter\MainPageAdapter.java:12: 错误: 找不到符号
import com.beisai.im.ChatListFragment_;
                    ^
  符号:   类 ChatListFragment_
  位置: 程序包 com.beisai.im
F:\workspace\Parents2\app\src\main\java\com\beisai\parents\MoreImageActivity.java:14: 错误: 找不到符号
import com.beisai.fragments.AlertFragment_;
                           ^
  符号:   类 AlertFragment_
  位置: 程序包 com.beisai.fragments
F:\workspace\Parents2\app\src\main\java\com\beisai\adapter\PhotoAdapter.java:16: 错误: 找不到符号
import com.beisai.parents.ImageBrowserActivity_;
                         ^
  符号:   类 ImageBrowserActivity_
  位置: 程序包 com.beisai.parents
F:\workspace\Parents2\app\src\main\java\com\beisai\adapter\PhotoAdapter.java:17: 错误: 找不到符号
import com.beisai.parents.MoreImageActivity_;
                         ^
  符号:   类 MoreImageActivity_
  位置: 程序包 com.beisai.parents
F:\workspace\Parents2\app\src\main\java\com\beisai\adapter\SortAdapter.java:15: 错误: 找不到符号
import com.beisai.parents.FriendInfoActivity_;
                         ^
  符号:   类 FriendInfoActivity_
  位置: 程序包 com.beisai.parents
F:\workspace\Parents2\app\src\main\java\com\beisai\adapter\SortAdapter.java:16: 错误: 找不到符号
import com.beisai.parents.LoginActivity_;
                         ^
  符号:   类 LoginActivity_
  位置: 程序包 com.beisai.parents
F:\workspace\Parents2\app\src\main\java\com\beisai\fragments\AlbumFragment.java:10: 错误: 找不到符号
import com.beisai.parents.EduDetailActivity_;
                         ^
  符号:   类 EduDetailActivity_
  位置: 程序包 com.beisai.parents
F:\workspace\Parents2\app\src\main\java\com\beisai\fragments\ContactFragment.java:15: 错误: 找不到符号
import com.beisai.parents.AddFriendsActivity_;
                         ^
  符号:   类 AddFriendsActivity_
  位置: 程序包 com.beisai.parents
F:\workspace\Parents2\app\src\main\java\com\beisai\fragments\ContactFragment.java:16: 错误: 找不到符号
import com.beisai.parents.ClassActivity_;
                         ^
  符号:   类 ClassActivity_
  位置: 程序包 com.beisai.parents
F:\workspace\Parents2\app\src\main\java\com\beisai\fragments\EduFragment.java:9: 错误: 找不到符号
import com.beisai.parents.EduDetailActivity_;
                         ^
  符号:   类 EduDetailActivity_
  位置: 程序包 com.beisai.parents
F:\workspace\Parents2\app\src\main\java\com\beisai\fragments\GroupFragment.java:32: 错误: 找不到符号
import com.beisai.parents.PublishActivity_;
                         ^
  符号:   类 PublishActivity_
  位置: 程序包 com.beisai.parents
F:\workspace\Parents2\app\src\main\java\com\beisai\fragments\GroupFragment.java:34: 错误: 找不到符号
import com.beisai.parents.UserFeedActivity_;
                         ^
  符号:   类 UserFeedActivity_
  位置: 程序包 com.beisai.parents
F:\workspace\Parents2\app\src\main\java\com\beisai\utils\CommonUtils.java:28: 错误: 找不到符号
import com.beisai.parents.LoginActivity_;
                         ^
  符号:   类 LoginActivity_
  位置: 程序包 com.beisai.parents
F:\workspace\Parents2\app\src\main\java\com\beisai\fragments\MainFragment.java:20: 错误: 找不到符号
import com.beisai.event.NotiEvent_;
                       ^
  符号:   类 NotiEvent_
  位置: 程序包 com.beisai.event
F:\workspace\Parents2\app\src\main\java\com\beisai\fragments\MainFragment.java:24: 错误: 找不到符号
import com.beisai.parents.ChargeActivity_;
                         ^
  符号:   类 ChargeActivity_
  位置: 程序包 com.beisai.parents
F:\workspace\Parents2\app\src\main\java\com\beisai\fragments\MainFragment.java:25: 错误: 找不到符号
import com.beisai.parents.CourseActivity_;
                         ^
  符号:   类 CourseActivity_
  位置: 程序包 com.beisai.parents
F:\workspace\Parents2\app\src\main\java\com\beisai\fragments\MainFragment.java:26: 错误: 找不到符号
import com.beisai.parents.DishActivity_;
                         ^
  符号:   类 DishActivity_
  位置: 程序包 com.beisai.parents
F:\workspace\Parents2\app\src\main\java\com\beisai\fragments\MainFragment.java:27: 错误: 找不到符号
import com.beisai.parents.EduActivity_;
                         ^
  符号:   类 EduActivity_
  位置: 程序包 com.beisai.parents
F:\workspace\Parents2\app\src\main\java\com\beisai\fragments\MainFragment.java:28: 错误: 找不到符号
import com.beisai.parents.HandinfoActivity_;
                         ^
  符号:   类 HandinfoActivity_
  位置: 程序包 com.beisai.parents
F:\workspace\Parents2\app\src\main\java\com\beisai\fragments\MainFragment.java:29: 错误: 找不到符号
import com.beisai.parents.LeaveListActivity_;
                         ^
  符号:   类 LeaveListActivity_
  位置: 程序包 com.beisai.parents
F:\workspace\Parents2\app\src\main\java\com\beisai\fragments\MainFragment.java:30: 错误: 找不到符号
import com.beisai.parents.LiveActivity_;
                         ^
  符号:   类 LiveActivity_
  位置: 程序包 com.beisai.parents
F:\workspace\Parents2\app\src\main\java\com\beisai\fragments\MainFragment.java:31: 错误: 找不到符号
import com.beisai.parents.NotifyActivity_;
                         ^
  符号:   类 NotifyActivity_
  位置: 程序包 com.beisai.parents
F:\workspace\Parents2\app\src\main\java\com\beisai\fragments\MainFragment.java:32: 错误: 找不到符号
import com.beisai.parents.PhotoActivity_;
                         ^
  符号:   类 PhotoActivity_
  位置: 程序包 com.beisai.parents
F:\workspace\Parents2\app\src\main\java\com\beisai\fragments\MainFragment.java:34: 错误: 找不到符号
import com.beisai.parents.SchoolActivity_;
                         ^
  符号:   类 SchoolActivity_
  位置: 程序包 com.beisai.parents
F:\workspace\Parents2\app\src\main\java\com\beisai\fragments\MainFragment.java:35: 错误: 找不到符号
import com.beisai.parents.SignActivity_;
                         ^
  符号:   类 SignActivity_
  位置: 程序包 com.beisai.parents
F:\workspace\Parents2\app\src\main\java\com\beisai\fragments\MainFragment.java:36: 错误: 找不到符号
import com.beisai.parents.TrackActivity_;
                         ^
  符号:   类 TrackActivity_
  位置: 程序包 com.beisai.parents
F:\workspace\Parents2\app\src\main\java\com\beisai\fragments\MainFragment.java:90: 错误: 找不到符号
    NotiEvent_ pref;
    ^
  符号:   类 NotiEvent_
  位置: 类 MainFragment
F:\workspace\Parents2\app\src\main\java\com\beisai\fragments\SettingFragment.java:12: 错误: 找不到符号
import com.beisai.event.NotiEvent_;
                       ^
  符号:   类 NotiEvent_
  位置: 程序包 com.beisai.event
F:\workspace\Parents2\app\src\main\java\com\beisai\fragments\SettingFragment.java:13: 错误: 找不到符号
import com.beisai.parents.AddBabyActivity_;
                         ^
  符号:   类 AddBabyActivity_
  位置: 程序包 com.beisai.parents
F:\workspace\Parents2\app\src\main\java\com\beisai\fragments\SettingFragment.java:14: 错误: 找不到符号
import com.beisai.parents.BabyActivity_;
                         ^
  符号:   类 BabyActivity_
  位置: 程序包 com.beisai.parents
F:\workspace\Parents2\app\src\main\java\com\beisai\fragments\SettingFragment.java:16: 错误: 找不到符号
import com.beisai.parents.CardNumActivity_;
                         ^
  符号:   类 CardNumActivity_
  位置: 程序包 com.beisai.parents
F:\workspace\Parents2\app\src\main\java\com\beisai\fragments\SettingFragment.java:17: 错误: 找不到符号
import com.beisai.parents.ChargeActivity_;
                         ^
  符号:   类 ChargeActivity_
  位置: 程序包 com.beisai.parents
F:\workspace\Parents2\app\src\main\java\com\beisai\fragments\SettingFragment.java:18: 错误: 找不到符号
import com.beisai.parents.ExamineActivity_;
                         ^
  符号:   类 ExamineActivity_
  位置: 程序包 com.beisai.parents
F:\workspace\Parents2\app\src\main\java\com\beisai\fragments\SettingFragment.java:19: 错误: 找不到符号
import com.beisai.parents.FindWatchActivity_;
                         ^
  符号:   类 FindWatchActivity_
  位置: 程序包 com.beisai.parents
F:\workspace\Parents2\app\src\main\java\com\beisai\fragments\SettingFragment.java:20: 错误: 找不到符号
import com.beisai.parents.HandleActivity_;
                         ^
  符号:   类 HandleActivity_
  位置: 程序包 com.beisai.parents
F:\workspace\Parents2\app\src\main\java\com\beisai\fragments\SettingFragment.java:21: 错误: 找不到符号
import com.beisai.parents.HistoryActivity_;
                         ^
  符号:   类 HistoryActivity_
  位置: 程序包 com.beisai.parents
F:\workspace\Parents2\app\src\main\java\com\beisai\fragments\SettingFragment.java:22: 错误: 找不到符号
import com.beisai.parents.LoginActivity_;
                         ^
  符号:   类 LoginActivity_
  位置: 程序包 com.beisai.parents
F:\workspace\Parents2\app\src\main\java\com\beisai\fragments\SettingFragment.java:23: 错误: 找不到符号
import com.beisai.parents.MeActivity_;
                         ^
  符号:   类 MeActivity_
  位置: 程序包 com.beisai.parents
F:\workspace\Parents2\app\src\main\java\com\beisai\fragments\SettingFragment.java:25: 错误: 找不到符号
import com.beisai.parents.SOSActivity_;
                         ^
  符号:   类 SOSActivity_
  位置: 程序包 com.beisai.parents
F:\workspace\Parents2\app\src\main\java\com\beisai\fragments\SettingFragment.java:26: 错误: 找不到符号
import com.beisai.parents.SettingActivity_;
                         ^
  符号:   类 SettingActivity_
  位置: 程序包 com.beisai.parents
F:\workspace\Parents2\app\src\main\java\com\beisai\fragments\SettingFragment.java:27: 错误: 找不到符号
import com.beisai.parents.VoiceActivity_;
                         ^
  符号:   类 VoiceActivity_
  位置: 程序包 com.beisai.parents
F:\workspace\Parents2\app\src\main\java\com\beisai\fragments\SettingFragment.java:28: 错误: 找不到符号
import com.beisai.parents.ZhiDouActivity_;
                         ^
  符号:   类 ZhiDouActivity_
  位置: 程序包 com.beisai.parents
F:\workspace\Parents2\app\src\main\java\com\beisai\fragments\SettingFragment.java:66: 错误: 找不到符号
    NotiEvent_ pref;
    ^
  符号:   类 NotiEvent_
  位置: 类 SettingFragment
F:\workspace\Parents2\app\src\main\java\com\beisai\fragments\VideoListFragment.java:24: 错误: 找不到符号
import com.beisai.parents.PlayVideoActivity_;
                         ^
  符号:   类 PlayVideoActivity_
  位置: 程序包 com.beisai.parents
F:\workspace\Parents2\app\src\main\java\com\beisai\parents\AddBabyActivity.java:20: 错误: 找不到符号
import com.beisai.fragments.AlertFragment_;
                           ^
  符号:   类 AlertFragment_
  位置: 程序包 com.beisai.fragments
F:\workspace\Parents2\app\src\main\java\com\beisai\parents\AddBabyActivity.java:21: 错误: 找不到符号
import com.beisai.service.ParentService_;
                         ^
  符号:   类 ParentService_
  位置: 程序包 com.beisai.service
F:\workspace\Parents2\app\src\main\java\com\beisai\parents\AddFriendsActivity.java:16: 错误: 找不到符号
import com.beisai.fragments.AlertFragment_;
                           ^
  符号:   类 AlertFragment_
  位置: 程序包 com.beisai.fragments
F:\workspace\Parents2\app\src\main\java\com\beisai\parents\AtActivity.java:12: 错误: 找不到符号
import com.beisai.fragments.AlertFragment_;
                           ^
  符号:   类 AlertFragment_
  位置: 程序包 com.beisai.fragments
F:\workspace\Parents2\app\src\main\java\com\beisai\parents\BabyActivity.java:30: 错误: 找不到符号
import com.beisai.fragments.AlertFragment_;
                           ^
  符号:   类 AlertFragment_
  位置: 程序包 com.beisai.fragments
F:\workspace\Parents2\app\src\main\java\com\beisai\parents\BindCardActivity.java:18: 错误: 找不到符号
import com.beisai.fragments.AlertFragment_;
                           ^
  符号:   类 AlertFragment_
  位置: 程序包 com.beisai.fragments
F:\workspace\Parents2\app\src\main\java\com\beisai\parents\CardNumActivity.java:17: 错误: 找不到符号
import com.beisai.fragments.AlertFragment_;
                           ^
  符号:   类 AlertFragment_
  位置: 程序包 com.beisai.fragments
F:\workspace\Parents2\app\src\main\java\com\beisai\parents\CartActivity.java:11: 错误: 找不到符号
import com.beisai.fragments.AlertFragment_;
                           ^
  符号:   类 AlertFragment_
  位置: 程序包 com.beisai.fragments
F:\workspace\Parents2\app\src\main\java\com\beisai\parents\ChargeActivity.java:17: 错误: 找不到符号
import com.beisai.fragments.AlertFragment_;
                           ^
  符号:   类 AlertFragment_
  位置: 程序包 com.beisai.fragments
F:\workspace\Parents2\app\src\main\java\com\beisai\parents\CutActivity.java:22: 错误: 找不到符号
import com.beisai.fragments.AlertFragment_;
                           ^
  符号:   类 AlertFragment_
  位置: 程序包 com.beisai.fragments
F:\workspace\Parents2\app\src\main\java\com\beisai\parents\DishActivity.java:12: 错误: 找不到符号
import com.beisai.fragments.AlertFragment_;
                           ^
  符号:   类 AlertFragment_
  位置: 程序包 com.beisai.fragments
F:\workspace\Parents2\app\src\main\java\com\beisai\parents\DishPicActivity.java:16: 错误: 找不到符号
import com.beisai.fragments.AlertFragment_;
                           ^
  符号:   类 AlertFragment_
  位置: 程序包 com.beisai.fragments
F:\workspace\Parents2\app\src\main\java\com\beisai\parents\EduActivity.java:11: 错误: 找不到符号
import com.beisai.fragments.EduFragment_;
                           ^
  符号:   类 EduFragment_
  位置: 程序包 com.beisai.fragments
F:\workspace\Parents2\app\src\main\java\com\beisai\parents\EduActivity.java:12: 错误: 找不到符号
import com.beisai.fragments.VideoListFragment_;
                           ^
  符号:   类 VideoListFragment_
  位置: 程序包 com.beisai.fragments
F:\workspace\Parents2\app\src\main\java\com\beisai\parents\ExamineActivity.java:20: 错误: 找不到符号
import com.beisai.fragments.AlertFragment_;
                           ^
  符号:   类 AlertFragment_
  位置: 程序包 com.beisai.fragments
F:\workspace\Parents2\app\src\main\java\com\beisai\parents\FeedbackActivity.java:9: 错误: 找不到符号
import com.beisai.fragments.AlertFragment_;
                           ^
  符号:   类 AlertFragment_
  位置: 程序包 com.beisai.fragments
F:\workspace\Parents2\app\src\main\java\com\beisai\parents\FindWatchActivity.java:9: 错误: 找不到符号
import com.beisai.fragments.AlertFragment_;
                           ^
  符号:   类 AlertFragment_
  位置: 程序包 com.beisai.fragments
F:\workspace\Parents2\app\src\main\java\com\beisai\parents\FriendInfoActivity.java:16: 错误: 找不到符号
import com.beisai.fragments.AlertFragment_;
                           ^
  符号:   类 AlertFragment_
  位置: 程序包 com.beisai.fragments
F:\workspace\Parents2\app\src\main\java\com\beisai\parents\HandinfoActivity.java:19: 错误: 找不到符号
import com.beisai.fragments.AlertFragment_;
                           ^
  符号:   类 AlertFragment_
  位置: 程序包 com.beisai.fragments
F:\workspace\Parents2\app\src\main\java\com\beisai\parents\HandleActivity.java:19: 错误: 找不到符号
import com.beisai.fragments.AlertFragment_;
                           ^
  符号:   类 AlertFragment_
  位置: 程序包 com.beisai.fragments
F:\workspace\Parents2\app\src\main\java\com\beisai\parents\HistoryActivity.java:10: 错误: 找不到符号
import com.beisai.fragments.AlertFragment_;
                           ^
  符号:   类 AlertFragment_
  位置: 程序包 com.beisai.fragments
F:\workspace\Parents2\app\src\main\java\com\beisai\parents\JiBuActivity.java:15: 错误: 找不到符号
import com.beisai.fragments.AlertFragment_;
                           ^
  符号:   类 AlertFragment_
  位置: 程序包 com.beisai.fragments
F:\workspace\Parents2\app\src\main\java\com\beisai\parents\JiBuCountActivity.java:11: 错误: 找不到符号
import com.beisai.fragments.JiBuCountFragment_;
                           ^
  符号:   类 JiBuCountFragment_
  位置: 程序包 com.beisai.fragments
F:\workspace\Parents2\app\src\main\java\com\beisai\parents\LeaveActivity.java:14: 错误: 找不到符号
import com.beisai.fragments.AlertFragment_;
                           ^
  符号:   类 AlertFragment_
  位置: 程序包 com.beisai.fragments
F:\workspace\Parents2\app\src\main\java\com\beisai\parents\LeaveListActivity.java:14: 错误: 找不到符号
import com.beisai.fragments.AlertFragment_;
                           ^
  符号:   类 AlertFragment_
  位置: 程序包 com.beisai.fragments
F:\workspace\Parents2\app\src\main\java\com\beisai\parents\LiveActivity.java:23: 错误: 找不到符号
import com.beisai.app.ParentsApp_;

**Comment by jielundewode** [comment]
here is the build.gradle
apply plugin: 'com.android.application'

//aa
apply plugin: 'android-apt'
def AAVersion = '3.3.2'


def cfg = rootProject.ext.configuration // 配置
def libs = rootProject.ext.libraries // 库
android {
    compileSdkVersion cfg.compileVersion
    buildToolsVersion cfg.buildToolsVersion

    defaultConfig {
        applicationId "com.beisai.parents"
        minSdkVersion cfg.minVersion
        targetSdkVersion cfg.targetVersion
        versionCode 55
        versionName "1.1.0.1"
    }

    signingConfigs {
        release {
            storeFile file("/babysafe.jks")
            storePassword "88888888"
            keyAlias "babysafe"
            keyPassword "88888888"
        }
    }

    buildTypes {
        release {
            signingConfig signingConfigs.release
            minifyEnabled false
            multiDexEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
        debug {
            multiDexEnabled false
            signingConfig signingConfigs.release
        }
    }
//    dexOptions {
//        javaMaxHeapSize "4g"
//    }
}

dependencies {
    compile fileTree(include: ['*.jar'], dir: 'libs')
    testCompile 'junit:junit:4.12'
    compile libs.appcompat
    //aa
    apt "org.androidannotations:androidannotations:$AAVersion"
    compile "org.androidannotations:androidannotations-api:$AAVersion"

    compile 'com.zhy:okhttputils:2.0.2'
    compile 'com.zhy:autolayout:1.3.6'
    //检测内存泄露问题
    debugCompile 'com.squareup.leakcanary:leakcanary-android:1.4-beta2'
    releaseCompile 'com.squareup.leakcanary:leakcanary-android-no-op:1.4-beta2'
    testCompile 'com.squareup.leakcanary:leakcanary-android-no-op:1.4-beta2'
    //    //双击放大
    compile 'com.bm.photoview:library:1.3.6'
    //glide
    compile 'com.github.bumptech.glide:glide:3.6.1'
    //ios风格弹窗
    compile 'com.bigkoo:alertview:1.0.2'
    //圆角ImageView
    compile 'de.hdodenhof:circleimageview:2.0.0'
    //点击展开
    compile 'com.ms-square:expandableTextView:0.1.4'
    //gson
    compile 'com.google.code.gson:gson:2.5'
    compile project(':RongIM')
    compile project(':flowlayout')
    compile project(':PTR')
    compile project(':ptr2')
    compile project(':db')
    compile project(':stagelibrary')
    compile project(':pickerview')
    compile project(':livelibrary')
    compile project(':expandlv')
    compile project(':imagesellibrary')
    compile project(':badgelibrary')
    compile project(':fcper')

    compile project(':zxing')

    compile 'com.tencent.bugly:crashreport:latest.release'
    compile files('libs/BaiduLBS_Android.jar')
    compile files('libs/alipaySdk-20160120.jar')
    compile files('libs/libammsdk.jar')
    compile 'com.rockerhieu.emojicon:library:1.3.3'
    // compile 'cn.finalteam:galleryfinal:1.4.8.7'
    compile 'com.github.bumptech.glide:glide:3.6.1'
    //百分比布局
    compile 'com.zhy:autolayout:1.3.6'
   // compile 'com.github.lypeer:FcPermissions:v0.0.1'
    compile files('libs/jpush-android-2.1.7.jar')

    compile 'com.zcw:togglebutton-library:1.0.0'//ios开关

    //compile'com.android.support:multidex:1.0.1'
}

//aa
buildscript {
    repositories {
        mavenCentral()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:2.2.3'
        classpath 'com.neenbedankt.gradle.plugins:android-apt:1.4'
    }
}
repositories {
    flatDir {
        dirs 'libs'
    }
    mavenCentral()
    mavenLocal()
    maven { url "https://jitpack.io" }
}
apt {
    arguments {
        androidManifestFile variant.outputs[0].processResources.manifestFile
        resourcePackageName "com.beisai.parents"
    }
}

**Comment by WonderCsabo** [comment]
Please check androidannotations.log in the generated sources directory.

**Comment by jielundewode** [comment]
it is strange，there is no androidannotations.log file

**Comment by jielundewode** [comment]
@WonderCsabo

**Comment by WonderCsabo** [comment]
@jielundewode there should be one. Are you looking at the correct folder. It should be under
`app/build/generated/source/apt` or one of its subdirectories.

**Comment by jielundewode** [comment]
@WonderCsabo  yes ,it is empty,seems androidannotation didnot work

**Comment by WonderCsabo** [comment]
Yes, it seems, but your `build.gradle` file seems to be correct. Can you change your `apt` block to this, to make sure AA is not running?

```groovy
apt {
    arguments {
        androidManifestFile variant.outputs[0].processResources.manifestFile
        resourcePackageName "com.beisai.parents"
        logLevel "TRACE"
        logAppenderConsole "true"
    }
}
```

If AA is running, then it should print messages to the console.

**Comment by jielundewode** [comment]
@WonderCsabo yes,i do what you say,but it didnot work

**Comment by jielundewode** [comment]
my android studio version is 2.2.3

**Comment by jielundewode** [comment]
@WonderCsabo  thanks for your answer,i find the problem,i import the wrong class,now the question is dead

**Comment by AllenCoder** [comment]
i also get this error ,my android studio 2.2.3 . apt doesn't work  there is no androidannotations.log file 

```
apt {
    arguments {
        androidManifestFile variant.outputs[0].processResources.manifestFile
        resourcePackageName "com.beisai.parents"
        logLevel "TRACE"
        logAppenderConsole "true"
    }
}
```

i try this ,but does't work 。

**Comment by jielundewode** [comment]
the problem is not here ，you maybe import the wrong class，check every java file，it is a huge work！


------------------
周杰伦


 




------------------ 原始邮件 ------------------
发件人: "Allen";<notifications@github.com>;
发送时间: 2017年1月22日(星期天) 上午10:10
收件人: "androidannotations/androidannotations"<androidannotations@noreply.github.com>; 
抄送: "山羊"<751495739@qq.com>; "Mention"<mention@noreply.github.com>; 
主题: Re: [androidannotations/androidannotations] cannot generated class(#1924)




i also get this error ,my android studio 2.2.3 . apt doesn't work  there is no androidannotations.log file
 apt {     arguments {         androidManifestFile variant.outputs[0].processResources.manifestFile         resourcePackageName "com.beisai.parents"         logLevel "TRACE"         logAppenderConsole "true"     } }  
i try this ,but does't work 。

**Comment by AllenCoder** [comment]
Yesterday, the project can be normal operation 。However, today can not be re-opened normal operation 。Find a reason is a huge project, there is no obvious log output

**Comment by jielundewode** [comment]
yes,the work is huge，you can just remove new added files！if it works，add file one by one


------------------
周杰伦


 




------------------ 原始邮件 ------------------
发件人: "Allen";<notifications@github.com>;
发送时间: 2017年1月22日(星期天) 上午10:16
收件人: "androidannotations/androidannotations"<androidannotations@noreply.github.com>; 
抄送: "山羊"<751495739@qq.com>; "Mention"<mention@noreply.github.com>; 
主题: Re: [androidannotations/androidannotations] cannot generated class(#1924)




Yesterday, the project can be normal operation 。However, today can not be re-opened normal operation 。Find a reason is a huge project, there is no obvious log output

**Comment by AllenCoder** [comment]
I decided to move out of this library

**Comment by AllenCoder** [comment]
自己挖的坑，自己填，我花了整整一天时间移除了这个依赖库，现在能编译成功。但是部分页面现在一点击就崩溃，还得花两天时间，全部检查测试一遍 。想哭的心都有。

**Comment by WonderCsabo** [comment]
@AllenCoder i am sorry that you had issues, but your behaviour is not really acceptable here.

First of all, your are posted to a really wrong channel. Please next time for usage questions use other channels, like [stackoverflow](http://stackoverflow.com/questions/tagged/android-annotations) or the [mailing list](http://groups.google.com/group/androidannotations) or the [chat](https://gitter.im/excilys/androidannotations). GitHub issues is not a place for these kind of questions, we discuss development (bugs, new features, etc) here. We already show you [this information](https://github.com/excilys/androidannotations/wiki/HowToWriteAnIssue) (guidelines on contributing) on the top of the [new issue page](https://github.com/excilys/androidannotations/issues/new).

Your issue is most likely due to incorrect project setup, however we cannot help because you only added the fragment of the needed information.

I am not sure what are you trying to achieve with stating that you are no longer using the library. AndroidAnnotations is can be used by you for free, the developers are writing it and providing you support for no cost, in their free time. 

Lastly, please use English for communicating on AA Github, as the other users and the contributors does not understand Chinese or any other language.
