### ISSUE TITLE
Support for permissions

### ISSUE THREAD

**Issue by Draftdog** [androidannotations/androidannotations#1926]
This ticket is about a feature request.

Currently there is the [PermissionsDispatcherPlugin](https://github.com/AleksanderMielczarek/AndroidAnnotationsPermissionsDispatcherPlugin) to handle requests for runtime permissions since Android 6.0. It integrates with AA but is still quite cumbersome to use.
The list of annotations can be found here: https://github.com/hotchemi/PermissionsDispatcher

The problem with the current usage is that we still need to manually delegate from our code to a static dispatcher. The dispatchers are generated by the plugin but since AA is agnostic of what actually happens it doesn't delegate the calls automatically and we have to write the same boilerplate code over and over again (once per activity and once per fragment, but only when annotated with `@RuntimePermissions`)

Here's a short example to illustrate the problem, I have omitted the imports for brevity:
```
@RuntimePermissions
@EActivity(R.layout.map_layout)
public class MapActivity extends Activity
{
   ...

   @Click(R.id.myLocationButton)
   void onMyLocationClick()
   {
      zoomIntoMyLocation();
   }

   @NeedsPermission(ACCESS_FINE_LOCATION)
   void zoomIntoMyLocation()
   {
      // code to execute when the permission has been granted
   }

   @OnPermissionDenied(ACCESS_FINE_LOCATION)
   void onLocationPermissionDenied()
   {
       // do something to handle the fact the user did not grant us this permission, e.g. a dialog
   }
}
```

These annotations generate a `MapActivityPermissionsDispatcher` class that is to be used in `MapActivity` like so:
```
{

   // IMPORTANT: all calls to zoomIntoMyLocation() will need to be replaced with calls to
   // MapActivityPermissionsDispatcher.zoomIntoMyLocationWithCheck(MapActivity)

   // we need to add this override
   @Override
   public void onRequestPermissionsResult(int requestCode, @NonNull String[] permissions, @NonNull int[] grantResults)
   {
      // we just need to delegate
      super.onRequestPermissionsResult(requestCode, permissions, grantResults);
      MapActivityPermissionsDispatcher.onRequestPermissionsResult(this, requestCode, grantResults);
   }

}
```

I don't think I need to explain the ugliness of these calls to the dispatcher, they are error prone because it is easy to forget to replace the calls to the original (annotated) method.

However, this is the best the plugin can do .. it cannot generate code into the same file that is generated by AA. And that's exactly why I am writing this feature request. It would already be great if AA would process the annotations and do the following:

- generate the `onRequestPermissionsResult(..)` override in the `MapActivity_` subclass
- generate a `zoomIntoMyLocationWithCheck()` method that will simply delegate to the dispatcher, that way we would just need to call this new method instead .. which is not too bad

The ideal, however, would be to just be able to call `zoomIntoMyLocation()` and have everything handled in the subclass somehow, but I don't think this is possible unless AA generates all of the dispatcher code in the `MapActivity_` subclass. Would this be a possibility?

One thing that comes to mind is when the activity has an AA-annotated abstract parent, if this parent also carries the `@NeedsPermission` on one of its methods then things could get ugly (since static calls don't cleanly override).

Anyway, this is just a suggestion, perhaps it would be even better to just write something new, independently from the 3rd-party plugin .. any ideas?

Cheers
-- Wouter

**Comment by dodgex** [comment]
Hey there,

thank you for this feature request. We [decided](https://github.com/androidannotations/androidannotations/issues/1537) to not build our own permission support. 

You could ask @AleksanderMielczarek if he wants to support this in his [AndroidAnnotationsPermissionsDispatcherPlugin](https://github.com/AleksanderMielczarek/AndroidAnnotationsPermissionsDispatcherPlugin) or you could try to [create a plugin](https://github.com/androidannotations/androidannotations/wiki/Creating-an-AndroidAnnotations-plugin) yourself that adds support for this. If you do your own plugin we can add it to [our list of available plugins](https://github.com/androidannotations/androidannotations/wiki/List-of-AndroidAnnotations-plugins). 

Best regards.

**Comment by Draftdog** [comment]
Hi dodgex,

Sorry I missed that issue. I understand there's no support in AA because it already existed/exists in another plugin, right? 

> I do not think it is a good idea to re-implement that functionality of that lib in AA, even more because it seems only a small fix will make that lib AA-compatible.

I'm quoting @WonderCsabo here. Besides the fact that I'm convinced a native AA implementation would actually be a good idea you wouldn't need to re-implement anything. You would only need to support annotations from a 3rd party plugin, i.e. AA generates code that will call the code generated by the other plugin. I described both solutions in my original request above (native integration, and delegation to the other plugin.)

I'm not sure how you guys are implementing your permission requests but my guess is that you're using the native Android API directly, or some other 3rd party lib, and that's a shame IMHO. I'm surprised it's not already part of AA to be honest, since the benefit would be similar to, or even more than, what we have with `@ViewById`.
Can you tell me how you are handling permissions in your apps? Perhaps I'm missing the obvious here ...

Anyway, I'm perfectly willing to write the necessary code and documentation for this functionality, but I prefer knowing you guys' opinion before going in .. 

Best regards
-- Wouter

**Comment by AleksanderMielczarek** [comment]
Hi,

[AndroidAnnotationsPermissionsDispatcherPlugin](https://github.com/AleksanderMielczarek/AndroidAnnotationsPermissionsDispatcherPlugin) does not generate any code by itself. It just removes `@RuntimePermissions` from generated activity or fragment.

Original idea of plugin was to generate additional `onRequestPermissionsResult` method as @Draftdog described. But it wasn't working because two different annotations processors (AA and PermissionsDispatcher) were using the same `@RuntimePermissions` annotation to generate code and as the result `onRequestPermissionsResult` method wasn't generated. 

One possible workaround is to create additional annotation like `@ERuntimePermissions` just to generate `onRequestPermissionsResult` method:

```
@RuntimePermissions
@ERuntimePermissions
@EActivity(R.layout.map_layout)
public class MapActivity extends Activity {
}
```

Best regards
Aleksander Mielczarek

**Comment by Draftdog** [comment]
Hi Aleksander,

Thanks for your comment and your suggestion. The workaround you propose will definitely work but it would be something that I'ld rather avoid, if possible. You would basically be forcing side-effects of design decisions onto the end-user (i.e. the two annotations).

> But it wasn't working because two different annotations processors (AA and PermissionsDispatcher) were using the same @RuntimePermissions annotation to generate code and as the result onRequestPermissionsResult method wasn't generated.

AA isn't processing the @RuntimePermissions annotation, is it?
Anyway, even if it would be processing it, you would still need to insert code into the file generated by AA .. not sure if it's a good idea to edit files generated by another plugin though.

Cheers
-- Wouter

**Comment by dodgex** [comment]
@Draftdog 
> Can you tell me how you are handling permissions in your apps? Perhaps I'm missing the obvious here ...

As of now i had no need to ask for runtime permissions in my app. so i can't answer you on that. sorry!

> Anyway, even if it would be processing it, you would still need to insert code into the file generated by AA .. not sure if it's a good idea to edit files generated by another plugin though.

Thats what AA plugins are for. They allow you to extend the functionality of AA by adding new annotations and processors to generate additional code for your AA generated classes.


@AleksanderMielczarek 
> Original idea of plugin was to generate additional `onRequestPermissionsResult` method as @Draftdog described. But it wasn't working because two different annotations processors (AA and PermissionsDispatcher) were using the same `@RuntimePermissions` annotation to generate code and as the result `onRequestPermissionsResult` method wasn't generated. 

Arent you still processing the annotation to remove it? The handler should be called and you should be possible to generate code there. Or am I wrong?
