### ISSUE TITLE
FragmentPageAdapter requires a constructor with FragmentManager as argument, thus unable to annotate it as @EBean

### ISSUE THREAD

**Issue by namanjain1993** [androidannotations/androidannotations#1927]
This is a template, please adjust it accordingly to your specific issue.<br/>
You may also want to read our [issue guide](https://github.com/androidannotations/androidannotations/wiki/HowToWriteAnIssue).

**AndroidAnnotations version**:

**Android compile SDK version**:

**Annotated code**:
```java
your code
```

**Expected generated code**:
```java
expected generated code
```

**Actual generated code**:
```java
actual generated code
```

**Stacktrace in case of AA crash**:

**Comment by namanjain1993** [comment]
@EBean
public class PreviewFragmentPageAdapter extends FragmentPagerAdapter {

    public PreviewFragmentPageAdapter(FragmentManager fm) {
        super(fm);
    }
}

**Comment by WonderCsabo** [comment]
@namanjain1993 you should update the template according to your issue, not leave it like this...

You cannot work around this limitation of AA, `@Bean`s must have a `Context` parameter constructor, hence you cannot use a `FragmentPagerAdapter` as a bean.
