### ISSUE TITLE
False negative warning for valid meta-data

### ISSUE THREAD

**Issue by WonderCsabo** [androidannotations/androidannotations#1929]
AA cannot parse a valid meta-data element from the manifest, like this:
```xml
<meta-data
                android:name="com.commonsware.cwac.provider.STREAM_PROVIDER_PATHS"
                android:resource="@xml/file_paths"/>
```

It emits the following warning: 
```
warning: A malformed <meta-data> has been found in the manifest with name com.commonsware.cwac.provider.STREAM_PROVIDER_PATHS
```
This is a valid meta-data, so we should be able to parse it.

**Comment by dodgex** [comment]
also: the warning is ... bad :D a malformed WHAT has been found? :D

**Comment by WonderCsabo** [comment]
It is okay, we print the name of the meta-data element (which is this weird thing in this case).

**Comment by dodgex** [comment]
yeah but still i think the warning should contain the element type in some way.

**Comment by WonderCsabo** [comment]
Oh, the message is correct, just Github removed `<meta-data>`. :)

This is the full message
```
warning: A malformed <meta-data> has been found in the manifest with name com.commonsware.cwac.provider.STREAM_PROVIDER_PATHS
```

**Comment by dodgex** [comment]
Oh. Okay. :)

**Comment by smaugho** [comment]
The problem is that I assumed that always it should have a "value" field, and this is not true. This is the code:

```java
private Map<String, String> extractMetaDataQualifiedNames(NodeList metaDataNodes) {
		Map<String, String> metaDataQualifiedNames = new HashMap<String, String>();
		
		for (int i = 0; i < metaDataNodes.getLength(); i++) {
			Node node = metaDataNodes.item(i);
			Node nameAttribute = node.getAttributes().getNamedItem("android:name");
			Node valueAttribute = node.getAttributes().getNamedItem("android:value");

			if (nameAttribute == null || valueAttribute == null) {
				if (nameAttribute != null) {
					LOGGER.warn("A malformed <meta-data> has been found in the manifest with name {}", nameAttribute.getNodeValue());
				} else {
					LOGGER.warn("A malformed <meta-data> has been found in the manifest");
				}
			} else {
				metaDataQualifiedNames.put(nameAttribute.getNodeValue(), valueAttribute.getNodeValue());
			}
		}
		
		return metaDataQualifiedNames;
	}
```

I will try to make it generic.. Now following the correct syntax for the meta-data tag:

```xml

    <meta-data android:name="string"
               android:resource="resource specification"
               android:value="string" />

```
The method should be able to recollect not only the Value, but also the resource... But all these methods return a Map<String, String>.... so key-value... 

Maybe it would be good to save a Map<String, MetaDataInfo> with MetaData info containing both Value and Resource. 

Any suggestion?

**Comment by smaugho** [comment]
Hi @dodgex , @WonderCsabo  about this functionality, I would like to know if for you is ok to implemente it like I suggested, I was the one that implemente it only taking in Account the value (well to be honest, didn't need the resource in that specific moment).. but to make it more generic, and avoid this error that you are reporting, then a Structure should be used in the Map, I just would like to agree with you about if it is the correct way, and please if you could suggest me where to place this Structure (the class I called MetaDataInfo above).

**Comment by WonderCsabo** [comment]
@dodgex i think `MetadataInfo` is okay. Normally we should only break API in major version, but i think we can do it in this case in a minor version.

**Comment by dodgex** [comment]
@WonderCsabo Yeah. I think you are right.

@smaugho feel free to contribute a fix :)

**Comment by dodgex** [comment]
implemented
