### ISSUE TITLE
Problem in Inheriting with Android Annotations

### ISSUE THREAD

**Issue by r4m1n** [androidannotations/androidannotations#1933]
I have a problem in inheriting from base class when using AndroidAnnotations.<br/>

**AndroidAnnotations version**: 4.2.0

**Android compile SDK version**: 25

**Annotated code**:
**My Base Class:**
```
@EActivity
public abstract class BaseActivity extends AppCompatActivity {

    @ViewById
    Toolbar toolbar;

    @ViewById(R.id.drawer_layout)
    DrawerLayout drawerLayout;

    @ViewById(R.id.nav_view)
    NavigationView navView;
}
```

**My Child Class:**
```
@EActivity(R.layout.activity_main)
public class MainActivity extends BaseActivity {

    @ViewById
    ImageButton btnTabHome;
}
```

**When i build project get following errors:**
##MyProjectBuildPath##\MainActivity_.java
Error:(82, 13) error: toolbar is not public in BaseActivity; cannot be accessed from outside package

Error:(83, 13) error: drawerLayout is not public in BaseActivity; cannot be accessed from outside package

Error:(84, 13) error: navView is not public in BaseActivity; cannot be accessed from outside package

Error:(90, 9) error: cannot find symbol method initBaseViews()

**If i inherit from BaseActivity_, get following errors:**
##MyProjectBuildPath##\MainActivity.java
Error:(19, 35) error: cannot find symbol class BaseActivity_

Error:(17, 1) error: org.androidannotations.annotations.EActivity can only be used on an element that extends android.app.Activity

Warning:(19, 8) Element packagename.MainActivity invalidated by EActivityHandler

**Comment by dodgex** [comment]
Errors like this should be pretty self explaining.
`Error:(82, 13) error: toolbar is not public in BaseActivity; cannot be accessed from outside package`

I would say your BaseActivity is not in the same package as your MainActivity and thus you cannot use  default/package visibility on your fields.

Try to add `protected` visibility to the fields of your `BaseActivity`.

**Comment by r4m1n** [comment]
I'm sorry I did't good attention to that message. It is fixed just by change modifier to `protected`.
thank you.
