### ISSUE TITLE
No log is generated

### ISSUE THREAD

**Issue by AllenCoder** [androidannotations/androidannotations#1939]
![image](https://cloud.githubusercontent.com/assets/8213915/22175100/4d891982-e029-11e6-8fc0-98ebe4962ef9.png)

**Comment by AllenCoder** [comment]
the apt does't work ,no log no _AA file

**Comment by dodgex** [comment]
Can you post your build configuration?

**Comment by dodgex** [comment]
Closing due to lack of response.
