### ISSUE TITLE
How to unit test a custom ClientHttpRequestInterceptor?

### ISSUE THREAD

**Issue by johnjohndoe** [androidannotations/androidannotations#1940]
- **AndroidAnnotations version**: 4.0.0
``` groovy
apt "org.androidannotations:androidannotations:4.0.0"
apt "org.androidannotations:rest-spring:4.0.0"
compile "org.androidannotations:androidannotations-api:4.0.0"
compile "org.androidannotations:rest-spring-api:4.0.0"
```
- **Android compile SDK version**: 23

I wrote a custom interceptor inheriting from `ClientHttpRequestInterceptor`. I would like to unit test it but got stucked because I could not manually instantiate an `HttpRequest`. I saw [a couple of classes in rest-spring-test](https://github.com/androidannotations/androidannotations/tree/androidannotations-4.0.0/AndroidAnnotations/androidannotations-rest-spring/rest-spring-test/src/main/java/org/androidannotations/rest/spring/test) which might be helpful. I also saw [`MockClientHttpRequest`](http://docs.spring.io/spring/docs/current/javadoc-api/org/springframework/mock/http/client/MockClientHttpRequest.html). None of both is exposed in the library I depend on.
Is there another **test dependency** I have to add?

**Comment by dodgex** [comment]
I think this is no android annotations related question but more related to the spring rest project for android. afaik all we do is glue your custom `ClientHttpRequestInterceptor` to the spring rest client.

**Comment by johnjohndoe** [comment]
Are you also providing the glue code spring rest is using to test their interceptors?

**Comment by dodgex** [comment]
Not that i know of. But I actually have no idea how spring rest is testing interceptors. I personally do not use spring rest at all (at least not in android environment).

maybe this hels you? https://svenfila.wordpress.com/2012/01/05/resttemplate-with-custom-http-headers/

**Comment by WonderCsabo** [comment]
Sorry, but this question is not related to AA. Please ask at upstream.

**Comment by johnjohndoe** [comment]
Here is what I came up with ...

``` java
@RunWith(JUnit4.class)
public class CustomRequestInterceptorTest {

	private CustomRequestInterceptor interceptor;

	@Before
	public void setUp() {
		MockitoAnnotations.initMocks(this);
		interceptor = new CustomRequestInterceptor();
	}

	@Test
	public void intercept() throws Exception {
		Request request = new Request();
		interceptor.intercept(request, null, new RequestExecution());
		HttpHeaders headers = request.getHeaders();
		// assertThat()

	private class Request implements HttpRequest {

		HttpHeaders headers = new HttpHeaders();

		@Override
		public HttpMethod getMethod() {
			return null;
		}

		@Override
		public URI getURI() {
			return null;
		}

		@Override
		public HttpHeaders getHeaders() {
			return headers;
		}
	}

	private class RequestExecution implements ClientHttpRequestExecution {

		@Override
		public ClientHttpResponse execute(HttpRequest request, byte[] body) throws IOException {
			return null;
		}

	}

}
```

**Comment by WonderCsabo** [comment]
@johnjohndoe can't you just mock these with `Mockito`? In that case these subclasses would not be required.

**Comment by johnjohndoe** [comment]
Yes. It works. Thanks!
