### ISSUE TITLE
viewDestroyed_ should default to true

### ISSUE THREAD

**Issue by tidbeck** [androidannotations/androidannotations#1942]
I think it make more sens to default `viewDestroyed_` to `true`. This avoids methods annotated with `@IgnoreWhen(IgnoreWhen.State.VIEW_DESTROYED)` to be called before the fragment has been created/recreated.

**AndroidAnnotations version**:
4.2.0

**Android compile SDK version**:
25

**Annotated code**:
```java
@IgnoreWhen(IgnoreWhen.State.VIEW_DESTROYED)
```

**Expected generated code**:
```java
private volatile boolean viewDestroyed_ = true;
```

**Actual generated code**:
```java
private volatile boolean viewDestroyed_;
```

**Comment by dodgex** [comment]
I think this is a valid request. @WonderCsabo wdyt?

**Comment by WonderCsabo** [comment]
I agree. @tidbeck want to contribute this fix?

**Comment by tidbeck** [comment]
@WonderCsabo sure I will give it a try.
