### ISSUE TITLE
Services with START_STICKY

### ISSUE THREAD

**Issue by githubdoramon** [androidannotations/androidannotations#1943]
Is it possible to create a annotated IntentService that runs in a separate thread, so when the app is closed the service keeps running?

Aparently this can be done with a service that returns START_STICKY on onStartCommand... But with a annotated service this does not seems to work.

**Comment by WonderCsabo** [comment]
AndroidAnnotations has no effect on this. Make sure you are starting the generated service.

**Comment by githubdoramon** [comment]
Thx csabo
