### ISSUE TITLE
Multiple Annotations on one Element

### ISSUE THREAD

**Issue by mibzman** [androidannotations/androidannotations#1960]
**AndroidAnnotations version**:4.1.0

**Android compile SDK version**:25

**Annotated code**:
```java
@ViewById
@InstanceState
TextView connection;
```

AA fails to compile with this syntax.  

I would like to be able to save the value/state of a text view or other annotated UI component, instead of having to keep a separate `String` with `@InstanceState` and keep them both updated.

I apologize if this is a duplicate issue, I searched around for solutions but I didn't see this addressed in the documentation, on SO or in any other issues.

**Comment by dodgex** [comment]
Hello @mibzman,

AA does not support `@InstanceState` on `TextView` or other views. And I don't think that there are plans to support this.

**Comment by mibzman** [comment]
That makes sense, since the state of `View`s would be much more complicated than primitives.  

Could we add something to the documentation to make it more clear what the limitations of `@InstanceState` are?  Right now it just says that you can save attributes, which could possibly be interpreted to include views and the like.

**Comment by dodgex** [comment]
Good idea. Feel free to contribute to the wiki.

**Comment by dodgex** [comment]
BTW
> AA fails to compile with this syntax.

what exactly do you mean with fails to compile? is there an exception during compilation or does the generated code not compile?

**Comment by mibzman** [comment]
I'm actually not really sure.  This project is fairly large, so when there is an AA issue I'm pretty sure no classes are generated, so I get a couple of hundred `error: cannot find symbol class 'SomeGeneratedClass_'`, which obfuscates whatever the problem actually is.   

Is there a way to run just AA without attempting to compile the rest of the project?  It would be really helpful to get some kind of error from AA itself instead of a very verbose "something broke"

This probably isn't related to this issue, so feel free to close if you want to.

**Comment by dodgex** [comment]
There is a compilation error added when you try to do `@InstanceState` on a view:
> Error:(35, 9) java: Unrecognized type. Please let your attribute be primitive or implement Serializable or Parcelable or an annotated Parceler bean.

but i also added a short note to the wiki page.
