### ISSUE TITLE
BackgroundExecutor delay can lock up thread if user changes system clock

### ISSUE THREAD

**Issue by ddello32** [androidannotations/androidannotations#1965]
Since BackgroundExecutor uses SystemClock.currentTimeMillis() as base for delay calculation, a change in System Clock (as for example when the Daylight Saving Time starts or ends) can trigger or delay a thread execution, this can lock up the serial execution queue an cause major problems.
A possible solution to this problem would be to use [SystemClock.elapsedRealtime() ](https://developer.android.com/reference/android/os/SystemClock.html#elapsedRealtime()).

**AndroidAnnotations version**:
4.2.0
**Android compile SDK version**:
25

**Comment by dodgex** [comment]
Looks like this is a valid request. @WonderCsabo what do you think?
