### ISSUE TITLE
Method based @ViewsById isEmpty()

### ISSUE THREAD

**Issue by miszmaniac** [androidannotations/androidannotations#1966]
I've tried to used method based @ViewsById method, but found out that method parameter is empty List.
This happens beacuse of wrong order of calls in generated code.
I've also noticed that test of this part of code is incorrect. 
![zrzut ekranu 2017-03-07 11 32 31](https://cloud.githubusercontent.com/assets/1630300/23652595/d2b45d60-0329-11e7-8bcc-a29f5f7aea47.png)

**AndroidAnnotations version**:
4.2.0
**Android compile SDK version**:
25
**Annotated code**:
```java
 @ViewsById({R.id.divider_1, R.id.divider_2, R.id.divider_3, R.id.short_cut_container})
    void init(List<View> views) {
       ...
    }
```

**Expected generated code**:
```java
@Override
    public void onViewChanged(HasViews hasViews) {
        ArrayList<View> list_init_views = new ArrayList<View>();
        View view_divider_1 = hasViews.findViewById(R.id.divider_1);
        View view_divider_2 = hasViews.findViewById(R.id.divider_2);
        View view_divider_3 = hasViews.findViewById(R.id.divider_3);
        View view_short_cut_container = hasViews.findViewById(R.id.short_cut_container);

        if (view_divider_1 != null) {
            list_init_views.add(view_divider_1);
        }
        if (view_divider_2 != null) {
            list_init_views.add(view_divider_2);
        }
        if (view_divider_3 != null) {
            list_init_views.add(view_divider_3);
        }
        if (view_short_cut_container!= null) {
            list_init_views.add(view_short_cut_container);
        }
    {
            List<View> views = null;
            views = list_init_views;
            init(views);
        }
    }
```

**Actual generated code**:
```java
@Override
    public void onViewChanged(HasViews hasViews) {
        ArrayList<View> list_init_views = new ArrayList<View>();
        View view_divider_1 = hasViews.findViewById(R.id.divider_1);
        View view_divider_2 = hasViews.findViewById(R.id.divider_2);
        View view_divider_3 = hasViews.findViewById(R.id.divider_3);
        View view_short_cut_container = hasViews.findViewById(R.id.short_cut_container);

        {
            List<View> views = null;
            views = list_init_views;
            init(views);
        }
        if (view_divider_1 != null) {
            list_init_views.add(view_divider_1);
        }
        if (view_divider_2 != null) {
            list_init_views.add(view_divider_2);
        }
        if (view_divider_3 != null) {
            list_init_views.add(view_divider_3);
        }
        if (view_short_cut_container!= null) {
            list_init_views.add(view_short_cut_container);
        }
    }
```

**Comment by dodgex** [comment]
Thank you for your detailed report. I'll investigate this asap.

**Comment by miszmaniac** [comment]
I was about to make PR, but I didn't manage to configure project:)

I'm not sure if the instructions are up-to-date:)

**Comment by dodgex** [comment]
AFAIK the contribution guide should be up to date. 

where do you have trouble?

**Comment by miszmaniac** [comment]
I can't run functional tests (basically compile tests also, but mvnw install starts tests also

https://github.com/androidannotations/androidannotations/wiki/InstallingEnvironment#running-the-functional-tests

I got Error:Android Source Generator: [androidannotations] AndroidManifest.xml file not found

I've changed those preferences of paths to support /src/main/, so I Have no idea why that is:)

**Comment by dodgex** [comment]
Have you configured intellij to use the correct folders? (see [here](https://github.com/androidannotations/androidannotations/wiki/InstallingEnvironment#importing-into-intellij))

>  Unfortunately, due to an [IntelliJ bug](https://youtrack.jetbrains.com/issue/IDEA-137516), you have to adjust the *AndroidManifest.xml* and *res* folder paths manually. Go to **File** > **Project structure** > **Facets**. For each facet, in the **Structure** tab, change the manifest to point to *src/main/AndroidManifest.xml* inside the module,  and the resources directory to point to *src/main/res* inside the module. In the **Maven** tab, uncheck the *Manifest* and *Resources directory* checkboxes, so IntelliJ will not undo your settings when you reimport the project.
