### ISSUE TITLE
Update wiki for Android plugin 2.3

### ISSUE THREAD

**Issue by dodgex** [androidannotations/androidannotations#1970]
The [Building Project Gradle](https://github.com/androidannotations/androidannotations/wiki/Building-Project-Gradle) has to be updated to reflect the latest "how to" with Android Plugin 2.3

see https://github.com/androidannotations/androidannotations/issues/1964 for details

**Comment by dodgex** [comment]
fixed with https://github.com/androidannotations/androidannotations/wiki/Building-Project-Gradle/6fc7d111809fae867dc124d149050e8fb0eedc64

update of sample projects is done in #1971

**Comment by WonderCsabo** [comment]
@dodgex [this](https://github.com/androidannotations/androidannotations/wiki/CustomizeAnnotationProcessing#gradle) page also needs to be updated.

**Comment by dodgex** [comment]
Done. Thanks for mentioning that page!
