### ISSUE TITLE
Error after using new configuration

### ISSUE THREAD

**Issue by smaugho** [androidannotations/androidannotations#1972]
Hi, when using the new configuration as described in [Building Project Gradle](https://github.com/androidannotations/androidannotations/wiki/Building-Project-Gradle), specifically uncommenting javaCompilerOptions, as in the document:

```gradle
android {
    compileSdkVersion 25
    buildToolsVersion "25.0.2"

    defaultConfig {
        minSdkVersion 9
        targetSdkVersion 25
    }

    // If you have different applicationIds for buildTypes or productFlavors uncomment this block.
    javaCompileOptions {
        annotationProcessorOptions {
            arguments = ["resourcePackageName": android.defaultConfig.applicationId]
        }
    }
}
```

I get this error:

Error:(34, 0) Could not find method javaCompileOptions() for arguments [build_b151qwbivowr98cb68jfe2e30$_run_closure1$_closure7@129b0e8f] on object of type com.android.build.gradle.AppExtension.
<a href="openFile:..\app\build.gradle">Open File</a>

I'm not sure if javaCompileOption is correct in this context. What I wanted was to pass the argument "logLevel".

**Comment by dodgex** [comment]
damn. you are right. I updated all the stuff with this config in the wrong place. this block has to be in the `defaultConfig{}` block. I'll update all the stuff :D

**Comment by dodgex** [comment]
PR and wiki updated. Thanks !
