### ISSUE TITLE
SNAPSHOT builds are not being generated

### ISSUE THREAD

**Issue by EurigJones** [androidannotations/androidannotations#1979]
SNAPSHOT builds are currently not being generated...

https://oss.sonatype.org/content/repositories/snapshots/org/androidannotations/androidannotations/

**Comment by dodgex** [comment]
Thank you for the report. I just opened https://github.com/androidannotations/androidannotations/pull/1982 that should fix snapshot deployment.

**Comment by WonderCsabo** [comment]
Fixed, [SNAPSHOT builds are up](https://oss.sonatype.org/content/repositories/snapshots/org/androidannotations/).
