### ISSUE TITLE
@OptionsItem for android.R.id.home causes lint error

### ISSUE THREAD

**Issue by ened** [androidannotations/androidannotations#1981]
**AndroidAnnotations version**:

4.2.0

**Android compile SDK version**:

Support libs: 25.3.0

**Annotated code**:
```java
    @OptionsItem(android.R.id.home)
    void homeClicked() {
        finish();
    }
```

**Expected generated code**:
```java
    @Override
    public boolean onOptionsItemSelected(MenuItem item) {
        int itemId_ = item.getItemId();
        if (itemId_ == android.R.id.home) {
            homeClicked();
            return true;
        }
        return super.onOptionsItemSelected(item);
    }
```

**Actual generated code**:
```java
    import android.R;

    ...

    @Override
    public boolean onOptionsItemSelected(MenuItem item) {
        int itemId_ = item.getItemId();
        if (itemId_ == R.id.home) {
            homeClicked();
            return true;
        }
        return super.onOptionsItemSelected(item);
    }
```

**lint warning**:
> Don't include android.R here; use a fully qualified name for each usage instead

Seems to be new in Android Tools 23.3.

(or maybe I shouldn't listen for that button at all! 😄)

**Comment by WonderCsabo** [comment]
Yes, it is indeed not a good practice to import the Android `R` class. Unfortunately we do not exactly control how imports are made, our code generator does. But i opened a feature request for this. https://github.com/phax/jcodemodel/issues/51

Until this is fixed, you can set LINT in the *lint.xml* file, to ignore errors in the generated files:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<lint>
    <issue id="all">
        <ignore regexp="build/generated/source/apt/.*"/>
    </issue>
</lint>
```
