### ISSUE TITLE
Catching errors while validating/processing annotations

### ISSUE THREAD

**Issue by smaugho** [androidannotations/androidannotations#1985]
Right now AA gives support for the development of Plugins. While the stability of AA is high, it is probable to have internal crashes while validating or processing Annotations from the plugins.. It would be useful to catch errors in the validation/processing methods... for instance:

```java
	try {
		ElementValidation elementValidation = annotationHandler.validate(annotatedElement);

		AnnotationMirror annotationMirror = elementValidation.getAnnotationMirror();
		for (ElementValidation.Error error : elementValidation.getErrors()) {
			LOGGER.error(error.getMessage(), error.getElement(), annotationMirror);
		}

		for (String warning : elementValidation.getWarnings()) {
			LOGGER.warn(warning, elementValidation.getElement(), annotationMirror);
		}

		if (elementValidation.isValid()) {
			validatedAnnotatedElements.add(annotatedElement);
		} else {
			LOGGER.warn("Element {} invalidated by {}", annotatedElement, annotationName);
		}					
	} catch (Throwable e) {
		LOGGER.error(
	            "Internal crash in element {} with annotation {} while validating. \n"
		    + "Please report this  in https://github.com/androidannotations/androidannotations/issues", 
	            annotatedElement, annotationName
	        );
	}
```

Please note that I refer to AndroidAnnotation site for the report.. It would be good to add in the annoationHandlers a method which contains an URL with the creator of the plugin... Also in the AndroidAnnotationsPlugin, this "issues url" could be provided, so the user knows exactly to who report the given error. The crash report should be written also to the LOGGER, in order to be written to the LogFile and help to determine where the error was.

Note that this would be useful also for developers while making their plugins.

**Comment by smaugho** [comment]
Also, with the issue #1976 was removed the ValidationException which stopped the process for generating classes... 

Right now while processing, all the errors are caught here:

```java
        private <T extends GeneratedClassHolder> void processThrowing(AnnotationHandler<T> handler, Element element, T generatedClassHolder) throws ProcessingException {
		try {
			handler.process(element, generatedClassHolder);
		} catch (Exception e) {
			throw new ProcessingException(e, element);
		}
	}
```

I consider we should follow the same logic, generate an error like when the validation is done (so it would be shown to the user) but continue the process instead of throwing the exception and stop all the generation process (please see issue #1976 to understand the importance of continue generating classes).

**Comment by WonderCsabo** [comment]
@smaugho i am little but confused now. We already have [this mechanism](https://github.com/androidannotations/androidannotations/blob/b1e1903307d143b22f985d61c8b8e552d9c1c291/AndroidAnnotations/androidannotations-core/androidannotations/src/main/java/org/androidannotations/internal/AndroidAnnotationProcessor.java#L132), we print a github link to open a new issue. What are you suggesting exactly?

**Comment by smaugho** [comment]
If any crash occurs right now while validating.. it simply will stop the validation process... now if the validation process is stopped for everybody, as indicated in #1976, we will have a huge amount of errors in AndroidStudio and it would be hard to determine where the error occurred..  so what I propose is to catch the error locally while validating or processing, and continue with the next items, not to stop or the generation process (and consequently the same issue that we were try to solve with #1976).. 

If [this mechanism](https://github.com/androidannotations/androidannotations/blob/b1e1903307d143b22f985d61c8b8e552d9c1c291/AndroidAnnotations/androidannotations-core/androidannotations/src/main/java/org/androidannotations/internal/AndroidAnnotationProcessor.java#L132) is used, all the generation will stop.

Also I'm not sure if the current plugins are able to show their own Issues Url (since each plugin has it's own page, I'm talking about third-party plugins)

**Comment by smaugho** [comment]
Please if you agree with me to add this to AA, I have already this implemented in [my Fork](https://github.com/smaugho/androidannotations/commit/296fc251fe1eb5622b7368f77d03a4c7e95b451e).

**Comment by WonderCsabo** [comment]
I am not sure if it is a good idea to continue generation if there is an exception. That means something went wrong, but we do not know what it is. It is possible that we will end up generating not compiling code. I think it is safer in case of crahes, to stop the entire processing. Yes, the user have to find the crash in buried in lots of errors, but it is still much easier to find (because it is big), and also it is quiet rare if the processing crashes.

**Comment by smaugho** [comment]
I agree that if we catch the crashes in the generation process we can generate dummy code.. but for the validations is not the same, see that in the way it is done the validation, that specific Handler which crashed in the validation will be not included in the generation, so it will not generate code at all, but the validation will continue and all the other info would be generated (solving the *buried* problem)

About the phase where the code is being generated, to be honest I also would like to offer solutions for beginners.. When programmers starts with AA everything is new (more if they have no that much experience)... IMHO, it is really important to catch new users, made them love the framework.... well, when they have this kind of situations, they even don't know what happened, everything just "crashed"... at least I'm talking from my experience working with programmers (many juniors)... If we report the crash properly, it would be much more likely that they know exactly what to do and how to receive help... What I want the most is to do all very very easy to use :). 

Please note also what I did for reporting the Issue URL, I think it could be important for plugins.

**Comment by dodgex** [comment]
Sorry for joining the party that late. :)

I think this is a good idea. We should always try to generate as much as possible. And with this change we can do it. As he says, only annotations that are validated successfully are added to the validated. And imho we can better generate code that might not be compiling but have easy to spot errors instead of still having some cases with heavy amount of errors.

**Comment by WonderCsabo** [comment]
OK. Let's finish the work on #1976, then we can polish this after.
