### ISSUE TITLE
Annotations not working with flavors.

### ISSUE THREAD

**Issue by econBabar** [androidannotations/androidannotations#1987]
This is a template, please adjust it accordingly to your specific issue.<br/>
You may also want to read our [issue guide](https://github.com/androidannotations/androidannotations/wiki/HowToWriteAnIssue).

**AndroidAnnotations version**:
def AAVersion = "4.2.0"

**Android compile SDK version**:
22

**Annotated code**:
```java
@EActivity(R.layout.test)
public class TestActivity extends Activity
{
    @ViewById(R.id.testView)
    TextView textView;
}
```

**Expected generated code**:
```java
expected generated code
```

**Actual generated code**:
```java
actual generated code
```

**Stacktrace in case of AA crash**:
All input files are considered out-of-date for incremental task ':app:compileMobilinkDebugJavaWithJavac'.
Compiling with source level 1.7 and target level 1.7.
file or directory 'D:\Git\Android\Bizstore\app\src\debug\java', not found
file or directory 'D:\Git\Android\Bizstore\app\src\mobilinkDebug\java', not found
Compiling with JDK Java compiler API.

error: The generated pk.com.mobilink.bizstore.R class cannot be found
1 error

**Comment by WonderCsabo** [comment]
Did you specifiy the `resourcePackageName` annotation processing option?

**Comment by econBabar** [comment]
I was following this https://github.com/androidannotations/androidannotations/wiki/FirstActivity

No i didn't. Please guide where should i.

**Comment by econBabar** [comment]
Thanks a lot Csabo. I missed this and was using flavors :(
// If you have different applicationIds for buildTypes or productFlavors uncomment this block.
        //javaCompileOptions {
        //    annotationProcessorOptions {
        //        arguments = ["resourcePackageName": android.defaultConfig.applicationId]
        //    }
        //}
