### ISSUE TITLE
Adding switch case support for Actions like AlertDialog

### ISSUE THREAD

**Issue by maykellopez89** [androidannotations/androidannotations#1989]
AlertDialogs in Declex are really easy using             

$AlertDialog().message(R.string.rate)
                    .positiveButton(R.string.yes)
                    .negativeButton(R.string.no)
                    .neutralButton(R.string.ask);

and then handling the answer like 
     if ($AlertDialog.PositiveButtonPressed){
          // some code here
      }
     if ($AlertDialog.NegativeButtonPressed){
          // some code here
      }
     if ($AlertDialog.NeutralButtonPressed){
          // some code here
      }

but it could be nicer if the answer was handled like this:
    switch ($AlertDialog.Result){
        case $AlertDialog.PositiveButtonPressed:
             // some code here
        break;
        case $AlertDialog.NegativeButtonPressed:
             // some code here
        break;
        case $AlertDialog.NeutralButtonPressed:
             // some code here
        break;
    }

**Comment by WonderCsabo** [comment]
Please report it to the Declex project.
