### ISSUE TITLE
java.lang.NullPointerException equal at generate class

### ISSUE THREAD

**Issue by sattha** [androidannotations/androidannotations#1990]
I don't know why it would happen like this, please check ... even you are use 

> final static String ACTIONS_ON_INCOMING_CALL

to check equal but it seem that it can be null anyway. I found this error happen on @EReceiver and @EIntentService.

**AndroidAnnotations version**: 4.2.0

**Android compile SDK version**: 25

**Annotated code**:
```java
@EReceiver
public class PhoneReceiver extends BroadcastReceiver {

    public static String TAG = "PhoneStateReceiver";

    @ReceiverAction(actions = "android.intent.action.PHONE_STATE")
    public void onIncomingCall(Intent intent) {
        
    }

    @Override
    public void onReceive(Context context, Intent intent) {
        
    }
}
```

**Expected generated code**:
```java
public final class PhoneReceiver_
    extends PhoneReceiver
{
    public final static String ACTIONS_ON_INCOMING_CALL = "android.intent.action.PHONE_STATE";

    @Override
    public void onReceive(Context context, Intent intent) {
        init_(context);
        super.onReceive(context, intent);
        String action = intent.getAction();
        if (action == null) {
            return;
        }
        if (action.equals(ACTIONS_ON_INCOMING_CALL)) {
            PhoneReceiver_.this.onIncomingCall(intent);
            return;
        }
    }

    private void init_(Context context) {
    }
}
```

**Actual generated code**:
```java
public final class PhoneReceiver_
    extends PhoneReceiver
{
    public final static String ACTIONS_ON_INCOMING_CALL = "android.intent.action.PHONE_STATE";

    @Override
    public void onReceive(Context context, Intent intent) {
        init_(context);
        super.onReceive(context, intent);
        String action = intent.getAction();
        if (ACTIONS_ON_INCOMING_CALL.equals(action)) {
            PhoneReceiver_.this.onIncomingCall(intent);
            return;
        }
    }

    private void init_(Context context) {
    }
}
```

**Stacktrace in case of AA crash**:

Exception java.lang.RuntimeException: Unable to start receiver com.alphacansend.mobile.receiver.PhoneReceiver_: java.lang.NullPointerException: Attempt to invoke virtual **method 'boolean java.lang.String.equals(java.lang.Object)' on a null object reference**
android.app.ActivityThread.handleReceiver (ActivityThread.java:2732)
android.app.ActivityThread.-wrap14 (ActivityThread.java)
android.app.ActivityThread$H.handleMessage (ActivityThread.java:1421)
android.os.Handler.dispatchMessage (Handler.java:102)
android.os.Looper.loop (Looper.java:148)
android.app.ActivityThread.main (ActivityThread.java:5421)
java.lang.reflect.Method.invoke (Method.java)
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:726)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:616)

**Comment by dodgex** [comment]
Strange... It should not be possible that this field is null.

**Comment by dodgex** [comment]
Also... from the stacktrace it looks that this issue is not in the receiver itself. It looks more like an issue in `ActivityThread.handleReceiver`. It does not mention your source file or the `onReceive` method. I think it is not an AndroidAnnotations related issue.

**Comment by sattha** [comment]
I'll try to investigate more from logical

**Comment by dodgex** [comment]
I'll close this issue as I'm pretty sure that this is no AA issue. In case your investigation can prove me wrong feel free to reopen this issue.
