### ISSUE TITLE
@AfterViews Method execute two times

### ISSUE THREAD

**Issue by zejiaohe** [androidannotations/androidannotations#1992]
in my MainActivity,i use @EActivity(R.layout.activity_main)  android in   @AfterViews
    public void afterViews(){} init,but it go to method afterviews for two times,why ？

**Comment by dodgex** [comment]
In most cases this is caused be either calling `setContentView` in the `onCreate` in addition to providing the layou to the `@EActivity` annotation or you are having a custom parent class that has a name with the same method and that also has the `@AfterViews` annotation.

**Comment by dodgex** [comment]
Closing due to lack of response. Feel free to reopen this issue if you still have problems with this.
