### ISSUE TITLE
Broken link AbstractIntentService

### ISSUE THREAD

**Issue by maykellopez89** [androidannotations/androidannotations#1993]
Hi, I was looking in the enhanced Intent Services documentation (https://github.com/androidannotations/androidannotations/wiki/Enhance-IntentServices) and found a broken link when trying to see the AbstractIntentService implementation(https://github.com/androidannotations/androidannotations/blob/develop/AndroidAnnotations/androidannotations-api/src/main/java/org/androidannotations/api/support/app/AbstractIntentService.java).

**Comment by dodgex** [comment]
Thank you for the report. I fixed the link in the wiki!
