### ISSUE TITLE
@CheckedChange doesn't work on Switch

### ISSUE THREAD

**Issue by wahyuprihantoro** [androidannotations/androidannotations#1994]
I have a switch on my layout:
` <Switch
                android:id="@+id/mySwitch"
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:layout_alignParentRight="true" />`
The @CheckedChange annotations doesn't work on mySwitch above. How to get listener from mySwitch using android annotations? Thanks.

**Comment by WonderCsabo** [comment]
Please post your code.

**Comment by WonderCsabo** [comment]
Closing due to lack of response.

**Comment by dodgex** [comment]
I recently did a small Test project with Switch und checkedchange annotation. No issues.

**Comment by dodgex** [comment]
I recently did a small Test project with Switch und checkedchange annotation. No issues.
