### ISSUE TITLE
Markdown not rendering in Github documentation for AA

### ISSUE THREAD

**Issue by radixdiaboli** [androidannotations/androidannotations#1995]
Not really sure if this is the correct place to post this.  In the Cookbook section of the documentation, the rendered page shows the markdown syntax, instead of rendering into links:

https://github.com/androidannotations/androidannotations/wiki/Cookbook

This has been like this for a while.

Also, I went to read the issue guidlines, and there's a similar issue with headings:

https://github.com/androidannotations/androidannotations/wiki/HowToWriteAnIssue

**Comment by dodgex** [comment]
Thank you for the report. It Looks like github changed The rendering...

**Comment by dodgex** [comment]
I fixed both sites. But I think one should review all wiki pages to ensure everything is rendered correctly.

**Comment by WonderCsabo** [comment]
@dodgex can you show which edit had to be made? Maybe we can `grep` for the old format.

**Comment by WonderCsabo** [comment]
Most of these are fixed now.
