### ISSUE TITLE
Is it possible to set the Preferences Name on an @SharedPref?

### ISSUE THREAD

**Issue by kihaki** [androidannotations/androidannotations#1999]
**AndroidAnnotations version**: 4.00

**Android compile SDK version**: 23

**Annotated code**:
```java
@SharedPref(value = Scope.UNIQUE, mode = Context.MODE_PRIVATE)
public interface UserDataSharedPreferences {
```

Is it possible to give the generated Preference class a custom name? The reason for this is that we are migrating a custom implementation to AndroidAnnotations' implementation of SharedPrefs.

Generated AndroidAnnotations' Preferences initializes like so:
```java
super(context.getSharedPreferences("UserDataSharedPreferences", 0));
```

I am trying to set a custom value for "UserDataSharedPreferences", since I want the app to access an existing SharedPreferences.

As far as I can see this is not possible right now, but maybe I am missing something? Could this be added to future versions of AA?

**Comment by dodgex** [comment]
You can use the [name](https://github.com/androidannotations/androidannotations/blob/androidannotations-4.3.0/AndroidAnnotations/androidannotations-core/androidannotations-api/src/main/java/org/androidannotations/annotations/sharedpreferences/SharedPref.java#L116) parameter of `@SharedPref` that has been added in `4.3.0`.
