### ISSUE TITLE
support kotlin in android studio ?   Three are many errors in my project if I use kotlin.  For example:

### ISSUE THREAD

**Issue by zhouwenhao** [androidannotations/androidannotations#2003]
support kotlin in android studio ?   Three are many errors in my project if I use kotlin.  For example:
Unresolved refrence: xxxx_

**Comment by WonderCsabo** [comment]
[We already have Kotlin support](https://github.com/androidannotations/androidannotations/tree/develop/examples/kotlin). What errors do you have?

**Comment by zhouwenhao** [comment]
Like this: Unresolved refrence: LoginActivity_

**Comment by dodgex** [comment]
have you properly set up your project? have a look at the build.gradle in the sample @WonderCsabo has linked. Look for usage `kapt`.

**Comment by nemesis06101986** [comment]
Hi guys, I'm having a similar issue. I've configured my build.graddle acording to the build.graddle in the example project you've linked. But I'm receiving  this when building:

> Error:(22, 0) Could not get unknown property 'processResourcesTask' for ApkVariantOutputImpl_Decorated{apkData=Main{type=MAIN, fullName=debug, filters=[]}} of type com.android.build.gradle.internal.api.ApkVariantOutputImpl.

This is my build.gradle

```
apply plugin: 'com.android.application'
apply plugin: 'kotlin-android'
apply plugin: 'kotlin-kapt'

android {
    compileSdkVersion 25
    buildToolsVersion "25.0.2"
    defaultConfig {
        applicationId "com.asillybug.fredagsskamtet"
        minSdkVersion 19
        targetSdkVersion 25
        versionCode 1
        versionName "1.0"
    }
    sourceSets {
        main.java.srcDirs += "src/main/kotlin"
    }
}

kapt {
    arguments {
        arg("androidManifestFile", variant.outputs[0].processResourcesTask.manifestFile)
    }
}

def AAVersion = "4.3.0"

dependencies {
    compile "org.jetbrains.kotlin:kotlin-stdlib-jre7:$kotlin_version"
    compile 'com.android.support:appcompat-v7:25.3.1'
    compile 'com.android.support.constraint:constraint-layout:1.0.2'

    kapt "org.androidannotations:androidannotations:$AAVersion"
    compile "org.androidannotations:androidannotations-api:$AAVersion"
}

```

**Comment by dodgex** [comment]
@nemesis06101986 to resolve your issue remove the `kapt {}` block. but when you are using the latest 3.0 android plugin you might get an error that AA can not find the `AndroidManifest.xml`... for that error i already opened a [PR](https://github.com/androidannotations/androidannotations/pull/2006) to fix it.

**Comment by nemesis06101986** [comment]
Thanks @dodgex . That was actually my problem, and the reason why I added the `kapt{}` block.

I'll wait for an update on this then. Thanks for the info

**Comment by WonderCsabo** [comment]
This issue is fixed. You can try it in the snapshot release.

**Comment by carloxavier** [comment]
@WonderCsabo how can we try the snapshot release?

**Comment by WonderCsabo** [comment]
Check out the wiki. 

https://github.com/androidannotations/androidannotations/wiki/Building-Project-Gradle#snapshots

**Comment by sattha** [comment]
here is my config, to make it work

```
kapt {
    arguments {
        arg("resourcePackageName", android.defaultConfig.applicationId)
        arg("androidManifestFile", variant.outputs[0]?.processResources?.manifestFile)
    }
}
```
