### ISSUE TITLE
Do i have to make my source code open?

### ISSUE THREAD

**Issue by econBabar** [androidannotations/androidannotations#2004]
If i use AndroidAnnotation in my app. AA is GNU, CDDL licensed. "When you distribute your software in an executable form (any form other than source code), you are required to make the source code available as well under the CDDL. The executable form may be released under the CDDL or any CDDL compatible licenses."

So do i have to make my source code open source?

Regards

**Comment by WonderCsabo** [comment]
This project is using the [Apache License 2.0](https://github.com/androidannotations/androidannotations/blob/develop/LICENSE.txt), not GNU.

**Comment by WonderCsabo** [comment]
Sorry. Yeah, we depend on JCodeModel, [which is indeed GNU / CDDL](https://github.com/phax/jcodemodel/blob/master/pom.xml#L4). But you do not actually incorporate this to your app, just run it at compile time. It is a good question that you have to open source your app or not in this case.

**Comment by dodgex** [comment]
It is not AndroidAnnotations that is GNU / CDDL licensed. It is one of our dependencies (CodeModel) that is GNU. But as this dependency is only used for the code generation and will not become part of your app you do not have to worry about that.

As @WonderCsabo mentioned AA itself is Apache License 2.0 and the code generated by AA in your application is license free (you can use your applications license for that code)

**Comment by econBabar** [comment]
Thanks a lot guys for your quick response. These licenses are pretty scary. 
One quick question. If a use a project as it is (no modification in the opensource code) which is gnu or cddl, am i still oblige to open source my app's code or only in case if i make any modification to that gnu/cddl opensource project.

Regards

**Comment by WonderCsabo** [comment]
@econBabar again, CodeModel is not included in your app, it is just used to generate code, no GNU components will be included in your app if you use AA.

**Comment by econBabar** [comment]
I reckon that already. I'm confirming something a bit off the context of AA.

**Comment by WonderCsabo** [comment]
Yes, i you would include a GNU project, that you would have to open source that project, AFAIK.
