### ISSUE TITLE
Kotlin开发的页面没办法跳转到AA注解的页面

### ISSUE THREAD

**Issue by xuchenchen** [androidannotations/androidannotations#2009]
**AndroidAnnotations version：3.3.2**:
**Android compile SDK version*25.0.0*:
kotlin页面进行跳转AA注解页面时会提示Error:(38, 55) Unresolved reference: XXXActivity_
kotlin代码： val intent = Intent(this, XXXActivity_::class.java)
            startActivity(intent)
XXXActivity_已经在mainfest.xml中注册过，并且Java代码进行跳转的时候没问题。
希望能尽快适应kotlin下的调用，辛苦谢了。

**Comment by god6585** [comment]
是在kotlin项目中无法生成XXXActivity_文件，以前编译存在的XXXActivity_文件无法使用 @xuchenchen

**Comment by dodgex** [comment]
Could you in future please write in english? Thanks.

Have you ensured that you correctly set up the annotation processor for kotlin? you need to register the proccessor dependency to `kapt` as seen [here](https://github.com/androidannotations/androidannotations/blob/develop/examples/kotlin/build.gradle#L45)

**Comment by xuchenchen** [comment]
Thank you very much for your answer

中文描述：跳转以前编译存在的XXXActivity_文件无法使用，目前我本地的配置和官方kotlin配置一样，kotlin能正常使用，但是跳转AA注解页面在编译时期就开始报错，提示：Error:(19, 41) Unresolved reference: XXXActivity_

Describe in English：
The file that was compiled prior to the jump was not available, and now my local configuration is the same as the official configuration, but the jump AA annotation page started to report errors at compile time，Error message：(19, 41) Unresolved reference: XXXActivity_

**Comment by WonderCsabo** [comment]
Please share all necessary information, code snippets, sample projects etc, otherwise we cannot figure out what your problem is.

**Comment by xuchenchen** [comment]
Thank you very much for helping me to see the problem, the attachment is a demo of the problem
The computer environment：win10
studio version：2.3.2



xuchen90@126.com
 
发件人： Csaba Kozák
发送时间： 2017-06-08 01:19
收件人： androidannotations/androidannotations
抄送： SimplifyReader; Mention
主题： Re: [androidannotations/androidannotations] Kotlin开发的页面没办法跳转到AA注解的页面 (#2009)
Please share all necessary information, code snippets, sample projects etc, otherwise we cannot figure out what your problem is.

**Comment by WonderCsabo** [comment]
I guess you attached it in the email, but that will not show up here. Please upload it to cloud and paste the share link. Maybe the easiest to upload it to a public GitHub repo.

**Comment by xuchenchen** [comment]
http://test-10007319.cossh.myqcloud.com/ryxallapk/androidannotations/KotlinAnnotations.zip

**Comment by WonderCsabo** [comment]
@xuchenchen i checked your project. The trick here that you must run the Kotlin annotation processor, and not the java one. Here is your fixed `build.gradle` file:

```Groovy
apply plugin: 'com.android.application'
apply plugin: 'kotlin-android'
apply plugin: 'kotlin-android-extensions'
apply plugin: "kotlin-kapt"

def AAVersion = '4.3.0'
android {
    compileSdkVersion 25
    buildToolsVersion "25.0.2"
    defaultConfig {
        applicationId "com.example.kotlinaademo"
        minSdkVersion 14
        targetSdkVersion 25
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
}

kapt {
    arguments {
        arg("androidManifestFile", variant.outputs[0].processResourcesTask.manifestFile)
        arg("resourcePackageName","com.example.kotlinaademo")
    }
}
sourceSets {
    main.java.srcDirs += 'src/main/kotlin'
}
repositories {
    flatDir { dirs 'libs' }
    mavenCentral()
}
dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    androidTestCompile('com.android.support.test.espresso:espresso-core:2.2.2', {
        exclude group: 'com.android.support', module: 'support-annotations'
    })
    //kotlin
    compile "org.jetbrains.kotlin:kotlin-stdlib:$kotlin_version"
    //AA注解
    kapt "org.androidannotations:androidannotations:$AAVersion"
    compile "org.androidannotations:androidannotations-api:$AAVersion"
    compile 'com.android.support:appcompat-v7:25.3.1'
    compile 'com.android.support.constraint:constraint-layout:1.0.2'
    testCompile 'junit:junit:4.12'
}
```

**Comment by xuchenchen** [comment]
I have solved the problem as you said, thank you very much for your careful answer
