### ISSUE TITLE
Abstract Kotlin Fragment not generating fields

### ISSUE THREAD

**Issue by giejay** [androidannotations/androidannotations#2011]
**AndroidAnnotations version**:
4.3.0 
**Android compile SDK version**:
7
**Annotated code**:
```java
@EFragment(R.layout.fragment_file_explorer)
abstract class FileExplorerFragment : Fragment(), Notifyable {
    @Bean
    lateinit open var operationExecutor: OperationExecutor

```

**Expected generated code**:
```java
public final class NetworkFileExplorerFragment_
    extends nl.giejay.subtitle.downloader.fragment.NetworkFileExplorerFragment
    implements HasViews
{
......

    private void init_(Bundle savedInstanceState) {
        // dependencies should be created here, does not happen:(
    }
```

When using kotlin, the fields of the abstract class, a fragment in this case, don't get generated in the implementing members. This worked fine in Java.

I did apply the kapt plugin:     kapt "org.androidannotations:androidannotations:$AAVersion"

**Comment by WonderCsabo** [comment]
Try adding `@JvmField` to the `operationExecutor` field.

**Comment by giejay** [comment]
I tried it:

    @Bean @JvmField
    var operationExecutor: OperationExecutor? = null

And unfortunately it doesnt work.

When I add: 

    @Bean @JvmField
    var operationExecutor2: OperationExecutor? = null 

To the Implementing fragment, the operationExecutor2 is generated:

    private void init_(Bundle savedInstanceState) {
        this.operationExecutor2 = OperationExecutor_.getInstance_(getActivity());
    }

**Comment by WonderCsabo** [comment]
I cannot reproduce this issue. Example code:
```kotlin
@EBean
open class MyBean {
}

@EFragment
abstract class AbstractFragment : Fragment() {

    @Bean
    protected lateinit var myBean: MyBean
}

@EFragment
open class ConcreteFragment : AbstractFragment() {

}
```
In the ConcreteFragment_:
```java
    private void init_(Bundle savedInstanceState) {
        this.myBean = MyBean_.getInstance_(getActivity());
    }
```

**Comment by badoualy** [comment]
Same code with version 4.3.1 (kotlin 1.1.2-5) and I get:
```
private void init_(Bundle savedInstanceState) {

}
```

**Comment by WonderCsabo** [comment]
Can you share the code?

**Comment by badoualy** [comment]
I just used your code from above, copy past, exactly the same

**Comment by WonderCsabo** [comment]
My [example](https://github.com/WonderCsabo/androidannotations/tree/2011_exampleWorking) work as expected for me. Check out.

**Comment by badoualy** [comment]
Ok, the issue is present with version 4.3.1 but fixed with current 4.4.0-SNAPSHOT.

**Comment by WonderCsabo** [comment]
@badoualy are you sure? AA 4.4.0-SNAPSHOT only contains one fix which is unrelated to this.

Moreover, i changed the version number in the example, did a clean build, and still the correct code got generated.

**Comment by badoualy** [comment]
Ok so noob story, I didn't have the
`apply plugin: 'kotlin-kapt'`
No idea why but I thought it wasn't needed since it was working without it.

Sorry for the waste of time.
