### ISSUE TITLE
how to integrate aa in many library

### ISSUE THREAD

**Issue by zjc** [androidannotations/androidannotations#2013]
hi everybody:
    sorry for my pool english. I'm using AndroidAnnotaion, but due to Android Studio 2.3 and Gradle 2.3.0, they said android-apt was obsoleted. And annotationProcessor is a new one. so, I want to know how can I configure annotationProcessor like I do with apt before.when i integrate the aa in library ,i find every library need to integrate the aa；
CommonLibrary:
    compile "org.androidannotations:androidannotations-api:$AAVersion"
    annotationProcessor "org.androidannotations:androidannotations:$AAVersion"
PDLibray:
     compile "org.androidannotations:androidannotations-api:$AAVersion"
    annotationProcessor "org.androidannotations:androidannotations:$AAVersion"
app:
    compile "org.androidannotations:androidannotations-api:$AAVersion"
    annotationProcessor "org.androidannotations:androidannotations:$AAVersion"

app dependencies pdLibrary and pdLibrary dependencies CommonLibrary.

I have other question，how to use aa and dagger2 in one library and project

**Comment by WonderCsabo** [comment]
Your snippet seem to be correct. Dagger integration is described [here](https://github.com/androidannotations/androidannotations/wiki/Dagger2Integration).

**Comment by zjc** [comment]
thanks for your reply
