### ISSUE TITLE
Compatible with Instant app?

### ISSUE THREAD

**Issue by evalo** [androidannotations/androidannotations#2017]
hi, i'm refering to [instant app](https://codelabs.developers.google.com/codelabs/android-instant-apps/index.html?index=..%2F..%2Findex#0) codelab from google i/o, i moved the files from application module to base feature module (no feature module for now), but several times as i tried, the file is not generated. I'd like to know is there anyway i can make it work? 
Thx

**Comment by dodgex** [comment]
I have not tested it yet, but I'm pretty sure it should be compatible. You have to add the AndroidAnnotations processor and dependencies to each module that should use generated files.

**Comment by WonderCsabo** [comment]
@ealden i quickly read through the doc, and instant app module is pretty much the same as a library module. AA should work out of the box. Can you share an example project?

**Comment by thanhthein** [comment]
sdsdsd

**Comment by WonderCsabo** [comment]
What do you mean?

**Comment by jaswanthm** [comment]
The instant app config requires the app to be separated into 3 modules

1. The feature module (with the base code) - com.android.feature
2. The application module - com.android.application
3. The instant app module - com.android.instantapp

Now, since we moved the code from application -> feature module, Android Annotations is not working at all.

I am having the same issue. If someone could help, it would be great. 

So the question again : Is there an android annotations version which supports instant app ?

**Comment by WonderCsabo** [comment]
@jaswanthm AndroidAnnotations fully support library projects. Please try to [configure these as library projects](https://github.com/androidannotations/androidannotations/wiki/Library-projects).

**Comment by ManuelSchmitzberger** [comment]
I'm currently working on Android instant apps by using the [android-topeka](https://github.com/googlesamples/android-topeka) example project.

Everything works as expected, after I'm using AndroidAnnotations on my Activity:


    @EActivity(resName = "activity_start")
    public class StartActivity extends AppCompatActivity {
    ...
    }

If I want to start the **application**(`:installed`) one, everything works, but for the **instant-app**(`:instant`), I get the following error:

```
    :base:javaPreCompileDebugFeature UP-TO-DATE
    error: The generated <applicationId>.R class cannot be found
    1 error
    :base:compileDebugFeatureJavaWithJavac FAILED
```

**Additional Info:**
> If I remove the `application project(':installed')` in the base
> build.gradle I can start the **instant-app** but with the wrong
> **application-id** (configured in the `:installed` project).

**Comment by dodgex** [comment]
@ManuelSchmitzberger this only happens when AndroidAnnotations is added to the project? Looks strange to me, as from what you have posted as errors I'm not sure how AA could be involved in the issue. 🤔

**Comment by dodgex** [comment]
Can you provide an up to date demo project (ready for AS 3.2.1 and latest tooles)? then I can try to check what is worng or needs to be done.

**Comment by ManuelSchmitzberger** [comment]
Thx for your response!

> @ManuelSchmitzberger this only happens when AndroidAnnotations is added to the project? Looks strange to me, as from what you have posted as errors I'm not sure how AA could be involved in the issue.
-> yes.

> Can you provide an up to date demo project (ready for AS 3.2.1 and latest tooles)? then I can try to check what is worng or needs to be done.
[Here](https://www.dropbox.com/s/rinf8mmk7ba95up/androidannotations-instantapp.tgz?dl=0) you can download the project setup.

How you can reproduce:
- run the :instant configuration -> everything fine
- add the `@EActivity(resName = "activity_start")` annotation to the `StartActivity` class (base-project)
- change `android:name="com.test.StartActivity"` to `android:name="com.test.StartActivity_` in the Manifest (also in the base-project)
- now you can see the error:
`error: The generated com.test2.R class cannot be found`

**Comment by dodgex** [comment]
@ManuelSchmitzberger not sure how you got to the r class error...

I updated the project to AS 3.2.1 - as requested - and with latest AA i get AndroidManifest cant be found, as mrhabibi  posted in april.

i'll see if i find a way to fix the manifest finder issue and see if the build works then.

**Comment by dodgex** [comment]
I think i got a working build with instant app. not yet tested if the result runs, and if it works with split/flavours. so i have to do some more testing and cleanup but i'm confident to get it fully working. :)

**Comment by dodgex** [comment]
@ManuelSchmitzberger  can you test for your version of the project configuration if it works with the following config in your `base\build.gradle`

I migrated my project to gradle build plugin 3.2.1 and after fixing the Manifest Finder issues i got the `error: The generated com.test2.R class cannot be found` error but the given option fixed it for me. :)

```
android {
    // ...
    defaultConfig {
        // ...
        javaCompileOptions {
            annotationProcessorOptions {
                arguments = ["resourcePackageName": "com.test"]
            }
        }
    }
}
```

**Comment by ManuelSchmitzberger** [comment]
@dodgex Thank you very much! It's so strange, I've tested that several times and now it seems to work. @
you saved my day!
