### ISSUE TITLE
Documentation - could be clearer?

### ISSUE THREAD

**Issue by nghamilton** [androidannotations/androidannotations#2018]
I am wondering if it is worth considering making the method names in the examples to be more clear in what they actually reference. For example - https://github.com/androidannotations/androidannotations/wiki/AdapterViewEvents has the following:

```
@ItemClick
	public void myListItemClicked
```

But, it should not be the list item that the R.id is derived from, but instead the AdapterView? Perhaps something like this would be more appropriate:

```
@ItemClick
	public void myListView
```

**Comment by WonderCsabo** [comment]
In that example, the id is `R.id.my_list`.
