### ISSUE TITLE
Empty screen when using fragment

### ISSUE THREAD

**Issue by TechnoMag82** [androidannotations/androidannotations#2026]
```
@EFragment(R.layout.fragment_sending_wink)
class SendingWinkFragment : Fragment() {
}
```

```
<?xml version="1.0" encoding="utf-8"?>
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
             xmlns:app="http://schemas.android.com/apk/res-auto"
             xmlns:tools="http://schemas.android.com/tools"
             android:layout_width="match_parent"
             android:layout_height="match_parent"
             android:background="@color/button_gray_text">

    <ImageView
        android:layout_margin="16dp"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:id="@+id/imgBack"
        android:src="@drawable/loveer_back"/>
</LinearLayout>
```

**I'm not using <Fragment android:name:"">**

I push fragment into `<FrameLayout>`

**Comment by dodgex** [comment]
How do you create the Fragment?

**Comment by dodgex** [comment]
It should be something like ` SendingWinkFragment _.builder().build()`

**Comment by dodgex** [comment]
also your class should be declared as `open`

**Comment by TechnoMag82** [comment]
I create Fragment : var sendingFragment: SendingFragment = SendingFragment()
When
var sendingFragment: SendingFragment = SendingFragment _.builder().build()
compilation error:
Error:(31, 60) Please specify constructor invocation; classifier 'SendingFragment' does not have a companion object

**Comment by dodgex** [comment]
remove the space between `SendingFragment` and the underscroe `_`. It should read `SendingFragment_` That space was typo in my previous comment.

**Comment by TechnoMag82** [comment]
Sorry/ But same error/

**Comment by dodgex** [comment]
Hmmm. are there other errors in the log? is the fragment class declared as open? I did the same in my project two days ago (used kotlin based AA fragment in a kotlin class) nad no error

```
@EFragment(R.layout.fragment_station_select)
open class StationSelectFragment : Fragment() {
}
```
and ```val fragment = StationSelectFragment_.builder().build()` in my activity...

**Comment by TechnoMag82** [comment]
I used android.support.v4.app.Fragment. Fragment class is open.

**Comment by dodgex** [comment]
I`m using support fragment too. As mentioned for me this works, can you share the project for me to reproduce this issue?

**Comment by TechnoMag82** [comment]
[TestAnnotations.zip](https://github.com/androidannotations/androidannotations/files/1153677/TestAnnotations.zip)

**Comment by dodgex** [comment]
you need to add `apply plugin: 'kotlin-kapt'` and `kapt 'org.androidannotations:androidannotations:4.3.1'` (you should be able to remove the `annotationProcessor` line from dependencies)

also you need to add `lateinit` to the injected fields. requires you to remove the initializer (`=null`) but this allows you to remove the `?` from the type.

with this changes it builds and runs on emulator.

**Comment by TechnoMag82** [comment]
Thank you.
@ViewById(R.id.imgBack)
private lateinit var imgBack: ImageView

Private fields for annotations is not possible?

**Comment by dodgex** [comment]
No. As the generated subclass has to set the value but as private it can not access it. but you can use protected.

**Comment by dodgex** [comment]
As I assume this issue fixed I'll close it. If you still have issues with this feel free to reopen the issue or for other problems create a new one.
