### ISSUE TITLE
Duplicate files copied in APK androidannotations-api.properties using 4.4.0-SNAPSHOT

### ISSUE THREAD

**Issue by dderakhshani** [androidannotations/androidannotations#2027]
I can not build my project when using 4.4.0-SNAPSHOT. the other versions of the AA work properly. It does not depend on android sdk version.
The Error is as follow:
Error:java.lang.RuntimeException: com.android.build.api.transform.TransformException: com.android.builder.packaging.DuplicateFileException: Duplicate files copied in APK androidannotations-api.properties

**Comment by WonderCsabo** [comment]
Please check your dependencies, you probably have different versions of the same jar. Can you post your `build.gradle`?

**Comment by dderakhshani** [comment]
The other versions of the AA work properly with my other dependencies.

Project Gradle:
buildscript {
    repositories {
        jcenter()
        maven { url = 'https://oss.sonatype.org/content/repositories/snapshots' }
        maven { url 'https://jitpack.io' }
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:2.3.3'
        classpath "io.realm:realm-gradle-plugin:3.3.1"
        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

repositories {
    mavenCentral()
    mavenLocal()
}

allprojects {
    repositories {
        jcenter()
        maven {url = 'https://oss.sonatype.org/content/repositories/snapshots'}
        maven { url 'https://jitpack.io' }
    }

}

App Gradle:

apply plugin: 'com.android.application'
apply plugin: 'realm-android'

def AAVersion = '4.4.0-SNAPSHOT'
dependencies {
    annotationProcessor "org.androidannotations:androidannotations:$AAVersion"
    compile "org.androidannotations:androidannotations-api:$AAVersion"
}

android {

    compileSdkVersion 25
    buildToolsVersion '25.0.0'

    defaultConfig {
        applicationId "com.nilsa.app.behnama"
        minSdkVersion 16
        targetSdkVersion 23
        versionCode 1
        versionName "1.0"
    }

    dataBinding {
        enabled = true
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }

}

dependencies {
    compile fileTree(include: ['*.jar'], dir: 'libs')
    compile files('libs/gson-2.4.jar')
    compile files('libs/glide-3.7.0.jar')
    compile files('libs/core-3.2.0.jar')
    compile 'com.android.support:appcompat-v7:25.3.1'
    compile 'com.android.support:design:25.3.1'
    compile 'com.android.support:support-v4:25.3.1'
    compile 'com.android.support:cardview-v7:25.3.1'
    compile 'com.android.support:gridlayout-v7:25.3.1'
    compile 'com.android.support:recyclerview-v7:25.3.1'
    compile 'com.android.support.constraint:constraint-layout:+'
    compile 'com.1gravity:android-rteditor:1.6.2'
    compile 'com.cocosw:bottomsheet:1.+@aar'
    compile 'com.pkmmte.view:circularimageview:1.1'
    compile 'de.hdodenhof:circleimageview:2.1.0'
    compile 'net.gotev:uploadservice:3.2.4'
    compile 'net.gotev:uploadservice-okhttp:3.2.4'
    compile 'org.jsoup:jsoup:1.10.2'
    testCompile 'junit:junit:4.12'
    compile 'uk.co.chrisjenx:calligraphy:2.3.0@aar'
    compile 'se.emilsjolander:stickylistheaders:2.7.0'
    compile 'com.stepstone.stepper:material-stepper:3.3.0'
    compile 'jp.wasabeef:blurry:2.1.1'
    compile 'com.merhold.extensiblepageindicator:extensiblepageindicator:1.0.1'
    compile 'com.github.vihtarb:tooltip:0.1.9'


}

**Comment by WonderCsabo** [comment]
Are you sure there is no AA jar in the `libs` folder? Did you try a clean build?

**Comment by dderakhshani** [comment]
Oh you'r right, My mistake. I copied the api jar file to the libs folder and completely forgot it. Thanks a lot.
