### ISSUE TITLE
'Could not find the AndroidManifest.xml file' error using AA 4.4.0-SNAPSHOT and Android Gradle plugin 3.0.0-alpha7 with productFlavors

### ISSUE THREAD

**Issue by ahornerr** [androidannotations/androidannotations#2028]
Using the latest 4.4.0-SNAPSHOT version of AA with the latest Android Gradle alpha, locating the AndroidManifest.xml file fails when using product flavors.

I believe this issue may also be related to https://github.com/androidannotations/androidannotations/issues/2024

Taken from the example here: https://github.com/WonderCsabo/androidannotations/blob/2024_example/examples/gradle/build.gradle

Make the following changes:
#### Modified the Gradle Android plugin to **3.0.0-alpha7** and enable Kotlin/Kapt
```groovy
buildscript {
    dependencies {
        classpath "com.android.tools.build:gradle:3.0.0-alpha7"
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:1.1.0"
    }
}

apply plugin: "kotlin-android"
apply plugin: "kotlin-kapt"
```

#### Added a **flavorDimension** of `flavor` and **productFlavor** of `some_flavor`
```groovy
android {
    flavorDimensions "flavor"
    productFlavors {
        some_flavor {
            println "Defining the product flavor 'some_flavor'"
        }
    }
}
```

#### Modify AA dependency to use `kapt` instead of `annotationProcessor`
```groovy
dependencies {
    kapt "org.androidannotations:androidannotations:$AAVersion"
}
```

**Trying to compile the application with these changes throws an error, unable to locate AndroidManifest.xml in the generated folder.**

```
# ./gradlew assembleSome_flavorDebug

> Configure project :
Defining the product flavor 'some_flavor'

w: The '-d' option with a directory destination is ignored because '-module' is specified
e: error: Could not find the AndroidManifest.xml file, using  generation folder [androidannotations/examples/kotlin/build/generated/source/kapt/some_flavorDebug])
e:

e: androidannotations/examples/kotlin/src/main/kotlin/org/androidannotations/gradle/activity/HelloAndroidActivity.kt: (1, 1): Some error(s) occurred while processing annotations. Please see the error messages above.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':kaptSome_flavorDebugKotlin'.
> Compilation error. See log for more details

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED in 1s
13 actionable tasks: 1 executed, 12 up-to-date
```

[Link to full modified build.gradle](https://gist.github.com/ahornerr/3a82d3958a79621d520c4284392a3f17)

Checking the generated path that the error spits out, `androidannotations/examples/kotlin/build/generated/source/kapt/some_flavorDebug/` is empty. 

Up a level at `androidannotations/examples/kotlin/build/generated/source/kapt/` there is an `androidannotations.log` file with the following contents:

```
14:31:52.154 [RMI TCP Connection(51)-127.0.0.1] ERROR o.a.i.h.AndroidManifestFinder:147 - Could not find the AndroidManifest.xml file, using  generation folder [androidannotations/examples/kotlin/build/generated/source/kapt/some_flavorDebug])
```

Upon further research, I can see that the manifest is being generated to `androidannotations/examples/kotlin/build/intermediates/manifests/full/some_flavor/debug/AndroidManifest.xml` but it doesn't seem like AA is picking it up.

#### AndroidAnnotations version:
4.4.0-SHAPSHOT

#### Android compile SDK version:
25

**Comment by WonderCsabo** [comment]
Thanks for the detailed bug report! Is this happening if you do not use
kotlin? Where is the generated full manifest is at in your case?

**Comment by ahornerr** [comment]
It looks like the generated manifest is at `androidannotations/examples/kotlin/build/intermediates/manifests/full/some_flavor/debug/AndroidManifest.xml` but not in the `generated`folder.

I haven't tested without kotlin but I can tomorrow.

**Comment by ahornerr** [comment]
@WonderCsabo Swapping out `kapt` for `annotationProcessor`, disabling the `kotlin-apt` Gradle plugin, it appears to work.

It seems like kapt may be the issue here. I'm also getting a warning for both `kapt` and `annotationProcessor`:

```
warning: The following options were not recognized by any processor: '[resourcePackageName]'
```

**Comment by ahornerr** [comment]
It appears that the `resourcePackageName` annotation processor issue is related to the Android Gradle plugin, see: https://developer.android.com/studio/build/gradle-plugin-3-0-0-migration.html#variant_api

This breaks my current workflow because each of my application flavors have different application IDs.

**Comment by WonderCsabo** [comment]
The application ID may be different, but your resource package name should
be the same (this is the package where the R file is generated). In all my
projects I have the same Workflow as you. Moreover, I think the linked
change is not related to this.

**Comment by WonderCsabo** [comment]
Thanks for the details. Please ignore that warning, it is a false positive,
and was always displayed.

@dodgex I thought we fixed this for kapt. WDYT?

**Comment by dodgex** [comment]
@WonderCsabo yes, but @ahornerr states that the manifests are now generated in `build/intermediates/manifests/full/some_flavor/debug/AndroidManifest.xml` instead of `build/generated/source/[k]apt`. Maybe google changed the ouput directories once again.

We should investigate this, maybe we need to enhance/update the `GradleAndroidManifestFinderStrategy`. :/

**Comment by WonderCsabo** [comment]
I found what is the problem. We still have the `kapt` block which tries to set the manifest according to the `variant`. @ahornerr is right, this is not working anymore. However, we already find the manifest automatically, configuring the `androidManifestFile` in the `kapt` block is not necessary. I tried it, if you remove the `kapt` block, it will compile!

**Comment by dodgex** [comment]
Not sure what you mean with `kapt` block?

**Comment by WonderCsabo** [comment]
@dodgex eh, i missed the most important thing, the flavor. It is still not working.

**Comment by WonderCsabo** [comment]
Okay, i see what is the problem now... The Java annotation processor uses this generation folder in the end: `flavor/buildtype` . However `kapt` uses this generation folder : `flavorBuildtype`. This is pretty tricky, because we have to parse the variant name into the two parts in some way...

I will report this to the Kotlin guys, maybe way agree to change this directory to be in par with the Java one.

**Comment by WonderCsabo** [comment]
I created [this](https://youtrack.jetbrains.com/issue/KT-19245) issue. Let's see if they are willing to change this. If not, we have to come up with a workaround.

**Comment by dodgex** [comment]
I voted for the issue. :+1:

**Comment by ahornerr** [comment]
I was hoping it would be possible to hook into the Android Gradle variants API to fetch the generated manifest path but unfortunately it's the same broken API that is throwing the `resourcePackageName` error. We may need to wait for the Android build team to fix the variants API first.

**Comment by ahornerr** [comment]
I did a bit more testing, getting my project back to a stable state with an older version of the Android Gradle plugin. Using v2.3.1 and the following `kapt` configuration, I have AA v4.4.0-SNAPSHOT working.

```groovy
kapt {
    arguments {
        arg("androidManifestFile", variant.outputs[0].processResourcesTask.manifestFile)
        arg("resourcePackageName", android.defaultConfig.applicationId)
    }
}
```

Both of these arguments are necessary - without either of them the build will fail.

Knowing that these two arguments are necessary, and that the Android Gradle plugin variants API is broken, it makes sense why AA isn't working for me with the 3.0.0-alpha plugin.
