### ISSUE TITLE
Cannot be used without resources

### ISSUE THREAD

**Issue by tux-mind** [androidannotations/androidannotations#2032]
I have an android library without a `res` folder.
Thus I correctly don't have a R.class file, but android annotations does not like this.
I want to use this project for the `@Background` annotation, for now.

**AndroidAnnotations version**: 4.3.1

**Android compile SDK version**: 24

**Annotated log**:
```
14:36:22.452 [main] INFO  o.a.i.AndroidAnnotationProcessor:164 - AndroidManifest.xml found: AndroidManifest [applicationPackage=com.cleafy.mobile.helpers, componentQualifiedNames=[], metaDataQualifiedNames={}, permissionQualifiedNames=[], applicationClassName=, libraryProject=true, debugabble=false, minSdkVersion=9, maxSdkVersion=-1, targetSdkVersion=24]
14:36:22.454 [main] ERROR o.a.i.r.ProjectRClassFinder:47 - The generated com.cleafy.mobile.helpers.R class cannot be found
```

I can solve this by creating an `res/values/colors.xml` with a dummy color resource.

Thank you for your time and your contribution to the Android community :blush:

**Comment by WonderCsabo** [comment]
Unfortunately `R` is a base of our validations. I cannot really think we could support this. Please add a dummy resource.
