### ISSUE TITLE
Try Catch inside @Background function not working

### ISSUE THREAD

**Issue by ZulqurnainSDSOL** [androidannotations/androidannotations#2035]
Below example crash , it should not , and how can i fix this or is it bug

```
private String str = null;

@Background
void doSomething(){
  try{
    if(str.size()==0){ // here is crash
    }
  }catch(Exception e){e.printStackTrace();}
}
```

**Comment by WonderCsabo** [comment]
Sorry, this does not make sense.  Can you elaborate?

**Comment by BROUDING** [comment]
@ZulqurnainSDSOL 
You want to know size of Null...
Is it some kind of example?? ( I think it's not really a good example or mock-up to show )
Too many codes are omitted...

Maybe change `catch(Exception e)` to `catch(NullPointerException e)` ?
