### ISSUE TITLE
android studio 3.0 cann't get parent function

### ISSUE THREAD

**Issue by wei120698598** [androidannotations/androidannotations#2039]
`@EActivity
public abstract class BaseActivityAnnotation extends AppCompatActivity`

this is parent class.
if other class extends this class ， cann't get `getIntent()` 、 `setContentView()`...these function is red ，is error. but complete success.

**Comment by WonderCsabo** [comment]
Sorry, this issue is not related to AndroidAnnotations, your project is not correctly configured. Please check if the support library is added.
