### ISSUE TITLE
Imporve support for kotlin-allopen plugin

### ISSUE THREAD

**Issue by dodgex** [androidannotations/androidannotations#2040]
I just found that with 1.0.6 JetBrains released a kotlin compiler plugin "kotlin-allopen"  (see [1.0.6 release notes](https://blog.jetbrains.com/kotlin/2016/12/kotlin-1-0-6-is-here/) and [kotlin compiler plugin docs](https://kotlinlang.org/docs/reference/compiler-plugins.html)).

This plugin allows to mark classes with annotations and cause them to be `open` by default.

The idea is that we could document this feature in our kotlin sample (and maybe somewhere in the wiki?) and to better support this (remove the need to list all our annotations) we could provide a meta annotation that then has to be the only one listed in the plugin config.

e.g.
```java
@interface org.androidannotations.KotlinOpen {} // name not final :)

// and then
@KotlinOpen
@interface EActivity {}

// or
@KotlinOpen
@interface Background {}
```
the configuration in gradle is pretty straight forward
```
buildscript {
    dependencies {
        classpath "org.jetbrains.kotlin:kotlin-allopen:$kotlin_version"
    }
}
 
apply plugin: "kotlin-allopen"
 
allOpen {
    annotation("org.androidannotations.KotlinOpen")
}
```

@WonderCsabo what do you think?

**Comment by WonderCsabo** [comment]
@dodgex but this means we have to add `@KotlinOpen` to all of our annotations, right?

**Comment by dodgex** [comment]
Yes. Otherwise the user would need to add all annotations to the `allOpen {}` list

**Comment by WonderCsabo** [comment]
Will this work with our validations (we check if the method is not `final`)?

**Comment by dodgex** [comment]
I'm pretty sure it should. the plugin tells the kotlin compiler to not make the class final (as if the user would have used `open` on the class or method).

should be easy to test.

**Comment by WonderCsabo** [comment]
Okay, it is a nice enhancement, but definitely not on the top of the list right now. :)

**Comment by dodgex** [comment]
@WonderCsabo Any name suggestions for the annotation other than `org.androidannotations.KotlinOpen`? :D

**Comment by WonderCsabo** [comment]
I do not have a better idea. 🙂

**Comment by krokofant** [comment]
The kotlin example doesn't use this, right? Since the activity is not annotated with `@KotlinOpen` and it's set `open` instead.

**Comment by WonderCsabo** [comment]
It does use it. Not the activity but the bean.

https://github.com/androidannotations/androidannotations/blob/develop/examples/kotlin/src/main/kotlin/org/androidannotations/gradle/activity/HelloAndroidActivity.kt#L56

**Comment by dodgex** [comment]
@krokofant you do not have to use `@KotlinOpen` in your code by yourself. Our Annotations that need non final classes or methods. In case of the sample both [`@EActivity`](https://github.com/androidannotations/androidannotations/blob/develop/AndroidAnnotations/androidannotations-core/androidannotations-api/src/main/java/org/androidannotations/annotations/EActivity.java#L92) or [`@EBean`](https://github.com/androidannotations/androidannotations/blob/develop/AndroidAnnotations/androidannotations-core/androidannotations-api/src/main/java/org/androidannotations/annotations/EBean.java#L100) have the annotation and tell the compiler that the classes have to be `open`.  But we decided to keep the `open` keyword for the activity and instead add the bean class with a note about the `kotlin-allopen` plugin.

If you use the plugin in your project you do not need to provide the open keyword at all for our processor.

**Comment by krokofant** [comment]
I see, thanks for the clarification!

I also realised that I had to update to the Snapshot.

**Comment by WonderCsabo** [comment]
Indeed, this is not released yet, although i plan to release today. :)
