### ISSUE TITLE
About customized RestTemplate

### ISSUE THREAD

**Issue by han361769045** [androidannotations/androidannotations#2043]
If i want to use  customized RestTemplate，
I hope this:
@rest(rootUrl = BuildConfig.ROOT_URL,  restTemplate=CustomRestTemplate.class
public interface MyRestClient extends RestClientRootUrl, RestClientSupport, RestClientHeaders, RestClientErrorHandling {}

can auto create         **restTemplate = new CustomRestTemplate();**  ??
public MyRestClient_(Context context) {
        **restTemplate = new CustomRestTemplate();**
        availableCookies = new HashMap<String, _String>();
        availableHeaders = new HashMap<String, String>();
        rootUrl = "";
        restTemplate.getMessageConverters().clear();
        ............
    }

**Comment by WonderCsabo** [comment]
You can set your `RestTemplate` instance, this is explained in the javadoc.
```java
@RestService
MyRestClient myRestClient;

@AfterInject
void afterInject() {
  myRestClient.setRestTemplate(new CustomRestTemplate());
}
```

**Comment by han361769045** [comment]
if i  use this:
@RestService
MyRestClient myRestClient;

@AfterInject
void afterInject() {
  myRestClient.setRestTemplate(new CustomRestTemplate());
}
......
@Rest(rootUrl = BuildConfig.ROOT_URL, requestFactory = MyOkHttpClientHttpRequestFactory.class, interceptors = {MyInterceptor.class},
        converters = {StringHttpMessageConverter.class, MyGsonHttpMessageConverter.class, FormHttpMessageConverter.class, ByteArrayHttpMessageConverter.class, ResourceHttpMessageConverter.class},
        responseErrorHandler = MyResponseErrorHandlerBean.class)
these annotations  must be set ,too
