### ISSUE TITLE
Leak issue when using @Receiver

### ISSUE THREAD

**Issue by juanmendez** [androidannotations/androidannotations#2045]
Hi I am currently using AndroidAnnotations 4.3.1. I am using a fragment along with @Receiver. I noticed after rotating my device and doing a back-stack from that fragment I got this error:

Receiver not registered: info.juanmendez.myawareness.ui.HeadphoneFenceFragment_$1@59d4f5b

I was doing this before
`@Override
    public void onCreate(@Nullable Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setRetainInstance(true);
    }`

I stopped retaining the state, and that error was gone. I just wanted to let you know.

src: https://github.com/juanmendez/LearningAndroidAwareness/blob/master/app/src/main/java/info/juanmendez/myawareness/ui/HeadphoneFenceFragment.java#L128

**Comment by WonderCsabo** [comment]
In this case, you can use 

```java
@Receiver(actions = FENCE_INTENT_FILTER, registerAt = Receiver.RegisterAt.OnResumeOnPause)
```

In this case it should not leak even in this situation.
