### ISSUE TITLE
Revise documentaton for @Rest / Bundled interfaces

### ISSUE THREAD

**Issue by johnjohndoe** [androidannotations/androidannotations#2046]
I stumbled into the [documentation block](https://github.com/androidannotations/androidannotations/blob/androidannotations-4.3.1/AndroidAnnotations/androidannotations-rest-spring/rest-spring-api/src/main/java/org/androidannotations/rest/spring/annotations/Rest.java#L262-L264) for `Bundled interfaces` in Rest.java. The paragraph has a few typos - but is generally hard to understand. Since I do not understand the intention of the author I would like you to revise the paragraph.

**Comment by WonderCsabo** [comment]
I opened a PR to clarify that part. Is that understandable now?

**Comment by johnjohndoe** [comment]
Thank you.
