### ISSUE TITLE
onCheckIsTextEditor not called in custom View injected by @ViewById

### ISSUE THREAD

**Issue by mikh-o** [androidannotations/androidannotations#2047]
When injecting a custom view (extends `android.view.View`, not annotated by `@EView`) into an `@EFragment`, injected view's callback methods `onCheckIsTextEditor()` and `onCreateInputConnection(EditorInfo)` are not getting called

**AndroidAnnotations version**: 4.3.0, 4.3.1

**Android compile SDK version**: 25

**Injection**:
```java
@EFragment(R.layout.fragment_some)
public class SomeFragment {
...
    //View class itself is not annotated
    protected @ViewById(R.id.someView) SomeView someView;
...
}
```
**Expected**
`onCheckIsTextEditor()` and `onCreateInputConnection(EditorInfo)` are called

**Actual**
`onCheckIsTextEditor()` and `onCreateInputConnection(EditorInfo)` are not getting called

**Note**
If using `getView().findViewById(R.id.someView)` everything works ok

**How to reproduce**
- Create a custom view that overrides `onCheckIsTextEditor` and `onCreateInputConnection`
  That view should not be annotated by `@EView`
- Create a Fragment annotated by `@EFragment` and add your custom view into that fragment's layout
- Inject your custom view by using `@ViewById` annotation
- As stated above, methods in question are not getting called

**Comment by WonderCsabo** [comment]
Are you sure this view is properly set-up? AndroidAnnotations does not calls these methods, nor setups the view, it just injects it. Those callbacks are not related to AA in any way. Can you share an example project?

**Comment by WonderCsabo** [comment]
Closing due to lack of response.
