### ISSUE TITLE
IllegalStateException with AndroidAnnotations 4.1 and @EViewGroup / @OrmLiteDao

### ISSUE THREAD

**Issue by ytakahashi1981** [androidannotations/androidannotations#2048]
I have the same issue as #1887.
I updated #1887, but there is no response maybe due to issue status(closed).

I cannot upgrade AA to 4.x because of upgration cost with this issue...
(many many views are using OrmLiteDao annotations in my product...)

Maybe you can reproduce with these simple sources.
(My AA version is 4.3.1 but reproduced with 4.1)

TestDao.java
```TestDao.java
public class TestDao extends BaseDaoImpl<TestEntity, Integer> {
	protected TestDao(ConnectionSource connectionSource, Class<TestEntity> dataClass) throws SQLException {
		super(connectionSource, dataClass);
	}
}
```

TestEntity.java
```TestEntity.java
@DatabaseTable(tableName = "Test", daoClass = TestDao.class)
public class TestEntity {
}
```

TestView.java
```TestView.java

@EViewGroup
public class TestView extends FrameLayout {

	@OrmLiteDao(helper = DBHelper.class)
	TestDao testDao;

	public TestView(@NonNull Context context) {
		super(context);
	}

}
```

DBHelper.java
```DBHelper.java
public class DBHelper extends OrmLiteSqliteOpenHelper {
	public DBHelper(Context context) {
		super(context, "test.db", null, 1);
	}

	@Override
	public void onCreate(SQLiteDatabase database, ConnectionSource connectionSource) {}

	@Override
	public void onUpgrade(SQLiteDatabase database, ConnectionSource connectionSource, int oldVersion, int newVersion) {}
}
```

**Comment by TomWangTW** [comment]
Hi,
Have you try this?
For using OrmLiteDao, addd these new dependencies in your build.gradle:

compile "org.androidannotations:ormlite-api:4.0.0"
apt "org.androidannotations:ormlite:4.0.0"

Change your imports to
org.androidannotations.ormlite.annotations.OrmLiteDao

https://github.com/androidannotations/androidannotations/wiki/4.0.0-migration-guide

**Comment by ytakahashi1981** [comment]
@TomWangTW 
Hi. Thanks for reply.
These dependencies are already added.

I can use @OrmLiteDao with @EActivity, @EFragment, @EBean classes, but, can't use only with @EViewGroup due to IllegalStateException(like #1887, the error appears in compile time).

**Comment by ytakahashi1981** [comment]
I found what is wrong (maybe).

https://github.com/androidannotations/androidannotations/blob/1847f7083f0ce29747f12a496af9c0dffef183ea/AndroidAnnotations/androidannotations-ormlite/ormlite/src/main/java/org/androidannotations/ormlite/holder/OrmLiteHolder.java#L68-L75

This code seems to call below.

https://github.com/androidannotations/androidannotations/blob/1847f7083f0ce29747f12a496af9c0dffef183ea/AndroidAnnotations/androidannotations-core/androidannotations/src/main/java/org/androidannotations/holder/EViewHolder.java#L176-L179

https://github.com/androidannotations/androidannotations/blob/1847f7083f0ce29747f12a496af9c0dffef183ea/AndroidAnnotations/androidannotations-core/androidannotations/src/main/java/org/androidannotations/holder/ReceiverRegistrationDelegate.java#L97-L99

How can I avoid this?

(Sorry for my poor English...😢)

**Comment by WonderCsabo** [comment]
@dodgex i found what is the issue. 

```java
private void injectReleaseInOnDestroy(JFieldVar databaseHelperRef) {
		if (holder() instanceof HasLifecycleMethods) {
			JBlock destroyBody = ((HasLifecycleMethods) holder()).getOnDestroyBeforeSuperBlock();

			destroyBody.staticInvoke(getJClass(OrmLiteClasses.OPEN_HELPER_MANAGER), "releaseHelper");
			destroyBody.assign(databaseHelperRef, _null());
		}
	}
```


So `OrmLiteHolder` calls `getOnDestroyBeforeSuperBlock` because it needs to release the helper there. But `EViewHolder` simply delegates to `ReceiverRegistrationDelegate`, which always throws an exception.

I think there is a bad design here. `EView` should not extend `HasLifecycleMethods` in the first place. And for these kind of registrations, it should return onAttach/onDetach in separate delegates.

Another thing maybe: should we allow these kind of things in views at all? I am not so familiar with the onAttach/onDetach lifecycle, can we rely on it?

**Comment by dodgex** [comment]
> `EView` should not extend `HasLifecycleMethods` in the first place. 

I totally agree.

> Another thing maybe: should we allow these kind of things in views at all? I am not so familiar with the onAttach/onDetach lifecycle, can we rely on it?

Unfortunately i have no idea if we can rely on the onAttach/onDetach lifecycle. For convinience reasons I'd say we should keep support for these kind of things, but I'm not sure if it is worth the effort to ensure that those features work as expected, and even more important do not leak resources during runtime...

**Comment by dodgex** [comment]
regarding convinience: at least for this specific case of having database access directly in a view I'd say we could ignore the convinience aspect and say that there should be some kind of MVPish pattern that feeds the view with data.

**Comment by WonderCsabo** [comment]
It seems `View.onAttachedToWindow()` / `onDetachedFromWindow()` is reliable. It is called at `ViewGroup.addView()` / `removeView()` , and `onDetachedFromWindow()` is also called at `Activity.onDestroy()` if the view was not removed before.
