### ISSUE TITLE
Passing Value from Current Fragment to Previous Fragment

### ISSUE THREAD

**Issue by Zulqurnain** [androidannotations/androidannotations#2050]
I want to pass value from my current fragment to previous fragment , i have a general idea about how to pass it without android annotation. [from this SO](https://stackoverflow.com/a/40110415/8399299)

**AndroidAnnotations version**:4.3.1

**Android compile SDK version**:26

**Comment by WonderCsabo** [comment]
There is no special support for this in AA. You can use the same mechanism as in normal Android development.
