### ISSUE TITLE
Could java class and kotlin class use AA’s annoation in the same project?

### ISSUE THREAD

**Issue by cxc2014** [androidannotations/androidannotations#2054]
My project containers many Activity that use @EActivity, and now, I want to use kotlin to write my project, and keep use AA. Unfortunately, it looks like I can't use AA in java and kotlin in the same project, if I use

```
apply plugin: "kotlin-kapt"
kapt "org.androidannotations:androidannotations:$AAVersion"
```
can generate KotlinActivity_ , but can't generate JavaActivity_ .

if I use
```
annotationProcessor "org.androidannotations:androidannotations:$AAVersion"
```
can generate JavaActivity_, but can't generate KotlinActivity_ .

**Comment by darekdeo** [comment]
Using kapt works for me without issues for both Java and Kotlin classes.

Check this example
https://github.com/androidannotations/androidannotations/tree/develop/examples/kotlin

**Comment by WonderCsabo** [comment]
Yes, Kotlin is supported, check our example project.

**Comment by a4dangelo** [comment]
Not a useful comment at all. Clearly he knows Kotlin is supported. He meant can you use both Java and Kotlin in the same project and have AA work for both.
