### ISSUE TITLE
Generated files are unresolved

### ISSUE THREAD

**Issue by marcoEgger** [androidannotations/androidannotations#2057]
**AndroidAnnotations version**: 4.3.1
**Android compile SDK version**: 25

Using annotationProcessor and Android Studio 3.0 with 3.0.0 of android plugin.

The files are generated correctly and I can view them in Android Studio and everything is referenced correctly when viewing other files that are using the generated files. Still I can an error for every occurence with ```Unresolved reference: XXX_```

I'm using these compile options

```
javaCompileOptions {
    annotationProcessorOptions {
        arguments = ['resourcePackageName': android.defaultConfig.applicationId]
    }
}
```

**Comment by WonderCsabo** [comment]
Please share the whole project if possible.

**Comment by vickutetg** [comment]
I have the same problem
Error:(16, 18) error: cannot find symbol class XXX_

`apply plugin: 'com.android.application'
//apply plugin: 'android-apt'
//apply plugin: 'robolectric'
apply plugin: 'com.neenbedankt.android-apt'
apply plugin: 'me.tatarka.retrolambda'


def AAVersion = "4.3.1"
dependencies {
    annotationProcessor "org.androidannotations:androidannotations:$AAVersion"
    compile "org.androidannotations:androidannotations-api:$AAVersion"

    apt 'net.vvakame:jsonpullparser-apt:1.6.2'
    compile 'net.vvakame:jsonpullparser-core:1.6.2'

    annotationProcessor "org.androidannotations:roboguice:$AAVersion"
    compile "org.androidannotations:roboguice-api:$AAVersion"
    compile "org.roboguice:roboguice:3.0.1"

    compile 'com.android.support:support-v4:25.3.1'
    compile 'com.android.support:support-v13:25.3.1'
    compile "com.android.support:appcompat-v7:25.3.1"
    compile 'com.android.support:cardview-v7:25.3.1'
    compile 'com.google.android.gms:play-services-analytics:7.3.0'
    compile 'com.google.android.gms:play-services-maps:7.3.0'

    compile "com.wefika:flowlayout:0.3.+"
    compile 'com.etsy.android.grid:library:1.0.5'
    compile 'com.astuetz:pagerslidingtabstrip:1.0.1'
    compile "com.google.guava:guava:17.0"
    compile 'com.google.zxing:core:3.1.0'

    compile 'com.github.castorflex.smoothprogressbar:library:0.5.2'

    compile 'se.emilsjolander:stickylistheaders:+'

    compile 'com.mcxiaoke.volley:library:1.0.+'

    compile 'io.reactivex:rxandroid:0.25.0'

    compile project(':popinfo-sdk-res')

    compile fileTree(dir: 'libs', include: ['*.jar'])

//    androidTestCompile 'junit:junit:4.10'
//    androidTestCompile 'org.robolectric:robolectric:2.3+'
//    androidTestCompile 'com.squareup:fest-android:1.0.+'

//    compile 'com.android.support:support-v4:19.1.0'

    compile 'com.facebook.fresco:fresco:0.5.0+'

    compile 'com.android.support:recyclerview-v7:25.3.1'
}

android {
    compileSdkVersion 25
    buildToolsVersion "25.0.2"

    defaultConfig {
        minSdkVersion 15
        targetSdkVersion 19
        versionCode 16
        versionName "3.0.2"
        renderscriptSupportModeEnabled true
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    sourceSets {
        main {
        }
    }

    signingConfigs {
        own {
            keyAlias 'jp.co.loft'
            keyPassword 'pBiaK1A6'
            storeFile file('./keystore/loftapp.keystore')
            storePassword 'pBiaK1A6'
        }
    }

    buildTypes {
        debug {
            debuggable true
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.txt'
        }
        release {

            zipAlignEnabled true
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.txt'
            signingConfig signingConfigs.own
        }
    }

    productFlavors {
        dev {
            applicationId 'jp.co.loft.dev'
//            versionName "${android.defaultConfig.versionName}-dev"
        }
        staging {
            applicationId 'jp.co.loft.staging'
//            versionName "${android.defaultConfig.versionName}-staging"
        }
        product {
            applicationId 'jp.co.loft.fanapp'
        }
    }

    packagingOptions {
        exclude 'LICENSE.txt'
        exclude 'META-INF/LICENSE'
        exclude 'META-INF/LICENSE.txt'
        exclude 'META-INF/NOTICE'
    }

    lintOptions {
        abortOnError false
    }
}

//apt {
//    arguments {
//        androidManifestFile variant.outputs[0].processResources.manifestFile
//        resourcePackageName 'jp.co.loft'
//    }
//}
//
//configurations {
//    apt
//}

//robolectric {
//    // configure the set of classes for JUnit tests
//    include '**/*Test.class'
//    exclude '**/espresso/**/*.class'
//
//    // configure max heap size of the test JVM
//    maxHeapSize = "2048m"
//}

`


`// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    repositories {
        mavenCentral()
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:2.3.3'
        classpath 'com.neenbedankt.gradle.plugins:android-apt:1.8'
        classpath 'org.robolectric:robolectric-gradle-plugin:0.14.+'
        classpath 'me.tatarka:gradle-retrolambda:3.2.2'
    }
}

task assemble {
}

ext {
    compileSdkVersion = 25
    buildToolsVersion = "25.0.2"
}

allprojects { project ->
    afterEvaluate {
        if ((project.plugins.hasPlugin('android') || project.plugins.hasPlugin('android-library'))) {
            android {
                compileSdkVersion rootProject.ext.compileSdkVersion
                buildToolsVersion rootProject.ext.buildToolsVersion

                lintOptions {
                    abortOnError false
                }
            }
        }
    }
    repositories {
        jcenter()
        mavenCentral()
        mavenLocal()
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}`

**Comment by WonderCsabo** [comment]
You should not use `android-apt` anymore, it was superseded by the `annotationProcessor` configuration. 

You are definitely missing telling the resource package name to AA:

```groovy
android {
    compileSdkVersion 25
    buildToolsVersion "25.0.2"

    defaultConfig {
        minSdkVersion 9
        targetSdkVersion 25

        // this is the important part
        javaCompileOptions {
            annotationProcessorOptions {
                arguments = ["resourcePackageName": "jp.co.loft"]
            }
        }
    }
}
```

**Comment by WonderCsabo** [comment]
Closing due to lack of response. Please configure the project according to our wiki page.
