### ISSUE TITLE
Executing code before dependency injection

### ISSUE THREAD

**Issue by Aqua-Ye** [androidannotations/androidannotations#2058]
Hi,

Is there any way to call a particular code before dependency injection? `@BeforeInject` or something like that.

Thanks.

**Comment by Aqua-Ye** [comment]
If I look at the generated code, `super.onCreate` is called after `init_`

```
        OnViewChangedNotifier previousNotifier = OnViewChangedNotifier.replaceNotifier(onViewChangedNotifier_);
        init_(savedInstanceState);
        super.onCreate(savedInstanceState);
```

**Comment by WonderCsabo** [comment]
Sorry, you are right in this case. Why do you need this?

**Comment by Aqua-Ye** [comment]
I am using EventBus annotation:
```
    @EventBusGreenRobot
    EventBus bus;
```
Which get's bind during `init_` with `this.bus = EventBus.getDefault();`. 
But I need to configure it before the first call (see http://greenrobot.org/eventbus/documentation/configuration)

**Comment by WonderCsabo** [comment]
Where is that annotation coming from? How is it adding this to AA generated
method?

**Comment by Aqua-Ye** [comment]
Plugin listed here: https://github.com/androidannotations/androidannotations/wiki/List-of-AndroidAnnotations-plugins
Repo: https://github.com/tmtron/green-annotations

**Comment by WonderCsabo** [comment]
I checked the plugin, it is implemented as it should be.

You should configure the default instance in your `Application.onCreate()` method, it will run before any injections.

**Comment by Aqua-Ye** [comment]
I am also using the annotation in my Application. That is the problem.

**Comment by WonderCsabo** [comment]
Then you can use a static initializer block.
```java
@EApplication
public class MyApplication extends Application {

  static {
    // configure eventbus
  }

  // ...
}
`

**Comment by Aqua-Ye** [comment]
Right, didn't think about that 👍
