### ISSUE TITLE
gradle failed when upgrade to gradle 3.0 and Android Studio 3.0 release version

### ISSUE THREAD

**Issue by Anthonyeef** [androidannotations/androidannotations#2059]
This is a template, please adjust it accordingly to your specific issue.<br/>
You may also want to read our [issue guide](https://github.com/androidannotations/androidannotations/wiki/HowToWriteAnIssue).

**AndroidAnnotations version**:
4.3.1
**Android compile SDK version**:
26.0.2
**Annotated code**:
```java
kapt {
    arguments {
        arg("androidManifestFile", variant.outputs[0].processResourcesTask.manifestFile)
        arg("logLevel", "warn")
        arg("logAppenderConsole", true)
    }
}
```

**Expected generated code**:
gradle sync success.

**Actual generated code**:
gradle sync failed.

**Stacktrace in case of AA crash**:
Could not get unknown property 'processResourcesTask' for ApkVariantOutputImpl_Decorated{apkData=Main{type=MAIN, fullName=debug, filters=[]}} of type com.android.build.gradle.internal.api.ApkVariantOutputImpl.

**Comment by Anthonyeef** [comment]
I remember this line
> arg("androidManifestFile", variant.outputs[0].processResourcesTask.manifestFile)

was added because I am using Kotlin (kapt) and AndroidAnnotation at the same time. What should I do with this argument now, cause it seems deprecated when upgrade gradle plugin version to 3.0.0

**Comment by a-merkle** [comment]
In my case it works when you replace this line
`arg("androidManifestFile", variant.outputs[0]?.processResourcesTask?.manifestFile)`
with that
`arg("androidManifestFile", variant.outputs[0]?.processResources?.manifestFile)`
It seems as if `processResourcesTask` is now called `processResources`

**Comment by Anthonyeef** [comment]
thx @a-merkle . I will close this.
