### ISSUE TITLE
Build successful but nothing gets generated after updating Android Studio to 3.0

### ISSUE THREAD

**Issue by lukesterlee** [androidannotations/androidannotations#2060]
This is a template, please adjust it accordingly to your specific issue.<br/>
You may also want to read our [issue guide](https://github.com/androidannotations/androidannotations/wiki/HowToWriteAnIssue).

**AndroidAnnotations version**:
4.3.1

**Android compile SDK version**:
26 (buildToosVersion : 26.0.2)

**Annotated code**:
```java
dependencies {
    annotationProcessor "org.androidannotations:androidannotations:$annotationsVersion"
    implementation "org.androidannotations:androidannotations-api:$annotationsVersion"
}
```

**Expected generated code**:
gradle build successful and all the XXX_ classes generated

**Actual generated code**:
gradle build successful and nothing XXX_ classes got generated

**Stacktrace in case of AA crash**:
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
271 errors

 FAILED

FAILURE: Build failed with an exception.

**Comment by cooaer** [comment]
@lukesterlee I met the same question, and how do you solve it? Thanks!

**Comment by githubdoramon** [comment]
Same here

**Comment by WonderCsabo** [comment]
Can you share the project, or a sample project which reproduces the issue?

**Comment by githubdoramon** [comment]
ok... find the issue.... have forgot to add

 ```
 javaCompileOptions {
            annotationProcessorOptions {
                arguments = ["resourcePackageName": android.defaultConfig.applicationId]
            }
  }
```

inside defaultConfig in build.gradle

**Comment by wutq** [comment]
Who can tell me what to do with the following mistakes? 
Error:In <declare-styleable> FontFamilyFont, unable to find attribute android:font
Error:In <declare-styleable> FontFamilyFont, unable to find attribute android:fontWeight
Error:java.util.concurrent.ExecutionException: com.android.ide.common.process.ProcessException: Error while executing process D:\ProgramFiles\AndroidSdk\build-tools\26.0.2\aapt.exe with arguments {package -f --no-crunch -I D:\ProgramFiles\AndroidSdk\platforms\android-22\android.jar -M \\?\F:\AndroidProject\czwygjgc\app\build\intermediates\manifests\full\_360\debug\AndroidManifest.xml -S F:\AndroidProject\czwygjgc\app\build\intermediates\res\merged\_360\debug -m -J \\?\F:\AndroidProject\czwygjgc\app\build\generated\source\r\_360\debug -F F:\AndroidProject\czwygjgc\app\build\intermediates\res\_360\debug\resources-_360Debug.ap_ -D \\?\F:\AndroidProject\czwygjgc\app\build\intermediates\multi-dex\_360\debug\manifest_keep.txt --custom-package com.changzhou.czwygjgc -0 apk --output-text-symbols \\?\F:\AndroidProject\czwygjgc\app\build\intermediates\symbols\_360\debug --no-version-vectors}
Error:com.android.ide.common.process.ProcessException: Error while executing process D:\ProgramFiles\AndroidSdk\build-tools\26.0.2\aapt.exe with arguments {package -f --no-crunch -I D:\ProgramFiles\AndroidSdk\platforms\android-22\android.jar -M \\?\F:\AndroidProject\czwygjgc\app\build\intermediates\manifests\full\_360\debug\AndroidManifest.xml -S F:\AndroidProject\czwygjgc\app\build\intermediates\res\merged\_360\debug -m -J \\?\F:\AndroidProject\czwygjgc\app\build\generated\source\r\_360\debug -F F:\AndroidProject\czwygjgc\app\build\intermediates\res\_360\debug\resources-_360Debug.ap_ -D \\?\F:\AndroidProject\czwygjgc\app\build\intermediates\multi-dex\_360\debug\manifest_keep.txt --custom-package com.changzhou.czwygjgc -0 apk --output-text-symbols \\?\F:\AndroidProject\czwygjgc\app\build\intermediates\symbols\_360\debug --no-version-vectors}
Error:org.gradle.process.internal.ExecException: Process 'command 'D:\ProgramFiles\AndroidSdk\build-tools\26.0.2\aapt.exe'' finished with non-zero exit value 1
Error:Execution failed for task ':app:process_360DebugResources'.
> Failed to execute aapt

 After I delete the apt dependency ！！！

**Comment by bzn1120** [comment]
just restart




发自网易邮箱大师
On 12/14/2017 09:20，wutq<notifications@github.com> wrote：

Who can tell me what to do with the following mistakes?
Error:In FontFamilyFont, unable to find attribute android:font
Error:In FontFamilyFont, unable to find attribute android:fontWeight
Error:java.util.concurrent.ExecutionException: com.android.ide.common.process.ProcessException: Error while executing process D:\ProgramFiles\AndroidSdk\build-tools\26.0.2\aapt.exe with arguments {package -f --no-crunch -I D:\ProgramFiles\AndroidSdk\platforms\android-22\android.jar -M \?\F:\AndroidProject\czwygjgc\app\build\intermediates\manifests\full_360\debug\AndroidManifest.xml -S F:\AndroidProject\czwygjgc\app\build\intermediates\res\merged_360\debug -m -J \?\F:\AndroidProject\czwygjgc\app\build\generated\source\r_360\debug -F F:\AndroidProject\czwygjgc\app\build\intermediates\res_360\debug\resources-360Debug.ap -D \?\F:\AndroidProject\czwygjgc\app\build\intermediates\multi-dex_360\debug\manifest_keep.txt --custom-package com.changzhou.czwygjgc -0 apk --output-text-symbols \?\F:\AndroidProject\czwygjgc\app\build\intermediates\symbols_360\debug --no-version-vectors}
Error:com.android.ide.common.process.ProcessException: Error while executing process D:\ProgramFiles\AndroidSdk\build-tools\26.0.2\aapt.exe with arguments {package -f --no-crunch -I D:\ProgramFiles\AndroidSdk\platforms\android-22\android.jar -M \?\F:\AndroidProject\czwygjgc\app\build\intermediates\manifests\full_360\debug\AndroidManifest.xml -S F:\AndroidProject\czwygjgc\app\build\intermediates\res\merged_360\debug -m -J \?\F:\AndroidProject\czwygjgc\app\build\generated\source\r_360\debug -F F:\AndroidProject\czwygjgc\app\build\intermediates\res_360\debug\resources-360Debug.ap -D \?\F:\AndroidProject\czwygjgc\app\build\intermediates\multi-dex_360\debug\manifest_keep.txt --custom-package com.changzhou.czwygjgc -0 apk --output-text-symbols \?\F:\AndroidProject\czwygjgc\app\build\intermediates\symbols_360\debug --no-version-vectors}
Error:org.gradle.process.internal.ExecException: Process 'command 'D:\ProgramFiles\AndroidSdk\build-tools\26.0.2\aapt.exe'' finished with non-zero exit value 1
Error:Execution failed for task ':app:process_360DebugResources'.

Failed to execute aapt

After I delete the apt dependency ！！！
