### ISSUE TITLE
Can't stop thread by BackgroundExecutor.cancelAll

### ISSUE THREAD

**Issue by zqr95518** [androidannotations/androidannotations#2078]
**AndroidAnnotations version**:4.4.0
**Android compile SDK version**:21-26
**Annotated code**:

    @SuppressWarnings("InfiniteLoopStatement")
    @Background(id = "stageTimeTick")
    void stageTimeTick() {
        while (true) {
            try {
               //do something here
                Thread.sleep(1000);
            } catch (InterruptedException e) {
                e.printStackTrace();
            }
        }
    }
    @Background
    public void stopStageTimeTick() {
        Log.e(TAG, "stopStageTimeTick");
        BackgroundExecutor.cancelAll("stageTimeTick", true);
    }

**Comment by zqr95518** [comment]
I use this as a timer every second. When I stop it and later start another, there will be 2 thread together.

**Comment by WonderCsabo** [comment]
@zqr95518 i think the problem here that you are using an infinite loop, and you catch the `InterruptedException` as well. The `cancelAll()` method should throw that exception, but you just catch it, and then sleep again, and again. You should add a `break` statement in the `catch` block.

**Comment by zqr95518** [comment]
Thanks, I will have a try.
