### ISSUE TITLE
AndroidAnnotation doesn't engage without APT

### ISSUE THREAD

**Issue by liuzhen2008** [androidannotations/androidannotations#2080]
Previous build.gradle.

```
buildscript {
    dependencies {
        classpath 'com.android.tools.build:gradle:2.3.3'
    }
}
apply plugin: 'android-apt'

apt {
    arguments {
        androidManifestFile variant.outputs[0]?.processResources?.manifestFile
        resourcePackageName android.defaultConfig.applicationId
    }
}

dependencies {
    apt "org.androidannotations:androidannotations:4.4.0"
    apt "org.androidannotations:ormlite:4.4.0"
    compile "org.androidannotations:androidannotations-api:4.4.0"
    compile "org.androidannotations:ormlite-api:4.4.0"
}
```

With APT. My project is able to build and run properly.

Now, I would like to upgrade the plugin tool. I notice that this is no longer working for me. AndroidAnnotation is not generating any class.

I can 100% assure that these were the only difference in my git.

What am I missing with the new dependencies? I couldn't find any instruction on what dependencies to write for tool 3.0.0

```
buildscript {
    dependencies {
        classpath 'com.android.tools.build:gradle:3.0.0'
    }
}
dependencies {
    annotationProcessor "org.androidannotations:androidannotations:4.4.0"
    annotationProcessor "org.androidannotations:ormlite:4.4.0"
    implementation "org.androidannotations:androidannotations-api:4.4.0"
    implementation "org.androidannotations:ormlite-api:4.4.0"
}
```

**Comment by WonderCsabo** [comment]
The `apt` block no longer works, you have to specify the `resourcePackageName` like explained in the [wiki](https://github.com/androidannotations/androidannotations/wiki/Building-Project-Gradle).

**Comment by liuzhen2008** [comment]
@WonderCsabo 
Thanks it works!
