### ISSUE TITLE
OttoIntegration not working with gradle 3.0

### ISSUE THREAD

**Issue by Tumanin** [androidannotations/androidannotations#2081]
After upgrade gradle to 3.0 the methods with annotation `@Subscribe` never fire.

**AndroidAnnotations version**: 4.4.0

**Android compile SDK version**: 25

**Comment by Tumanin** [comment]
here is the example project:

https://github.com/Tumanin/testAndroidAnnotations.git

**Comment by WonderCsabo** [comment]
You forgot to add the Otto plugin:

```groovy
annotationProcessor "org.androidannotations:otto:$AAVersion"
```

**Comment by Tumanin** [comment]
Thanks! I overlooked it, because it worked on the gradle 2.3 without including Otto AA plugin.

**Comment by WonderCsabo** [comment]
@Tumanin it should not have worked. Maybe you used AA < 4.0.

**Comment by Tumanin** [comment]
Yes, you're right. I used 2.something and switched to 4.4 with the gradle upgrade. Now I understand, how it works. Thanks!

**Comment by ricking007** [comment]
I am facing the same problem, how to solve?
gradle:3.4.0

app:
apply plugin: 'com.android.application'

def AAVersion = '4.4.0'
dependencies {
    annotationProcessor "org.androidannotations:androidannotations:$AAVersion"
    implementation "org.androidannotations:androidannotations-api:$AAVersion"
    annotationProcessor "org.androidannotations:otto:$AAVersion"
}

apply plugin: 'com.android.application'
allprojects {
    repositories {
        google()   //  <-- here
        jcenter()
    }
}
buildscript {
    repositories {
        mavenCentral()
        jcenter()
        google()
    }

}

android {
    compileSdkVersion 28
    buildToolsVersion '28.0.3'

    defaultConfig {
        applicationId "kcollector.com.br.kcgm"
        minSdkVersion 17
        targetSdkVersion 28
        versionCode 1
        versionName "1.0"

        javaCompileOptions {
            annotationProcessorOptions {
                includeCompileClasspath true
                arguments = ["resourcePackageName": android.defaultConfig.applicationId]
                //arguments = ['androidManifestFile': variant.outputs[0].processResources.manifestFile]
            }
        }
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }

    sourceSets { main { assets.srcDirs = ['src/main/assets', 'src/main/assets/'] } }
}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])

    //noinspection DuplicatePlatformClasses
    implementation 'org.apache.httpcomponents:httpclient:4.5.6'

    // https://mvnrepository.com/artifact/org.apache.james/apache-mime4j
    implementation group: 'org.apache.james', name: 'apache-mime4j', version: '0.6.1'

//    // https://mvnrepository.com/artifact/org.apache.httpcomponents/httpmime
    implementation group: 'org.apache.httpcomponents', name: 'httpmime', version: '4.5.6'
    //noinspection GradleCompatible
    implementation 'com.android.support:appcompat-v7:28.0.0'
    implementation 'com.android.support:design:28.0.0'

    implementation 'com.github.satyan:sugar:1.5'
    implementation 'com.squareup.picasso:picasso:2.71828'
    implementation 'commons-collections:commons-collections:3.0'
    implementation 'com.google.code.gson:gson:2.8.2'
    implementation 'com.journeyapps:zxing-android-embedded:3.6.0@aar'
    implementation 'com.google.zxing:core:3.3.2'
    implementation 'com.mixpanel.android:mixpanel-android:4.7.0'
    //noinspection GradleDynamicVersion
    implementation 'com.google.android.gms:play-services-base:8.4.0+'
    //noinspection GradleDynamicVersion,GradleCompatible
    implementation 'com.google.android.gms:play-services-gcm:8.4.0+'

    implementation 'org.jbundle.util.osgi.wrapped:org.jbundle.util.osgi.wrapped.org.apache.http.client:4.1.2'
    implementation 'net.sourceforge.jexcelapi:jxl:2.6'

    implementation 'com.parse.bolts:bolts-tasks:1.3.0'
    implementation 'com.parse.bolts:bolts-applinks:1.3.0'
    implementation 'com.android.support:support-annotations:28.0.0'
    implementation 'androidx.annotation:annotation:1.0.2'


}

error:
error: cannot find symbol class MainActivity_
