### ISSUE TITLE
Use generated classes in Kotlin tests

### ISSUE THREAD

**Issue by nenick** [androidannotations/androidannotations#2082]
**AndroidAnnotations version**: 4.4.0

**Android compile SDK version**: 25

**Annotated code**: Empty Activity with `@EActivity` annotation

**Actual generated code**: Looks correct, no issues here.

We want to use AndroidAnnotation generated classes in tests (unit/instrumentation) but since Kotlin 1.1.3 this does not work anymore. Tests implemented in Java instead of Kotlin work fine however.

**Easiest way to reproduce (unit test):** 
* Kotlin app project with AndroidAnnotations
* enhance an activity with annotation `@EActivity`
* write Kotlin unit test which creates an AndroidAnnotation generated activity instance (ExampleActivity_) and call `setContentView(null)`
  * expected is a stacktrace which contains information about AndroidAnnotation generated activity class
  * result is stacktrace with direct call to base class (skipping the generated one)

**Other way to reproduce (instrumentation test):**

This issue occurs also within Espresso tests. Espresso test references generated class, but it uses the base activity during runtime.

```java
@Rule
@JvmField
val mActivityRule = ActivityTestRule(MyActivity_::class.java)
```

```
java.lang.RuntimeException: Could not launch activity
at android.support.test.runner.MonitoringInstrumentation.startActivitySync(MonitoringInstrumentation.java:430)
at android.support.test.rule.ActivityTestRule.launchActivity(ActivityTestRule.java:332)
at android.support.test.rule.ActivityTestRule$ActivityStatement.evaluate(ActivityTestRule.java:431)
at org.junit.rules.RunRules.evaluate(RunRules.java:20)
...
at android.support.test.internal.runner.TestExecutor.execute(TestExecutor.java:58)
at android.support.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:375)
at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:1932)
Caused by: java.lang.RuntimeException: Unable to resolve activity for: Intent { act=android.intent.action.MAIN flg=0x10000000 cmp=com.company.myapp/.ui.MyActivity }
at android.app.Instrumentation.startActivitySync(Instrumentation.java:396)
at android.support.test.runner.MonitoringInstrumentation.access$101(MonitoringInstrumentation.java:96)
at android.support.test.runner.MonitoringInstrumentation$4.call(MonitoringInstrumentation.java:410)
at android.support.test.runner.MonitoringInstrumentation$4.call(MonitoringInstrumentation.java:407)
at java.util.concurrent.FutureTask.run(FutureTask.java:237)
...
```

**Already tried:**
* use different Kotlin versions
  * with all Kotlin 1.1.2-* versions its works fine, with 1.1.3 this issue occurs
  * with Kotlin 1.1.51 the issue still exists
* tools like dbflow looks working (possible not comparable)

**Comment by WonderCsabo** [comment]
I am afraid this is out of of the processors reach, we cannot really do anything about this. But you can share the example project so we can take a look.

**Comment by nenick** [comment]
Here is an example project which shows the issue https://github.com/nenick/android-kotlin-androidannotations

There are also other libraries included where I can access the generated classes in Kotlin based tests without any issue. Also the Java based tests work without any issue.

Really strange behaviour I hope you have an idea.

**Comment by WonderCsabo** [comment]
@nenick i checked your project, it is really strange... For some reason `MainActivity_::class` returns the Kotlin class for `MainActivity`. But this is only happening in the instrumented test, not in the app. It is also happening in the unit test. You should report this error in the upstream project (i am not sure which), because we cannot do anything from AA-side. :(

**Comment by nenick** [comment]
@WonderCsabo do you know why all classes generated by AndroidAnnotations have the `@Metadata(...)` annotation? When i remove this annotation from generated classes then tests work fine.

**Comment by bohsen** [comment]
Could this issue be related to the Kotlin compiler generating classes with the Kt suffix added to the classname for top-level functions? If a kotlin file contains top-level functions (functions outside a class) the compilation will result in the creation of a java class that has its name constructed from the file name and the Kt suffix. Top level functions are compiled into static methods inside this class. 
For example, let's suppose that we define a top-level function within the Printer.kt file:

``` 
    // Printer.kt 
    fun printTwo() { 
        print(2) 
    }
```

The generated bytecode will be analogical to the code generated from the following Java class:

```
    //Java 
    public final class PrinterKt { 
        public static void printTwo() { 
            System.out.print(2);
        } 
    } 
```

Btw. This behavior can be changed using the @file:JvmName("Printer")  annotation or @file:JvmMultifileClass .

**Comment by nenick** [comment]
I found temporal acceptable workaround 

    afterEvaluate {
        kaptDebugKotlin.doLast {
            ant.replaceregexp(match:'(}, d2 = \\{\\n    "L)(.*);",', replace:'\\1\\2_;",') {
                fileset(dir: 'build/generated/source/kapt/debug')
            }
        }
    }

**Comment by saschak42** [comment]
Same issue here. @nenick your workaround is working, thank you! When will there be an official fix for that?

**Comment by adammach** [comment]
Where in structure of gradle should I put this "fix"? Thanks.

**Comment by saschak42** [comment]
You can put it simply at the end of the build.gradle file.

**Comment by adammach** [comment]
@saschak42  thanks for response. I've tried it, but I'm getting 'Could not get unknown property 'kaptDebugKotlin' for project ':mobile' of type org.gradle.api.Project '.

**Comment by dodgex** [comment]
I have opened a ticket in kotlin issue tracker: https://youtrack.jetbrains.com/issue/KT-27571 

please vote for it and hope they'll fix this soon :)

**Comment by dodgex** [comment]
I just got feedback and it seems that after all this is an issue within android annotations as we copy annotations from the enhanced class and those include the `kotlin.Metadata`.

I'll prepare a PR to fix this.

**Comment by WonderCsabo** [comment]
Finally fixed, thanks @dodgex!
