### ISSUE TITLE
@Click at EBean don't work

### ISSUE THREAD

**Issue by intmainreturn00** [androidannotations/androidannotations#2083]
Hello to everyone, 
**AndroidAnnotations version = 1.3**:

I have this code:
```java
@UseEventBus
@EActivity(R.layout.activity_main)
public class MainActivity extends AppCompatActivity {
	
    @ViewById(R.id.play)
    Button playButton;

    @Click(R.id.play)
    public void play() { /* works well */ }

}
```

it works as expected and generates expected handler for click event. I thought I can extract some logic into sub-bean from activity, since I can use [view related annotation](https://github.com/androidannotations/androidannotations/wiki/Enhance-custom-classes#view-related-annotations). So I tried this:
```java
@UseEventBus
@EActivity(R.layout.activity_main)
public class MainActivity extends AppCompatActivity {
    @Bean
    PlayerController playerController;
}

@EBean
public class PlayerController {

    @ViewById(R.id.play)
    Button playButton;

    @Click(R.id.play)
    public void play() { /* don't called */ }

    @AfterViews
    void test() {
        // playButton is accessible and not null here
    }

}
```
So some view-related annotation works as expected in activity child bean (view binding propagation works), but why does click event don't generate any code at all and therefore click events don't works? Does there is any way I can do such controllers in activity sub-beans? 

Thanks in advance,

**Comment by WonderCsabo** [comment]
Can you post the generated code?
