### ISSUE TITLE
HttpClientErrorException 400 Bad Request

### ISSUE THREAD

**Issue by marcbiaggini** [androidannotations/androidannotations#2084]
I have been experiment some troubles with REST client when I have to send body params, I've tried with diferents types using @Body annotation even with JSONObject class, but I've not had success can you tell me please what I'm doing wrong? . By the way when I'm doing a CURL directly in my swagger it works but in my Android client it always returns HttpClientErrorException code 400 Bad Request. 

**AndroidAnnotations 4.3.1**:

**Rest Swagger Setup**:
```

| Parameters    | Value              | Description           | Parameter Type | Data Type               |
|---------------|--------------------|-----------------------|----------------|-------------------------|
| authorization | Bearer <token>     | Guest Token           | header         | string                  |
| x-channel     | android            | Accepts: android, ios | header         | string                  |
| CpfModel      | { "cpf": "string"} | --                    | body           | CpfModel {cpf (string)} |

Parameter content type: application/json

```

**CURL**:
```
curl -X POST --header 'Content-Type: application/json' --header 'Accept: application/json' --header 'authorization: Bearer   token' --header 'x-channel: android' -d '{ \ 
   "cpf": "xxxxxxxxxx" \ 
 }' 'BaseUrl'
```

**Rest Interface**:
```java
@NonFinal
@Rest(rootUrl = BuildConfig.DEV_API_URL, converters = {GsonHttpMessageConverter.class,StringHttpMessageConverter.class,MappingJackson2HttpMessageConverter.class, FormHttpMessageConverter.class})
@RequiresHeader("x-channel")
public interface ServiceInterface extends RestClientErrorHandling {
...
  @Post("user/cpfCheck")
  @Headers(@Header(name ="Content-Type", value="application/json"))
  @RequiresHeader("authorization")
  String usedCPf(@Body Map<String,String> CpfModel);
...

} 
```

**Service Client Call**:
```java

...
@Background
    public void usedCpf(){
        Map<String, String> CpfModel = new HashMap<>();
        CpfModel.put("cpf", "15924798712");
        getResponse(ApiServices.getServiceInterface().usedCPf(CpfModel));
    }
...

```

**Stacktrace**
```
org.springframework.web.client.HttpClientErrorException: 400 Bad Request
```
**THANKS!**

**Comment by dodgex** [comment]
From your code samples i can't see where you set the `x-channel` and `authorization` headers.

You should either expand your `@Headers(@Header(name ="Content-Type", value="application/json"))` to provide the missing values as extra `@Header` as shown in the [javadoc of `@Headers`](https://github.com/androidannotations/androidannotations/blob/develop/AndroidAnnotations/androidannotations-rest-spring/rest-spring-api/src/main/java/org/androidannotations/rest/spring/annotations/Headers.java) or have a look at the [javadoc of `@RequiresHeader`](https://github.com/androidannotations/androidannotations/blob/develop/AndroidAnnotations/androidannotations-rest-spring/rest-spring-api/src/main/java/org/androidannotations/rest/spring/annotations/RequiresHeader.java) where is explained how to set the headers to be used with this annotation.

**Comment by marcbiaggini** [comment]
@dodgex I'm not pretty sure about it I did that already, I didn't posted the entire code cuz I think that the proble is with the type object on the body. but I will show the entire code in order to be 100% sure that is not problems with headers. 

In my class **ControllerServiceBeen** I´ve setup every header and I've tried every type object in method **usedCpf()** without success. 

In the main activity first I called the method **getUserGuest()** from the **ControllerServiceBeen** instance in order to set all headers and the BearerAuth token, after that I call the method **usedCpf()** but it seems that it doesn't work.

**Rest Interface**
```java
@NonFinal
@Rest(rootUrl = BuildConfig.DEV_API_URL, converters = {GsonHttpMessageConverter.class,StringHttpMessageConverter.class,MappingJackson2HttpMessageConverter.class, FormHttpMessageConverter.class})
@RequiresHeader("x-channel")
public interface ServiceInterface extends RestClientErrorHandling {
...
  @Post("user/guest")
  @Headers(@Header(name ="Content-Type", value="application/json"))
  AuthenticationResponse getUserGuest();

  @Post("user/cpfCheck")
  @Headers(@Header(name ="Content-Type", value="application/json"))
  @RequiresHeader("authorization")
  String usedCPf(@Body Map<String,String> CpfModel);

  void setBearerAuth(String token);

  void setHeader(String name, String value);
  String getHeader(String name);
}
``` 
**Rest Bean Controller**
```java

@EBean
public class ControllerServiceBeen {

    @RootContext
    Activity activity;

    ServiceCallback mlistener;

    private String token;

    @AfterInject
    protected void init(){
        mlistener = (MainActivity)activity;
    }

   @Background
    public void getUserGuest(){
        ApiServices.getServiceInterface().setHeader("x-channel", "android");
        setAthenticationToken(ApiServices.getServiceInterface().getUserGuest());
    }

    @UiThread
    protected void setAthenticationToken(AuthenticationResponse authentication){
        token = authentication.getToken();
        ApiServices.getServiceInterface().setBearerAuth(token);
        ApiServices.getServiceInterface().setHeader("authorization",(token));
    }

    @Background
    public void usedCpf(){
//        MultiValueMap<String, String> CpfModel = new LinkedMultiValueMap<String, String>();
//        CpfModel.add("cpf", String.valueOf("15924798712"));
//        JSONObject CpfModel = new JSONObject();
//        try {
//            CpfModel.put("cpf", String.valueOf("15924798712"));
//        } catch (JSONException e) {
//            e.printStackTrace();
//        }
//        CpfModel CpfModel = new CpfModel();
//        CpfModel.cpf=String.valueOf("15924798712");
        Map<String, String> CpfModel = new HashMap<>();
        CpfModel.put("cpf", "15924798712");
        getResponse(ApiServices.getServiceInterface().usedCPf(CpfModel));
    }

   @UiThread
    protected void getResponse(Object response){
        mlistener.getResponse(response);
    }
}
```

Tks!

**Comment by dodgex** [comment]
Could you post the generated code for `ServiceInterface`? This should help to see what actually happens in your App.

I'll try my best to help although in my projects I'm not using spring rest for many years now. :)

**Comment by dodgex** [comment]
Btw the generated class should be `ServiceInterface_`.

**Comment by brick8** [comment]
I was faced with the same problem and the problem is that `@Headers(@Header(name ="Content-Type", value="application/json"))` generate in `RestClient_` this code 

`HttpHeaders httpHeaders = new HttpHeaders();`
`httpHeaders.set("Content-Type", "application/json");`

According to 
In [javadoc of spring](https://docs.spring.io/spring-android/docs/2.0.0.M3/reference/html/rest-template.html#d5e395) says 
`HttpHeaders requestHeaders = new HttpHeaders();`
`requestHeaders.setContentType(new MediaType("application","json"));`

I would be very grateful if you will tell me how to add `setContentType(new MediaType("application","json"));` in Header.
Sorry for my bad english, i hope you anderstend me.

**Comment by dodgex** [comment]
Sorry for the delayed response.

The implementation of `setContentType` looks like this:

```
	public void setContentType(MediaType mediaType) {
		Assert.isTrue(!mediaType.isWildcardType(), "'Content-Type' cannot contain wildcard type '*'");
		Assert.isTrue(!mediaType.isWildcardSubtype(), "'Content-Type' cannot contain wildcard subtype '*'");
		set(CONTENT_TYPE, mediaType.toString());
	}
```

therefore the `httpHeaders.set("Content-Type", "application/json");` should do well.


Unfortunately I'm not using the spring rest api on my android apps. personally I'd either suggest to to try retrofit or maybe

**Comment by WonderCsabo** [comment]
I do not have any ideas unfortunetaly. @marcbiaggini have you found any solution to this?
