### ISSUE TITLE
Annotation doesn't generate for flavors with a customized sourceSets

### ISSUE THREAD

**Issue by liuzhen2008** [androidannotations/androidannotations#2085]
I have a flavor that uses sourceSets for some code reuse.

Originally I had main -> flavorA thats already setup with androidannotation and everything builds and works. I just wanted to add a subFlavorA with sourceSets customized.

```
    sourceSets {
        muuseUser {
            java.srcDirs = ['src/flavorA/java', 'src/subFlavorA/java']
        }
    }
```

i notice that as soon as I add an extra 'src/flavorA/java' to the srcDirs. My build will fail with a bunch of androidannotation errors. Without it, my simple subFlavorA works properly.

So I suppose this is not something that androidannotation support? But is there anything I can do to make it work regardless?

Thanks

**Comment by dodgex** [comment]
> I have a flavor that uses sourceSets for some code reuse.
for shared code you should add a library project to your build

But can you provide a small sample project to reproduce this error? Then we can investigate the problem and see if we can fix it, or if it is an issue wiht AndroidAnnotations at all.

**Comment by WonderCsabo** [comment]
@liuzhen2008 do you still see this problem. You can add more source directories, that is not a problem for AA.
