### ISSUE TITLE
Extra ArrayList<T> is injected with null value using Parceler

### ISSUE THREAD

**Issue by kot331107** [androidannotations/androidannotations#2086]
Hi! I've just written a very simple project to reproduce issue I've faced with and shrink redunant things.

**AndroidAnnotations version**: 4.4.0

**Android compile SDK version**: 26

**Annotated code**: 
   ```java
 @Extra
    ArrayList<Tour> tours; //**Tour** - is a simple POJO annotated with the @Parcel. 
```

```java
Main2Activity_.intent(this).tours(tours).start(); // starting the 2nd activity and filling the Extra-annotated arraylist (here tours is not null)
```

**Expected generated code in Main2Activity_.java**:
```java
 @SuppressWarnings("unchecked")
    private void injectExtras_() {
        Bundle extras_ = getIntent().getExtras();
        if (extras_!= null) {
            if (extras_.containsKey(TOURS_EXTRA)) {
                //due to johncarl81/parceler docs it should be something like this I suppose
                this.tours = (ArrayList<Tour> )Parcels.unwrap(extras_.getParcelable(TOURS_EXTRA));
            }
        }
    }
```

**Actual generated code in Main2Activity_.java**:
```java
 @SuppressWarnings("unchecked")
    private void injectExtras_() {
        Bundle extras_ = getIntent().getExtras();
        if (extras_!= null) {
            if (extras_.containsKey(TOURS_EXTRA)) {
                this.tours = ((ArrayList<Tour> ) extras_.getSerializable(TOURS_EXTRA));
            }
        }
    }
```

Am I right that Parceled ArrayLists<> should be supported by the **Extra** annotation and injected as well?

**Comment by kot331107** [comment]
BTW I've faced with another issue. JTIY if we write something like this
```java
    @InstanceState
    ArrayList<Tour> tours; // tour is the same POJO annotated with @Parcel
```
we'll get the following exception immediately when we trying to stop an Activity (for instance pressing Home button)

> java.lang.RuntimeException: Parcel: unable to marshal value

Should I write it to a different issue?

**Comment by WonderCsabo** [comment]
You should try
```java
@Extra
List<Tour> tours;
```

**Comment by kot331107** [comment]
@WonderCsabo Yeah you are definitely right! Sorry, this post https://stackoverflow.com/a/29691052/5109951 has taken me the wrong way...
