### ISSUE TITLE
How to use EFragment with class extends FragmentPagerAdapter?

### ISSUE THREAD

**Issue by zqr95518** [androidannotations/androidannotations#2091]
**AndroidAnnotations version**:
4.4.0
**Android compile SDK version**:
21-27
How to use EFragment with class extends FragmentPagerAdapter?
Should I use EBean to inject EFragment into the adapter?

**Comment by zqr95518** [comment]
Now I use new FragmentName_() to add Fragment.

**Comment by WonderCsabo** [comment]
You can use `@EBean` to inject the adapter into the `Fragment`, but there is no annotation for the other way, to inject the `Fragment` into the adapter. You have to create a setter on the adapter manually for that, and call in `Fragment` `@AfterInject` annotated method.
