### ISSUE TITLE
Error: cannot find symbol class MainActivity_ with gradle build 3.0.1

### ISSUE THREAD

**Issue by Gnanaoly** [androidannotations/androidannotations#2093]
The android annotation not generating the code.  I have tried for various method.  The compilation time there is no error but code not generated.  When I run that time only it was showing the error.

**def AAVersion = '4.4.0'**:
    annotationProcessor "org.androidannotations:androidannotations:$AAVersion"
    api "org.androidannotations:androidannotations-api:$AAVersion"

** compileSdkVersion 27
    buildToolsVersion '27.0.2'**:

 sourceSets {
        main {
            manifest.srcFile 'src/main/AndroidManifest.xml'
            assets.srcDirs = ['assets']
        }

        androidTest.setRoot('tests')
    }
    flavorDimensions "default"

    buildTypes.debug {
        minifyEnabled false
        shrinkResources false
        proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
    }
    buildTypes.release {
        minifyEnabled true
        shrinkResources true
        proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
    }

   compileOptions {
        encoding "UTF-8"
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

error: cannot find symbol
import com.client.activities.home.WaitForDriverActivity_;

distributionUrl=https\://services.gradle.org/distributions/gradle-4.1-all.zip
                                         ^

**Comment by crystalzhaoluoyang** [comment]
i got the same error

**Comment by nttgithubntt** [comment]
you reference https://github.com/androidannotations/androidannotations/issues/2079

**Comment by latrevisani** [comment]
I was having the same issue. And searching for similar issues, I faced:
https://stackoverflow.com/questions/36685423/android-annotation-upgrade-to-4-0-0-build-error
So I replaced all my:
@Extra List<T>
by:
@Extra ArrayList<T>
And all those cannot find symbol _ errors were gone.

**Comment by WonderCsabo** [comment]
Please try with the latest version, but AA works well with all Gradle plugins.
