### ISSUE TITLE
How to use Androidannotations @Trace with a static method

### ISSUE THREAD

**Issue by harminderkharbanda** [androidannotations/androidannotations#2094]
**AndroidAnnotations version: 4.4.0**:

**Android compile SDK version: 26**:

I am using androidannotations **@Trace** to measure the execution time of methods. It's working as expected in case of non static methods, but incase I use it with a static method, it gives compilation error.

> Error:(36, 20) error: isFirstInstall(Context) in Utils_ cannot override isFirstInstall(Context) in Utils overridden method is static

```
@EBean
public class Utils { 
. 
.
.     
@Trace     
public static boolean isFirstInstall(Context context) {         
.         
.         
.    
} 
}
```

androidannotations generates corresponding class Utils_ where it tries to override isFirstInstall(Context) which leads to compilation error.
Is there any workaround to use @Trace with static methods?

**Comment by dodgex** [comment]
No. Our annotations can't work with static methods as it is not possible to overwrite static methods in Java

**Comment by harminderkharbanda** [comment]
Okay thanks!
