### ISSUE TITLE
update from 4.3.1 to 4.4.0

### ISSUE THREAD

**Issue by karimi12** [androidannotations/androidannotations#2095]
i have problem when update from 4.3.1 to 4.4.0
i dont have any problem with AndroidAnnotations 4.3.1
**AndroidAnnotations version**:
4.4.0
**Android compile SDK version**:
26

**Error message**:
Error:Execution failed for task ':app:compileDebugJavaWithJavac'.
> java.lang.NoSuchFieldError: LONG

**Comment by WonderCsabo** [comment]
Did you try with the latest version?
