### ISSUE TITLE
Abstract Activity with @EActivity ignored.

### ISSUE THREAD

**Issue by ZamBunny** [androidannotations/androidannotations#2096]
Hi

Abstract activities seems to be ignored by AA. Non-abstract activities are generated just fine.

I understand this must be a choice made by the dev team, but shouldn't it be documented somewhere ?

Thanks!

**AndroidAnnotations version**:
4.4.0
**Android compile SDK version**:
27
**Annotated code**:
```java
@EActivity(R.layout.activity_question)
public abstract class QuestionActivity extends AppCompatActivity {

	/* ... */

}
```
**Manifest**:
```xml
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="ca.csf.mobile2.tp2">

    <application
        android:allowBackup="true"
        android:icon="@mipmap/ic_launcher"
        android:label="@string/app_name"
        android:roundIcon="@mipmap/ic_launcher_round"
        android:supportsRtl="true"
        android:theme="@style/AppTheme">

        <activity
            android:name=".question.QuestionActivity_"
            android:label="@string/title_activity_question"
            android:theme="@style/AppTheme.NoActionBar">
            <intent-filter>
                <action android:name="android.intent.action.MAIN" />

                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>
        </activity>

    </application>

</manifest>
```
**Generated code after clean and build**
![image](https://user-images.githubusercontent.com/8997953/34227080-e79ef5c0-e599-11e7-8562-34bb24ebf36f.png)
**Generated code if activity is not abstract**
![image](https://user-images.githubusercontent.com/8997953/34227208-58ab086c-e59a-11e7-8547-4ad5b7042fda.png)

**Comment by dodgex** [comment]
What should we do with `abstract` methods in your abstract class? Also why would you make an activity abstract and then use the (not) generated class in the manifest? You should not use abstract for those activities. abstract activities should be used as "base" acitivty for other activites that then get code generated (including code for the abstract class)

**Comment by ZamBunny** [comment]
Makes a lot of sense. Completly forgot about that.

**Comment by dodgex** [comment]
No Problem. I Think i can Close this then
