### ISSUE TITLE
Start background Service for Build.VERSION.SDK_INT == Build.VERSION_CODES.O

### ISSUE THREAD

**Issue by BKMExpress** [androidannotations/androidannotations#2098]
Hi Guys,

According to Background Execution Limits on Android Oreo we should call the method  startForegroundService(new Intent(context, Service.class));  Will you provide any methods for this?

**AndroidAnnotations version**:4.4.0

**Android compile SDK version**:27

**Stacktrace in case of AA crash**:
java.lang.IllegalStateException: Not allowed to start service Intent { cmp=com.bkm.mobil/.service.Service_ }: app is in background uid UidRecord{3f9a458 u0a25 CEM  idle procs:1 seq(0,0,0)}

Thank you!

**Comment by BKMExpress** [comment]
Any comments ?

**Comment by tajchert** [comment]
This is a quite big issue for me, any ideas for nice workarounds or plans on supporting startForegroundService()?

**Comment by tajchert** [comment]
Workaround set `targetSdkVersion` to API 26 instead of 27.

**Comment by WonderCsabo** [comment]
Can you write a more detailed feature request?

**Comment by hiperioncn** [comment]
I met the same issue. Maybe you can visit this site for more information: https://stackoverflow.com/questions/46445265/android-8-0-java-lang-illegalstateexception-not-allowed-to-start-service-inten

**Comment by WonderCsabo** [comment]
The workaround is creating the `Intent` using the builder and call `startForegroundService()` manually:
```java
Intent intent = MyService_.intent(context).get()
context.startForegroundService(intent);
```

We could add `startForegroundService()` to `ServiceIntentBuilder`, but it was only added in API 26, which we cannot depend on with the current Maven setup. But i think the workaround above is more than acceptable.
