### ISSUE TITLE
@Extra equivalent for Fragments

### ISSUE THREAD

**Issue by pyricau** [androidannotations/androidannotations#210]
Based on #3 :

We should add the equivalent to `@Extra` with fragment arguments.
- It would inject the fragment arguments in fragment fields
- It would automatically add a builder method with those arguments in the generated subclass.

**Comment by joaoeduardo** [comment]
How to use?

**Comment by WonderCsabo** [comment]
Please check the wiki for the `@FragmentArg` annotation, we have detailed documentation.
