### ISSUE TITLE
cannot run app when using realm and androidannotations

### ISSUE THREAD

**Issue by haemi** [androidannotations/androidannotations#2100]
**AndroidAnnotations version**:
4.4.0

**Android compile SDK version**:
27

**Stacktrace in case of AA crash**:
Error:Error converting bytecode to dex:
Cause: com.android.dex.DexException: Multiple dex files define Lnet/jcip/annotations/Immutable;
Error:com.android.dex.DexException: Multiple dex files define Lnet/jcip/annotations/Immutable;
Error:	at com.android.dx.merge.DexMerger.readSortableTypes(DexMerger.java:661)
Error:	at com.android.dx.merge.DexMerger.getSortedTypes(DexMerger.java:616)
Error:	at com.android.dx.merge.DexMerger.mergeClassDefs(DexMerger.java:598)
Error:	at com.android.dx.merge.DexMerger.mergeDexes(DexMerger.java:171)
Error:	at com.android.dx.merge.DexMerger.merge(DexMerger.java:198)
Error:	at com.android.builder.dexing.DexArchiveMergerCallable.call(DexArchiveMergerCallable.java:61)
Error:	at com.android.builder.dexing.DexArchiveMergerCallable.call(DexArchiveMergerCallable.java:36)
Error:	at java.util.concurrent.ForkJoinTask$AdaptedCallable.exec(ForkJoinTask.java:1424)
Error:	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
Error:	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
Error:	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
Error:	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
Error:Execution failed for task ':app:transformDexArchiveWithDexMergerForDebug'.
> com.android.build.api.transform.TransformException: com.android.dex.DexException: Multiple dex files define Lnet/jcip/annotations/Immutable;

I added realm to my project and now I get the error from above; am I missing something or is this a known issue?

**Comment by dodgex** [comment]
It looks like the issue is not related to AndroidAnnotations. It seems that mutliple dependencies provide the `net/jcip/annotations/Immutable` class

you should check your dependencies tree if you maybe need to exclude a certain dependency to avoid the duplicated class.

**Comment by haemi** [comment]
I can't even get androidannotations up and running in a fresh project; added the two lines

```
compile 'org.androidannotations:androidannotations:4.4.0'
annotationProcessor 'org.androidannotations:androidannotations:4.4.0'
```

to build.gradle-dependencies gives me the following error:

```
Error:Execution failed for task ':app:transformDexArchiveWithExternalLibsDexMergerForDebug'.
> com.android.builder.dexing.DexArchiveMergerException: Unable to merge dex
```

**Comment by earendilSK** [comment]
@haemi please try 

`implementation "org.androidannotations:androidannotations-api:4.4.0"`

instead of

`implementation "org.androidannotations:androidannotations:4.4.0"`

it worked for me
