### ISSUE TITLE
Error:(34, 14) error: Activity_ is not abstract and does not override abstract method findViewById(int) in HasViews

### ISSUE THREAD

**Issue by Rohitsachdeva** [androidannotations/androidannotations#2101]
Just add this line in gradle and then this error came.

    compile 'com.stripe:stripe-android:6.1.0'

issue : Error:(34, 14) error: Activity_ is not abstract and does not override abstract method findViewById(int) in HasViews

**AndroidAnnotations version**:4.0

**Android compile SDK version**:26

**Comment by MarcosJava** [comment]
Have you already fixed ??
Because I have the same problem :/

**Comment by MarcosJava** [comment]
I solved ... 
I putted on version 4.4.0 , and It have the method findViewById(int) in HasViews

> buildscript {
>     repositories {
>         mavenCentral()
>         jcenter()
>         google()
> 
>         maven {
>             url 'https://maven.fabric.io/public'
>         }
>     }
>     dependencies {
>         classpath 'com.neenbedankt.gradle.plugins:android-apt:1.8'
>         classpath 'io.fabric.tools:gradle:1.+'
>         classpath 'com.android.tools.build:gradle:3.0.1'
> 
>     }
> }
> 
> repositories {
>     mavenCentral()
>     mavenLocal()
>     maven { url 'https://dl.bintray.com/drummer-aidan/maven' }
>     maven { url 'https://maven.fabric.io/public' }
>     maven { url "https://jitpack.io" }
>     maven { url "https://oss.sonatype.org/content/repositories/snapshots" }
> }
> 
> apply plugin: 'com.android.application'
> apply plugin: 'com.google.gms.google-services'
> apply plugin: 'io.fabric'
> apply plugin: 'jacoco'
> def AAVersion = '4.4.0'
> def compileSkdVersion = '27'
> 
> 
> android {
>     compileSdkVersion 27
>     buildToolsVersion '27.0.2'
> 
>     defaultConfig {
>         applicationId "br.com.xx.xx"
>         minSdkVersion 14
>         targetSdkVersion 21
>         versionCode Integer.parseInt(VERSION_CODE)
>         versionName VERSION_NAME
>         testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
>         javaCompileOptions {
>             annotationProcessorOptions {
>                 arguments = ["resourcePackageName": android.defaultConfig.applicationId]
>             }
>         }
> 
>         //resConfigs "pt", "en", "pt_BR"
>         //resConfigs "nodpi", "hdpi", "xhdpi", "xxhdpi", "xxxhdpi"
>     }
>     signingConfigs {//Its secret
>     }
> 
>     buildTypes {//Its secret
>     }
> 
>     flavorDimensions "app"
>     productFlavors { //Its secret    }
> 
>     packagingOptions {
>         exclude 'META-INF/LICENSE.txt'
>         exclude 'META-INF/NOTICE.txt'
>         exclude 'LICENSE.txt'
>     }
> 
>     lintOptions {
>         quiet true
>         abortOnError false
>         ignore 'InvalidPackage'
>     }
> 
> }
> 
> android.applicationVariants.all { variant ->
>     variant.variantData.variantConfiguration.javaCompileOptions.annotationProcessorOptions.arguments =
>             ['androidManifestFile': variant.outputs[0]?.processResources?.manifestFile,
>              'resourcePackageName': android.defaultConfig.applicationId]
> }
> 
> repositories {
>     maven { url 'https://maven.google.com' }
> }
> 
> dependencies {
> 
>     compile fileTree(dir: 'libs', include: ['*.jar'])
>     androidTestCompile('com.android.support.test.espresso:espresso-core:2.2.2', {
>         exclude group: 'com.android.support', module: 'support-annotations'
>     })
> 
>     //Apt
>     annotationProcessor "org.androidannotations:androidannotations:$AAVersion"
>     compile "org.androidannotations:androidannotations-api:$AAVersion"
> 
> 
>     // Google libraries
> //    compile 'com.android.support:appcompat-v7:27.0.2'
> //    compile 'com.android.support:animated-vector-drawable:27.0.2'
> //    compile 'com.android.support:support-v4:27.0.2'
> //    compile 'com.android.support:support-compat:27.0.2'
> 
>     compile 'com.android.support:appcompat-v7:27.0.2'
>     compile 'com.android.support:support-v4:27.+'
>     compile 'com.android.support:recyclerview-v7:27.+'
>     compile 'com.android.support:cardview-v7:27.+'
>     compile 'com.android.support:support-v13:27.+'
>     compile 'com.android.support:design:27.+'
> 
>     compile 'com.android.support:recyclerview-v7:+'
>     compile 'com.android.support:cardview-v7:+'
>     compile 'com.android.support:support-v13:+'
>     compile 'com.android.support:design:+'
> 
>     compile 'com.google.android.gms:play-services-analytics:11.4.2'
>     compile 'com.google.firebase:firebase-messaging:11.4.2'
>     //compile 'com.firebase:firebase-jobdispatcher:0.8.5'
> 
> 
> 
>     //Report
>     compile('com.crashlytics.sdk.android:crashlytics:2.3.2@aar') {
>         transitive = true;
>     }
>     //Log
>     compile 'com.jakewharton.timber:timber:3.1.0'
>     //Rest
>     //TODO: o código fonte do retrofit está no projeto, pois está com erro no retorno 401 da versão 1.9.0.
>     //a versão 2.0.x ainda está em beta e teve muitas mudanças incluindo nome de classes e namespaces
>     //compile 'com.squareup.retrofit2:retrofit:2.0.0-beta3'
>     //compile 'com.squareup.retrofit2:retrofit:2.0.0-beta4'
>     compile 'com.squareup.retrofit:retrofit:1.9.0'
>     compile 'com.squareup.okhttp:okhttp:2.5.0'
>     compile 'com.google.code.gson:gson:2.8.2'
>     //View
>     compile 'com.squareup.picasso:picasso:2.5.2'
>     compile 'com.squareup:otto:1.3.5'
>     compile 'com.rengwuxian.materialedittext:library:2.1.4'
>     compile 'com.afollestad.material-dialogs:core:0.9.4.4'
>     compile 'com.pkmmte.view:circularimageview:1.1'
>     compile 'com.github.PhilJay:MPAndroidChart:v2.1.3'
> 
> 
>     //Test
>     testCompile 'junit:junit:4.12'
>     testCompile 'org.assertj:assertj-core:1.7.0'
>     testCompile 'org.mockito:mockito-core:1.+'
>     testCompile 'com.squareup.okhttp:mockwebserver:2.5.0'
>     testCompile('org.robolectric:robolectric:3.0') {
>         exclude group: 'commons-logging', module: 'commons-logging'
>         exclude group: 'org.apache.httpcomponents', module: 'httpclient'
>     }
> }
> 
> assemble.dependsOn('jacocoReport')
> 
> //Jacoco
> jacoco {
>     toolVersion = "0.7.1.201405082137"
> }
> 
> task jacocoReport(type: JacocoReport, dependsOn: 'testVisaoHomologUnitTest') {
>     def coverageSourceDirs = [
>             '../app/src/main/java'
>     ]
> 
>     group = "Reporting"
>     description = "Generate Jacoco coverage reports"
> 
>     classDirectories = fileTree(
>             dir: '../app/build/intermediates/classes/visao/homolog',
>             excludes: ['**/R.class', '**/R$*.class',
>                        '**/*$ViewInjector*.*', '**/BuildConfig.*', '**/Manifest*.*']
>     )
> 
>     additionalSourceDirs = files(coverageSourceDirs)
>     sourceDirectories = files(coverageSourceDirs)
>     executionData = files('../app/build/jacoco/testVisaoHomologUnitTest.exec')
> 
>     reports {
>         xml.enabled = true
>         html.enabled = true
>     }
> }

**Comment by WonderCsabo** [comment]
Yes, this was fixed.
