### ISSUE TITLE
BindingObject can only be used on an element that extends ViewDataBinding

### ISSUE THREAD

**Issue by rehovicova** [androidannotations/androidannotations#2102]
For some reason AA says 

> BindingObject can only be used on an element that extends ViewDataBinding

even when I'm using BindingObject with class that extends ViewDataBinding

**AndroidAnnotations version**: 4.4.0
**Android compile SDK version**: 26
**Kotlin version**: 1.2.10

**Gradle**:
```java
apply plugin: 'com.android.application'
apply plugin: 'kotlin-android'
apply plugin: 'kotlin-android-extensions'
apply plugin: 'kotlin-kapt'
apply plugin: 'realm-android'


def AAVersion = '4.4.0'
def supportVersion = "26.1.0"

android {
    compileSdkVersion 26
    defaultConfig {
        applicationId "com.x.y"
        minSdkVersion 19
        targetSdkVersion 26
        versionCode 1
        versionName "1.0"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
    dataBinding {
        enabled = true
    }
}

dependencies {
}
```

**Annotated code**:
```java
@DataBound
@EFragment(R.layout.fragment_sign_in)
open class SignInFragment : BaseFragment() {

    @BindingObject
    lateinit var binding: FragmentSignInBinding

    ...

}
```

**FragmentSignInBinding**:
```java
public class FragmentSignInBinding extends android.databinding.ViewDataBinding {
    ...
}
```

**Stacktrace in case of AA crash**:

> Error:(8, 1) error: org.androidannotations.annotations.BindingObject can only be used on an element that extends android.databinding.ViewDataBinding

I was able to get rid of the message when I removed `dataBinding.enabled = true` from gradle. I made project clean today and I got the same error as yesterday. I made AA + databinding project before and I have never had this problem. The settings on both project seems the same. Any idea?

**Comment by rehovicova** [comment]
I commented every line with binding, cleaned it again, uncommented and built. It is working now, but I really dont want to do it every time I will have to clean the project.

**Comment by lymons** [comment]
I got the same problem. how do we fix it?

**Comment by Ung8023** [comment]
you can use this in your `app-level` `build.gradle`

```
kapt {
    correctErrorTypes = true
}
```

is seems that `AA` create a `xxx_.java`  before **dataBinding** create binding files

**Comment by WonderCsabo** [comment]
Good suggestion! I am adding this to our Kotlin guide.
