### ISSUE TITLE
Does androidannotations’ targetSdkVersion have to update to meet google play's new policy

### ISSUE THREAD

**Issue by george-world** [androidannotations/androidannotations#2103]
My app is using androidannotations framework, and have to update targetSdkVersion to newest api level to meet google play's new policy as below:
https://android-developers.googleblog.com/2017/12/improving-app-security-and-performance.html

My question is: 
Does androidannotations' targetSdkVersion also have to update?
If has to update, when it will be completed?

**Comment by dodgex** [comment]
Afaik we do not specify `targetSdkVersion` at any place other than the tests and examples (where we indeed should update the targetSdkVerion). so there should be no problem for you using android annotations.
