### ISSUE TITLE
AA with Kotlin: Can't use @FragmentArg with multiple nullable arguments.

### ISSUE THREAD

**Issue by ytakahashi1981** [androidannotations/androidannotations#2106]
**AndroidAnnotations version**:
4.4.0

**Android compile SDK version**:
27

**Kotlin version**:
1.2.10

**Gradle version**:
2.3.3

**Annotated code**:
In Fragment class: (annotated with `@EFragment`)
```kotlin
@set:FragmentArg
var argument1: String? = null
@set:FragmentArg
var argument2: String? = null
```

**Expected generated code**:
In XXFragment_.FragmentBuilder class:
```java
public XXFragment_.FragmentBuilder_ setArgument1(String argument1) {
  args.putString(ARGUMENT1_ARG, argument1);
}
public XXFragment_.FragmentBuilder_ setArgument2(String argument2) {
  args.putString(ARGUMENT2_ARG, argument2);
}
```

**Actual generated code**:
```java
public XXFragment_.FragmentBuilder_ setArgument1(String p0) {
  args.putString(P0_ARG, p0);
}
public XXFragment_.FragmentBuilder_ setArgument2(String p0) {
  args.putString(P0_ARG, p0);
}
```

Then, I got the same value from `argument1` and `argument2`.
Is there any way to use `@FragmentArg` with nullable String?

**Comment by Ung8023** [comment]
you can try this
```java
@FragmentArg
@JvmField final var aStr: String? = null
```

**Comment by ytakahashi1981** [comment]
The solution solved my problem.
Thanks @ung8023 !
