### ISSUE TITLE
Could not find the AndroidManifest.xml file, going up from path [/Users/apple/AndroidStudioProjects/MyApplication6/app/build/generated/source/apt/debug] found using dummy file [] (max atempts: 

### ISSUE THREAD

**Issue by xiehanchao** [androidannotations/androidannotations#2107]
I run my project.
I get these error.
how do I fix it?
__________________________________________________________________________________________________________
Error:注: Resolve log file to /Users/apple/AndroidStudioProjects/MyApplication6/app/build/generated/source/apt/androidannotations.log
注: Initialize AndroidAnnotations 3.2 with options {}
注: Start processing for 9 annotations on 28 elements
错误: Could not find the AndroidManifest.xml file, going up from path [/Users/apple/AndroidStudioProjects/MyApplication6/app/build/generated/source/apt/debug] found using dummy file [] (max atempts: file:///Users/apple/AndroidStudioProjects/MyApplication6/app/build/generated/source/apt/debug/dummy1517026875715)
注: Time measurements: [Whole Processing = 50 ms], [Extract Annotations = 45 ms], [Extract Manifest = 2 ms], 
注: Finish processing
注: Start processing for 0 annotations on 0 elements
注: Time measurements: [Whole Processing = 1 ms], 
注: Finish processing
1 个错误
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --debug option to get more log output.

* Get more help at https://help.gradle.org

BUILD FAILED in 5s
__________________________________________________________________________________________________________
apply plugin: 'com.android.application'
def AAVersion = '3.2'
android {
    compileSdkVersion 26
    defaultConfig {
        javaCompileOptions { annotationProcessorOptions { includeCompileClasspath = true } }
        applicationId "com.example.apple.myapplication"
        minSdkVersion 15
        targetSdkVersion 26
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
    buildToolsVersion '26.0.2'
}
dependencies {
    compile 'com.danikula:videocache:2.7.0'
    compile 'com.nostra13.universalimageloader:universal-image-loader:1.9.3'
    implementation fileTree(include: ['*.jar'], dir: 'libs')
    implementation 'com.android.support:appcompat-v7:26.1.0'
    implementation 'com.android.support.constraint:constraint-layout:1.0.2'
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'com.android.support.test:runner:1.0.1'
    androidTestImplementation 'com.android.support.test.espresso:espresso-core:3.0.1'

    annotationProcessor "org.androidannotations:androidannotations:${AAVersion}"
    compile "org.androidannotations:androidannotations-api:${AAVersion}"

    compile 'com.github.JakeWharton:ViewPagerIndicator:2.4.1'
    implementation project(':library')
}
__________________________________________________________________________________________________________
// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    
    repositories {
        google()
        jcenter()

    }
    dependencies {
        classpath 'com.android.tools.build:gradle:3.0.0'
    }
}

allprojects {
    repositories {
        google()
        jcenter()
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}

Thank!!!!

**Comment by lsanotes** [comment]
Try to run the official example:
https://github.com/androidannotations/androidannotations/tree/develop/examples/gradle
if it works well, then you know what to do next ^_

**Comment by khalil2535** [comment]
i have the same problem here

**Comment by naderz** [comment]
Having the same issue too

**Comment by trr-amsiq** [comment]
Try AA version 4.5.0

**Comment by dodgex** [comment]
Better try 4.5.1 as it fixes a bug related to Android X components.
