### ISSUE TITLE
How to download this jar? for eclipse

### ISSUE THREAD

**Issue by s593198145** [androidannotations/androidannotations#2108]
i can`t find the url for androidannotatons.jar. who can help me?

**Comment by dodgex** [comment]
You can find the jars here: https://mvnrepository.com/artifact/org.androidannotations/androidannotations

**Comment by s593198145** [comment]
think you very much！




------------------ 原始邮件 ------------------
发件人: "Kay-Uwe Janssen";<notifications@github.com>;
发送时间: 2018年2月2日(星期五) 下午3:32
收件人: "androidannotations/androidannotations"<androidannotations@noreply.github.com>;
抄送: "指间的流年"<593198145@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [androidannotations/androidannotations] How to download this jar?for eclipse (#2108)




You can find the jars here: https://mvnrepository.com/artifact/org.androidannotations/androidannotations
