### ISSUE TITLE
@Extra requires lateinit in Kotlin

### ISSUE THREAD

**Issue by tajchert** [androidannotations/androidannotations#2110]
Using @Extra annotations with nullable such as:

```
@Extra
 var productId: String? = null
```

Results in:
```
Element productId invalidated by ExtraHandler
org.androidannotations.annotations.Extra cannot be used on a private element
```

Android Annotations forces you to use lateinit, such as:

```
@Extra
 lateinit var productId: String
```

Which is not a good solution as Extras can be null and having an easy way to check them would be a much better solution.

compileSdkVersion = 26
AndroidAnnotations version = 4.3.1
kotlin ver = 1.2.10

**Comment by rehovicova** [comment]
You can use

```
@JvmField
@Extra
var productId: String? = null
```

**Comment by tajchert** [comment]
I use kotlin-allopen and I would need to do as ([source](https://stackoverflow.com/questions/41457954/kotlin-allopen-plugin-jvmfield-on-a-val-not-final-enough)):

```
  @JvmField
  @Extra
  final val product: Product? = null
```
But then there is another problem with @Extra : 
`org.androidannotations.annotations.Extra cannot be used on a final element`

**Comment by tajchert** [comment]
I will consider/try removing kotlin-allopen, as we added it to avoid adding 'open' keyword for all AndroidAnnotations classes. However any other solutions are more than welcome.

**Comment by tajchert** [comment]
Ok, so removing kotlin-allopen solved issue and proposed solution work well.
Thanks :) :shipit:

**Comment by hiepxuan2008** [comment]
I meet the same issue, it shows error: `error: org.androidannotations.annotations.Extra cannot be used on a private element`

My code:
```kotlin
@Extra("mode")
var mode: Int = 0
```

I changed to like below, and it works well:
```kotlin
@JvmField
@Extra("mode")
final var mode: Int = 0
```

**Comment by hiepxuan2008** [comment]
> I use kotlin-allopen and I would need to do as ([source](https://stackoverflow.com/questions/41457954/kotlin-allopen-plugin-jvmfield-on-a-val-not-final-enough)):
> 
> ```
>   @JvmField
>   @Extra
>   final val product: Product? = null
> ```
> 
> But then there is another problem with @extra :
> `org.androidannotations.annotations.Extra cannot be used on a final element`

I did like you said, it shows the same error: `error: org.androidannotations.annotations.Extra cannot be used on a final element
    @org.androidannotations.annotations.Extra(value = "product")`

I changed it like below, and it works well
```kotlin
@JvmField
@Extra
final var product: Product? = null
```
