### ISSUE TITLE
[Feature Request] Support @Rest on an Abstract Class

### ISSUE THREAD

**Issue by alonalbert** [androidannotations/androidannotations#2113]
The Rest annotation only works on interfaces but could also work for abstract classes. This can be useful when the native API does not exactly fit the use case. [For example, consider a REST API that returns List of Sections but the use case calls for a Map keyed by a Section title](https://pastebin.com/AfdwMPXw).

**Comment by WonderCsabo** [comment]
Sorry, but we do not want to support abstract classes.
