### ISSUE TITLE
[Bug] ConstraintLayout in a RecyclerView Renders Wrong

### ISSUE THREAD

**Issue by alonalbert** [androidannotations/androidannotations#2114]
**AndroidAnnotations version**:
4.4.0
**Android compile SDK version**:
27

When a ConstraintLayout is used inside a RecyclerView using 
[AndroidAnnotations design pattern](https://github.com/androidannotations/androidannotations/wiki/Adapters-and-lists#recyclerview-and-viewholder),
 it doesn't render properly. [sample project here](https://github.com/alonalbert/recycler-view-bug)

![Without Annotations](https://raw.githubusercontent.com/alonalbert/recycler-view-bug/master/without-annotations.png)
![With Annotations](https://raw.githubusercontent.com/alonalbert/recycler-view-bug/master/with-annotations.png)

**Comment by alonalbert** [comment]
I was able to come up with a proposal that works properly.

Admittedly, it's a bit awkward because it requires the item layout to explicitly use the generated view class:

`<view class="com.example.al.recyclerviewbug.working_annotatated.WorkingAnnotatedRecyclerViewActivity_$ItemView_"`

And it also requires the view class to implement the View constructor `View(Context context, AttributeSet attrs)`

That said, it works properly. Hopefully, a better solution can be found.

Here's a link to my awkward proposal:
[Code](https://github.com/alonalbert/recycler-view-bug/tree/master/app/src/main/java/com/example/al/recyclerviewbug/working_annotatated)
[Layout](https://github.com/alonalbert/recycler-view-bug/blob/master/app/src/main/res/layout/item_working_annotated.xml)

**Comment by radixdiaboli** [comment]
There is no bug here.  [You're supposed to use the generated class in layout files.](https://github.com/androidannotations/androidannotations/wiki/Enhance-custom-views)
