### ISSUE TITLE
How can I use AA in my android module library project directly? Not in app module.

### ISSUE THREAD

**Issue by xudeheng** [androidannotations/androidannotations#2122]
As title mentioned.

**Comment by xudeheng** [comment]
In module project, it doesn't work.

```
@EActivity(R.layout.activity_some_test)
class SomeTestActivity
```

------------------------
Compile failed: Element must be constant.

**Comment by dodgex** [comment]
In lineares you have to use 

> resName="activity_some_test"


As the annotation Parameter.

**Comment by dodgex** [comment]
closing due to lack of response
