### ISSUE TITLE
Adding Kotlin file stops classes being generated

### ISSUE THREAD

**Issue by henriAtstk** [androidannotations/androidannotations#2123]
**AndroidAnnotations version**: AndroidAnnotations 4.4.0

**Android compile SDK version**: 27

This might be an easy one (or not), so the project is building and generating classes fine, and working alright, but as soon as I add one kotlin file automatically generated classes stop being generated.

The changes in gradle/settings files that I do when I add the kotlin file are simply the ones I have in other non-annotated projects: almost-automatic changes added by android studio 3.0.1

I remove the kotlin stuff and back working it is...

Any help would be much appreciated!

**Stacktrace in case of AA crash**

The part that looks more relevant:
```
 error: cannot find symbol
            intent = new Intent(hostContext, MainActivity_.class);
                                             ^
  symbol:   class MainActivity_
  location: class CareNotificationManager
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
95 errors
```

**Comment by dodgex** [comment]
I think you need to add `kapt "org.androidannotations:androidannotations:${androidAnnotationsVersion}"` to your build.

If this wont work feel free to reopen the issue.
