### ISSUE TITLE
Anko conflict

### ISSUE THREAD

**Issue by xinaiz** [androidannotations/androidannotations#2124]
**AndroidAnnotations version**:
4.4.0

**Android compile SDK version**:
15+

**Annotated code**:
```kotlin
@EActivity(R.layout.empty_activity)
class EmptyActvity : AppCompatActivity() {

    @ViewById
    lateinit var test: Button

    @AfterViews
    fun afterViews() {
        verticalLayout {} // Anko DSL layout
    }
}
```

**Stacktrace in case of AA crash**:

> 03-11 06:54:22.992 8353-8353/com.example.admin.aatest E/AndroidRuntime:     at org.jetbrains.anko.internals.AnkoInternals.addView(Internals.kt:48)
>                                                                             at org.jetbrains.anko.internals.AnkoInternals.addView(Internals.kt:57)
>                                                                             at com.example.admin.aatest.EmptyActvity.afterViews(EmptyActvity.kt:33)
>                                                                             at com.example.admin.aatest.EmptyActvity_.onViewChanged(EmptyActvity_.java:106)
>                                                                             at org.androidannotations.api.view.OnViewChangedNotifier.notifyViewChanged(OnViewChangedNotifier.java:41)
>                                                                             at com.example.admin.aatest.EmptyActvity_.setContentView(EmptyActvity_.java:88)
>                                                                             at org.jetbrains.anko.AnkoContextImpl.doAddView(AnkoContext.kt:112)
>                                                                             at org.jetbrains.anko.AnkoContextImpl.addView(AnkoContext.kt:106)
>                                                                             at org.jetbrains.anko.internals.AnkoInternals.addView(Internals.kt:48)
>                                                                             at org.jetbrains.anko.internals.AnkoInternals.addView(Internals.kt:57)
>                                                                             at com.example.admin.aatest.EmptyActvity.afterViews(EmptyActvity.kt:33)
>                                                                             at com.example.admin.aatest.EmptyActvity_.onViewChanged(EmptyActvity_.java:106)
>                                                                             at org.androidannotations.api.view.OnViewChangedNotifier.notifyViewChanged(OnViewChangedNotifier.java:41)
>                                                                             at com.example.admin.aatest.EmptyActvity_.setContentView(EmptyActvity_.java:88)
...

Exception is generated forever due to recursive `setContentView` calls.
Any solutions?

**Comment by dodgex** [comment]
You should be able to use a `UI {}` block to setup your ui and then you should be able to use the resulting view to set it to a container.

Instead of having an actual  empty layout `empty_activity` you have one (e.g.) `LinearLayout` in it (in this sample with the id `yourContainer`)

```
val ui = UI {
    verticalLayout {
        // your layout
    }
}
yourContainer.addView(ui.view)
```

but you cant use `@ViewById` for views generated in the anko dsl.
