### ISSUE TITLE
about after android studio 3.0  how can i  change my project gradle config 

### ISSUE THREAD

**Issue by YX-G** [androidannotations/androidannotations#2126]
annotationProcessorOptions  config is always error
issue: 
Could not find method arguments() for arguments [build_5ltduckauc0gpawmzuiglf2im$_run_closure1$_closure5$_closure11$_closure12$_closure13@3c22850f] on AnnotationProcessorOptions_Decorated{classNames=[], arguments={}, includeCompileClasspath=null} of type com.android.build.gradle.internal.dsl.AnnotationProcessorOptions. Open File

my code

//annotationProcessor {
//    arguments {
//        androidManifestFile variant.outputs[0].processResources.manifestFile
//        resourcePackageName 'xxxxxxxxxxxxxxx'
//    }
//}

**Comment by dodgex** [comment]
You should check the [sample project](https://github.com/androidannotations/androidannotations/blob/develop/examples/gradle/build.gradle#L34). 

if you still have issues we need more information. e.g the android build plugin version

**Comment by WonderCsabo** [comment]
You are using the wrong syntax. Please check the [example project](https://github.com/androidannotations/androidannotations/blob/develop/examples/gradle/build.gradle#L34) or the [get started](https://github.com/androidannotations/androidannotations/wiki/Building-Project-Gradle) page.
