### ISSUE TITLE
AS 3.2 Alpha - Could not find the AndroidManifest.xml file, using  generation folder

### ISSUE THREAD

**Issue by veresvit** [androidannotations/androidannotations#2128]
On Android Studio 3.2 Alpha 8 with according build gradle plugin and using build variants its not posible to build the app. When downgrade to stable Android Studio 3.1 and build gradle plugin 3.1.0 the build works fine.<br/>

**AndroidAnnotations version**: 4.4.0

**Android compile SDK version**: 27

**com.android.tools.build:gradle**: 3.2.0-alpha08

**build.gradle**:
```
apply plugin: 'com.android.application'
apply plugin: 'io.fabric'
apply plugin: 'realm-android'

android {
	compileSdkVersion 27
	defaultConfig {
		...
		compileOptions {
			sourceCompatibility JavaVersion.VERSION_1_8
			targetCompatibility JavaVersion.VERSION_1_8
		}
		javaCompileOptions {
			annotationProcessorOptions {
				// Needs to be same as package name and manifest package
				arguments = ['resourcePackageName': 'pack.age.name']
			}
		}
	}
	buildTypes {
		release {
			minifyEnabled false
			proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
		}
	}
	flavorDimensions "default"
	productFlavors {
		flavtest {
			buildConfigField "String", "ENDPOINT_URL", '"https://.../"'
			versionNameSuffix "-test"
		}
		preprod {
			buildConfigField "String", "ENDPOINT_URL", '"https://.../"'
			versionNameSuffix "-preprod"
		}
		production {
			buildConfigField "String", "ENDPOINT_URL", '"https://.../"'
		}
	}
	dependencies {
		...
		annotationProcessor "com.github.hotchemi:permissionsdispatcher-processor:3.1.0"
		// Permission dispatcher annotation
		annotationProcessor "com.github.AleksanderMielczarek:AndroidAnnotationsPermissionsDispatcherPlugin:2.1.1"
		// AA
		annotationProcessor "org.androidannotations:androidannotations:4.4.0"
		implementation "org.androidannotations:androidannotations-api:4.4.0"
		// Android Annotations for Greenrobot
		annotationProcessor "com.tmtron:green-annotations:1.0.2"
		implementation "com.tmtron:green-annotations-api:1.0.2"
	}
	apply plugin: 'com.google.gms.google-services'
}
```

**Stacktrace in case of AA crash**:
```
\app\build\generated\source\apt\flavtest\androidannotations.log

10:13:34.489 [Daemon worker Thread 11] ERROR o.a.i.h.AndroidManifestFinder:147 - Could not find the AndroidManifest.xml file, using  generation folder [C:\Users\username\Documents\_Projects\Appname\app\build\generated\source\apt\flavtest\debug])
```

**Comment by sandsaber** [comment]
+1 issue, noticed same thing.
Did try, no luck
` arg("androidManifestFile", variant.outputs[0].processResourcesTask.manifestFile)
        arg("resourcePackageName", android.defaultConfig.applicationId)`

**Comment by petacz** [comment]
+1

**Comment by PetrKrestaAi** [comment]
+1
Same event without variants

**Comment by zqr95518** [comment]
+1

**Comment by petacz** [comment]
Also with 3.2.0-alpha10 and 11

**Comment by zqr95518** [comment]
Oh well. It broke in AS 3.1.2 release with 3.1.1.

**Comment by zqr95518** [comment]
It seems if you not import or use the EActivity, they will generate correctly.

**Comment by carrymaster** [comment]
Also with 3.2.0-alpha16. Any solution without removing EActivity annotation?

**Comment by veresvit** [comment]
Managed to make it work before the issue is fixed by adding this to the module's build.gradle android.defaultConfig:

```
		javaCompileOptions {
			annotationProcessorOptions {
				arguments = [
						'androidManifestFile': 'app\\build\\intermediates\\merged_manifests\\debug\\processDebugManifest\\merged\\AndroidManifest.xml'
				]
			}
		}
```

This works on Windows with Android Studio - allows me to build the project and release a signed apk. Let me know if you figure out any better solution. On other OS the path might need to be adjusted.

**Comment by rajeshsubramanian** [comment]
Appreciate it @veresvit. This worked for me on macOS HS too.
```
"androidManifestFile": "app/build/intermediates/merged_manifests/debug/processDebugManifest/merged/AndroidManifest.xml"
```

**Comment by carrymaster** [comment]
Thanks @veresvit! This worked perfectly.

But with this solution, would we be using the debug manifest in release?

**Comment by dodgex** [comment]
I'm currently working on a fix for this one.

**Comment by dodgex** [comment]
PR is up and @WonderCsabo will review it asap I think. As soon as he has reviewed and merged the PR you can use the `4.5.0-SNAPSHOT` wihtout the `androidManifestFile` option

**Comment by petacz** [comment]
Link to PR #2147

**Comment by LouisCAD** [comment]
Here's my solution for a Kotlin project (using kapt), that works my multi-buildTypes project:

I define this method at the top of my build.gradle file:
```groovy
private static String manifestPath(String buildTypeName) {
    def slash = File.separator
    return "app${slash}" +
            "build${slash}" +
            "intermediates${slash}" +
            "merged_manifests${slash}" +
            "$buildTypeName${slash}" +
            "process${buildTypeName.capitalize()}Manifest${slash}" +
            "merged${slash}" +
            "AndroidManifest.xml"
}
```
Then, in each buildType closure, I add this:
```groovy
kapt { arguments { arg('androidManifestFile', manifestPath(name)) } }
```

**Comment by Namnodorel** [comment]
I tried using `4.5.0-SNAPSHOT`, the bug still persisted until I used the manifest argument. My manifest location is `app\build\intermediates\merged_manifests\debug\AndroidManifest.xml`

**Comment by BugsBunnyBR** [comment]
I just tried the 4.5.0-SNAPSHOT and it is not working for me.
I have debug and release buildTypes and qa,stage and prod flavors where I add a `applicationIdSuffix`.

I removed the kapt arguments block and ran the command:
`./gradle clean assembleStageRelease`

I get an error that says:
`e: error: The generated $MY_PACKAGE_STAGE_.R class cannot be found`

I did not test much, but it seems to be the same to other variants too.

**Comment by luanmm** [comment]
To avoid using a SNAPSHOT version in a production code (don't know when exactly anything will be done from the AA team), I ended up with this solution (based on tips from other developers). It works for Kotlin projects that use KAPT and consider flavors (this is my scenario).

Create a file with this script (to avoid putting a lot of [temporary] code in your `build.gradle`):

```groovy
import java.util.regex.Pattern
import java.util.regex.Matcher

def static getManifestPath(String buildType) {
    def slash = File.separator
    return "app${slash}" +
            "build${slash}" +
            "intermediates${slash}" +
            "merged_manifests${slash}" +
            "$buildType${slash}" +
            "process${buildType.capitalize()}Manifest${slash}" +
            "merged${slash}" +
            "AndroidManifest.xml"
}

def getCurrentBuildType() {
    Gradle gradle = getGradle()
    String taskReqStr = gradle.getStartParameter().getTaskRequests().toString()

    println taskReqStr

    Pattern pattern = Pattern.compile(":(assemble|generate)(\\w+)")
    Matcher matcher = pattern.matcher(taskReqStr)
    if (matcher.find()) {
        String flavor = matcher.group(2)
        if (flavor.contains("Sources")) {
            flavor = flavor.replace("Sources", "")
        }

        char[] c = flavor.toCharArray()
        c[0] = Character.toLowerCase(c[0])
        flavor = new String(c)

        println "getCurrentBuildType:" + flavor
        return flavor
    } else {
        println "getCurrentBuildType:cannot_find_current_build_type"
        return ""
    }
}

def currentBuildType = getCurrentBuildType()
if (!currentBuildType.isEmpty()) {
    def manifestPath = getManifestPath(currentBuildType)
    kapt { arguments { arg("androidManifestFile", manifestPath) } }
}
```

Then, in your `build.gradle` file, import this script:

```groovy
apply from: "$rootDir/<build_scripts_folder>/annotations.gradle"
```

Credits to:
- @LouisCAD 
- wonsuc ([from Stackoverflow](https://stackoverflow.com/a/46204711/5136165))

**Comment by dodgex** [comment]
AndroidAnnotations 4.5.0 just has been released and should be available on maven central soon !

**Comment by fededri** [comment]
> 
> 
> Managed to make it work before the issue is fixed by adding this to the module's build.gradle android.defaultConfig:
> 
> ```
> 		javaCompileOptions {
> 			annotationProcessorOptions {
> 				arguments = [
> 						'androidManifestFile': 'app\\build\\intermediates\\merged_manifests\\debug\\processDebugManifest\\merged\\AndroidManifest.xml'
> 				]
> 			}
> 		}
> ```
> 
> This works on Windows with Android Studio - allows me to build the project and release a signed apk. Let me know if you figure out any better solution. On other OS the path might need to be adjusted.

You saved me
