### ISSUE TITLE
Pending Intent problem Through Notification

### ISSUE THREAD

**Issue by Zulqurnain** [androidannotations/androidannotations#2130]
I am calling activity from Notification pending intent using `MyActivity_.intent(context).myVar(true).get()` but this myVar variable is only **true** when activity is closed and clicked on notification , but when activity is already opened **myVar** don't get updated

**AndroidAnnotations version**:4.4.0

**Android compile SDK version**:27

Sorry code is too long to post , but it is not wortking

**Comment by dodgex** [comment]
As mentioned [here (see the 4.0.0 related warning)](https://github.com/androidannotations/androidannotations/wiki/Extras#handling-onnewintent) we no longer override `onNewIntent` to call `setIntent`. You have to add that by youself if you need this behaviour.

```
    @Override
    protected void onNewIntent(Intent intent) {
        super.onNewIntent(intent);
        setIntent(intent);
    }
```
