### ISSUE TITLE
Is this project still maintained?

### ISSUE THREAD

**Issue by xinaiz** [androidannotations/androidannotations#2132]
The question is same as the title. I'm curious, because I don't see any responses to the issues from commiters basically since version 4.4.0 came up, meaning 4-5 months. Or maybe it has been moved somewhere else?

**Comment by dodgex** [comment]
Hey @xinaiz,

yes the project is still maintained. More or less. Currently there are only two maintainer. @WonderCsabo and I. We both have a full time job and work on AndroidAnnotations only in our free time.

This weekend I got some time to do some work on AA to get it a bit updated. including support for Android Studio 3.2 (PR is up) and AndroidX / Jetpack dependencies/classes (going to start work here after checking some issues).
