### ISSUE TITLE
SOS!!!!!!! AndroidAnnotations 无法生成***Activity_.java

### ISSUE THREAD

**Issue by Disaida** [androidannotations/androidannotations#2133]
git merge 代码之后，无法生成带下划线的class，但不知道什么原因造成的。怎么去查找原因呢。

**Comment by zqr95518** [comment]
怎么个无法生成法，测试版的AS好像不能用，你用正式版的。manifest文件里要先改，生成才不会报错

**Comment by mwgzs001** [comment]
有可能你代码引用那个id值没有 就不会生成框架自动生成那些文件 或者错误信息拉到最下边 一般都有具体的错误位置

**Comment by dodgex** [comment]
Please post issues in english only. Thanks.
