### ISSUE TITLE
hi i need to migrate annotation process

### ISSUE THREAD

**Issue by rexi1r** [androidannotations/androidannotations#2136]
This is a template, please adjust it accordingly to your specific issue.<br/>
You may also want to read our [issue guide](https://github.com/androidannotations/androidannotations/wiki/HowToWriteAnIssue).

**AndroidAnnotations version**:4.0-SNAPSHOT

**Android compile SDK version**:27

**Annotated code**:
```java
apt {
   arguments {
        androidManifestFile variant.outputs[0].processResources.manifestFile
        resourcePackageName 'com.pop.store'
      library 'true'
    }
}
```

**Stacktrace in case of AA crash**:

with previos version of gradle tools and wrapper i dont have any problem and all classes generate correctly but after update gradle tools i had to remvoe 'android-apt' and change the configuration but in confuse in migration!!!!!

**Comment by dodgex** [comment]
Have you checked the gradle sample project? https://github.com/androidannotations/androidannotations/tree/develop/examples/gradle
