### ISSUE TITLE
Why is this library unable to find automatically generated classes after changing the name of the project package?

### ISSUE THREAD

**Issue by HuaZaiWuDi** [androidannotations/androidannotations#2139]
This is a template, please adjust it accordingly to your specific issue.<br/>
You may also want to read our [issue guide](https://github.com/androidannotations/androidannotations/wiki/HowToWriteAnIssue).

**AndroidAnnotations version**:
# Why is this library unable to find automatically generated classes after changing the name of the project package?

Before it is used normally, you can't find automatically generated classes after changing the application package names. Can you answer the specific reasons?
**Android compile SDK version**:

**Annotated code**:
```java
your code
```

**Expected generated code**:
```java
expected generated code
```

**Actual generated code**:
```java
actual generated code
```

**Stacktrace in case of AA crash**:

**Comment by dodgex** [comment]
Can you please post more details? like your build.gradle and the androidannotations.log?

Thanks

**Comment by fededri** [comment]
Yes, this annoying
