### ISSUE TITLE
Fragment builders inheritance

### ISSUE THREAD

**Issue by tlevavasseur-innovantic** [androidannotations/androidannotations#2140]
Hi, it could be nice if when `FragmentB extends FragmentA` then `FragmentB_.FragmentBuilder_ extends FragmentA_.FragmentBuilder_`.

Builders are nice when you have fragments with lots of optional params but when you want to provide abstract/default implementation of a fragment, you can not have mutualized configuration code : 

`
public void defaultConfig(MyAbstractFragment_.FragmentBuilder_ builder) { ... }
`

(currently using 4.4.0)

Thanks !

**Comment by dodgex** [comment]
Hey there,

I'm pretty sure we are not going to let one fragment builder extend one form another fragment.

Not sure what `defaultConfig` is supposed to do but maybe [`FragmentBuilder#args()`](https://github.com/androidannotations/androidannotations/blob/develop/AndroidAnnotations/androidannotations-core/androidannotations-api/src/main/java/org/androidannotations/api/builder/FragmentBuilder.java#L176) and [`FragmentBuilder#args(Bundle)`](https://github.com/androidannotations/androidannotations/blob/develop/AndroidAnnotations/androidannotations-core/androidannotations-api/src/main/java/org/androidannotations/api/builder/FragmentBuilder.java#L36) (which copys the data from the given bundle into the current one) can help you to do something similar.

```java
Bundle fragArgs = new FragA.FragmentBuilder().arg("foo","bar").args();
FragB fragmentB = new FragB.FragmentBuilder().arg("baz","foo").arg(fragArgs).build();
```

**Comment by tlevavasseur-innovantic** [comment]
Could be usefull in this case : 

`
@EFragment
MyLibFragment {

	@FragmentArg
	protected String title;
}

@EActivity
MyLibActivity {

	protected MyLibFragment_.FragmentBuilder_ createFragmentBuilder() {
		
		return MyLibFragment_.builder();
	}

	protected MyLibFragment createFragment() {
		
		return createFragmentBuilder().title("The title").build();
	}	
}

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

@EFragment
MyAppFragment extends MyLibFragment {

	@FragmentArg
	protected String color;
}

@EActivity
MyAppActivity exends MyLibActivity {

	@Override
	protected MyLibFragment_.FragmentBuilder_ createFragmentBuilder() {
	
		// Note that "title" is still configured by super class
		return MyAppFragment_.builder().color("red");
	}
}
`

Pretty sure it was not in the logic of your classes generation, I made my own androidannotations plugin to do that (kind of).

But ok, I could use the .args() & .arg(Bundle) methods :

`
@EActivity
MyLibActivity {

	protected MyLibFragment createFragment() {
		
		return MyLibFragment_.builder().args(createFragmentArgs()).build();
	}

	protected Bundle createFragmentArgs() {
		
		return MyLibFragment_.builder().title("The title").args();
	}
	
}

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

@EActivity
MyAppActivity {

	@Override
	protected MyLibFragment createFragment() {
		
		return MyAppFragment_.builder().arg(createFragmentArgs()).color("red").build();
	}
}
`

Thanks for your reply.

**Comment by dodgex** [comment]
While I understand your usecase i think it is not worth the work considering the easy workaround.

also IIRC you can still put default values in the fragment fields. If I'm not mistaken they should not be overriden if the fragment arg is not present. but you could verify that by looking at the generated code.

I'll close this issue as won't fix.
