### ISSUE TITLE
Support AndoridX support classes (e.g. androidx.fragment.app.Fragment)

### ISSUE THREAD

**Issue by dodgex** [androidannotations/androidannotations#2144]
Currently AA does not support the classes from AndroidX dependencies.

e.g. in addition to `android.app.Fragment` and `android.support.v4.app.Fragment` we also should support `androidx.fragment.app.Fragment`.

**Comment by dodgex** [comment]
The new Constants for AndroidX
```
ANDROIDX_ACTIVITY_COMPAT
ANDROIDX_FRAGMENT
ANDROIDX_FRAGMENT_ACTIVITY
ANDROIDX_LOCAL_BROADCAST_MANAGER
ANDROIDX_CONTEXT_COMPAT
ANDROIDX_PREFERENCE
ANDROIDX_PREFERENCE_FRAGMENT
ANDROIDX_PREFERENCE_FRAGMENTCOMPAT
ANDROIDX_PREFERENCE_CLICK_LISTENER
ANDROIDX_PREFERENCE_CHANGE_LISTENER
ANDROIDX_APPCOMPAT_ACTIVITY
ANDROIDX_VIEW_PAGER
ANDROIDX_PAGE_CHANGE_LISTENER
```

**Comment by dodgex** [comment]
Work on this is blocked by the other 3 PR. @WonderCsabo would be nice when you can review them tomorrow.

**Comment by sandsaber** [comment]
+ data binding, currently @DataBound does not work with android x data binding

**Comment by dodgex** [comment]
Hey @sandsaber could you please test if the updated PR https://github.com/androidannotations/androidannotations/pull/2149 works with databinding?

Thanks!

**Comment by vonclutch** [comment]
@dodgex Any news about this pr ?

**Comment by WonderCsabo** [comment]
Fixed.
