### ISSUE TITLE
@OrmLiteDao with @EViewGroup in AdapterView crashes on Android Nougat.

### ISSUE THREAD

**Issue by ytakahashi1981** [androidannotations/androidannotations#2150]
**AndroidAnnotations version**:

4.4.0

**Android compile SDK version**:

27

**Annotated code**:
```java
@EViewGroup(R.layout.layout1)
public class Layout1View extends FrameLayout {
    @OrmLiteDao(helper = Helper.class)
    SomeDao someDao;

    // this method will called by Adapter.
    public void show() {
        someDao.queryForId(0);
    }
}
```

When I use above view in AdapterView(ListView) and scroll AdapterView quickly again and again,
android causes IllegalStateException.

```
java.lang.IllegalStateException: attempt to re-open an already-closed object: SQLiteDatabase: [database file path]
    at android.database.sqlite.SQLiteClosable.acquireReference(SQLiteClosable.java:55) ~[na:0.0]
    at android.database.sqlite.SQLiteDatabase.rawQueryWithFactory(SQLiteDatabase.java:1314) ~[na:0.0]
    at android.database.sqlite.SQLiteDatabase.rawQuery(SQLiteDatabase.java:1257) ~[na:0.0]
    at com.j256.ormlite.android.AndroidDatabaseConnection.queryForOne(AndroidDatabaseConnection.java:203) ~[na:0.0]
```

**My Guess**

Before Nougat, View#onDetachedFromWindow will called only when AdapterView has destroyed.
But in Nougat, the method called in spite of AdapterView has not destroyed.
(Maybe called when every reusing View instance!)

So, database connection has closed against my will.
AndroidAnnotations's EViewGroup calles OpenHelperManager.getHelper in constructor, and
calles OpenHelperManager.releaseHelper in onDetachedFromWindow.

In my opinion, should call OpenHelperManager.releaseHelper when completely view destroyed (maybe timing of AdapterView has destroyed.).

----

How can we avoid this error?

**Comment by dodgex** [comment]
Not sure if there is any method that is called when a view is completely destroyed?

Maybe we should see if it is possible to instead of calling getHelper in the constructor call it from `onAttachedToWindow` but this might be to late for many cases...

**Comment by WonderCsabo** [comment]
Unfortunataly in a `View`, we can only use `onDetachedFromWindow()` to close the connections, there is no other callback. I would suggest to move your query call to a higher level, and call it using callbacks from your item views.
