### ISSUE TITLE
Can you create a plug-in that automatically generates BindView like butter knife?

### ISSUE THREAD

**Issue by HuaZaiWuDi** [androidannotations/androidannotations#2152]
I like androidannotations's annotation code very much, but because of its intrusive nature, there is no function of generating BindView plug-in like butter knife automatically. The project is a little heavy.

**Comment by WonderCsabo** [comment]
Unfortunataly , there is not possible. The way AA is architected, you have to use `@EXXX` annotations, and use the generated subclasses. We cannot change that without rewriting the whole project, and also we would have to remove lots of annotions.
