### ISSUE TITLE
Find view from parent fragment in child fragment

### ISSUE THREAD

**Issue by SnyersK** [androidannotations/androidannotations#2153]
Hi,

Is it possible to get a view from the parentFragment in a childFragment with AA?

The problem I'm having is the following:

```java
@EFragment(R.layout.parent)
class ParentFragment extends Fragment {
    //works fine, it's in R.layout.parent
    @ViewById(R.id.toolbar) Toolbar toolbar;
}
```

```java
@EFragment(R.layout.child)
class ChildFragment extends Fragment {
    //this is not found, because the 'HasViews' contentview (in 'onViewChanged') does not include the parentFragments layout
    @ViewById(R.id.toolbar) Toolbar toolbar;  
}
```

Is there some option to tell AA to check in the entire view hierarchy, not just the layout inflated by the fragment itself?

**Comment by WonderCsabo** [comment]
Sorry, but this is not possible. Actually it is not a good practice for your to components to access views outside its boundaries.
