### ISSUE TITLE
Crash on using @Bean for singleton in @EBean annotated class in Kotlin

### ISSUE THREAD

**Issue by rhythm9229** [androidannotations/androidannotations#2162]
**AndroidAnnotations version**: 4.4.0

**Android compile SDK version**: 28

**Annotated code**:

// UseSingleton.kt
@EBean
open class UseSingleton constructor() {
    @Bean
    lateinit var single:Single
   
    fun callSingletonMethod() {
        single.doSomething()
    }
}

// Single.kt
@EBean(scope = EBean.Scope.Singleton)
open class Single constructor() {
    fun doSomething() {
        println("hello!")
    }
}

--------------------------------------------------------------------------------------------
**Calling callSingletonMethod on UseSingleton object crashes with kotlin.UninitializedPropertyAccessException: lateinit property single has not been initialized**

This works fine if "@Bean" annotation for singleton is used inside "@EActivity" or "@EFragment"

**Comment by WonderCsabo** [comment]
@rhythm9229 did you try this with the latest SNAPSHOT? Can we close this issue?
