### ISSUE TITLE
@EFragment does not compile using kotlin

### ISSUE THREAD

**Issue by davidvirdeforshh** [androidannotations/androidannotations#2165]
**AndroidAnnotations version**: 4.4.0

**Android compile SDK version**: kotlin_version = '1.2.50'

**Annotated code**:
```java
@EFragment(R.layout.my_layout)
class MyFragment : Fragment() {
```

**Stacktrace in case of AA crash**:
org.androidannotations.annotations.EFragment cannot be used on a final element
@org.androidannotations.annotations.EFragment(value = R.layout.my_layout)

**Comment by robin4201** [comment]
I'm also encountered with this issue:

    import org.androidannotations.annotations.*
    @EFragment
    class MyFragment : Fragment() {

error message:  org.androidannotations.annotations.EFragment cannot be used on a final element

Solution: I found at last that "class MyFragment"  in kotlin is a final class, and cannot be inherited, so the solution is:

    @EFragment
    open class MyFragment : Fragment() {
