### ISSUE TITLE
how can i use aa in library

### ISSUE THREAD

**Issue by jielundewode** [androidannotations/androidannotations#2171]
AA ver is 4.5.1
AndroidStudio 3.2.1 
gradle 4.6
buildtoolsversion:28.0.3
library code：
@EActivity(resName = "view_actionsheet")
open class KotlinActitivy : AppCompatActivity() {
//    @Click(resName = ["txt_cancel"])
//    open fun clickCancel(){
//        finish()
//    }
}

apply plugin: 'com.android.library'
apply plugin: 'kotlin-kapt'
apply plugin: 'kotlin-android'

apply plugin: 'kotlin-android-extensions'

android {
    compileSdkVersion rootProject.ext.compileSdkVersion
    buildToolsVersion rootProject.ext.buildToolsVersion

    defaultConfig {
        minSdkVersion rootProject.ext.minSdkVersion

       //  If you have different applicationIds for buildTypes or productFlavors uncomment this block.
        javaCompileOptions {

            annotationProcessorOptions {
                arguments = ["library": "true"]
            }
        }
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    compileOnly "com.android.support:appcompat-v7:${rootProject.ext.supportLibraryVersion}"
    compileOnly "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"

    kapt "org.androidannotations:androidannotations:$AAVersion"
    compileOnly "org.androidannotations:androidannotations-api:$AAVersion"
}

when i write code in app,it likes this:
`   @Click(R.id.btn_aac)
    open fun testAAC() {
        ALog.e(KotlinActitivy_::class)
    }
`
the log is this 
`class com.adorkable.iosdialog.KotlinActitivy`
is not `com.adorkable.iosdialog.KotlinActitivy_`

**Comment by dodgex** [comment]
I think this might be related to https://youtrack.jetbrains.com/issue/KT-27571 where the generated java class gets wrong metadata added by the `kapt` annotation processor.

when you see the log message you can expect AA to work for your project. just the `::class` reference returns invalid data.

**Comment by dodgex** [comment]
We found the issue and a PR with a fix is up.

**Comment by dodgex** [comment]
Should be fixed in snapshots and upcoming Release

**Comment by jielundewode** [comment]
yes ，it fixed
