### ISSUE TITLE
androidstudio3.3Canary13cannot use aa4.5.2

### ISSUE THREAD

**Issue by zgnckzn** [androidannotations/androidannotations#2173]
the error message is:
Gradle may disable incremental compilation as the following annotation processors are not incremental: androidannotations-4.5.2.jar (org.androidannotations:androidannotations:4.5.2).
Consider setting the experimental feature flag android.enableSeparateAnnotationProcessing=true in the gradle.properties file to run annotation processing in a separate task and make compilation incremental.

**Comment by zgnckzn** [comment]
Could not find the AndroidManifest.xml file, using  generation folder [D:\Android\AS_PROJECTS\test\app\build\generated\source\apt\debug])

**Comment by dodgex** [comment]
PR to add support is up: https://github.com/androidannotations/androidannotations/pull/2174

**Comment by dodgex** [comment]
4.6.0-SNAPSHOT should work for you now :)
