### ISSUE TITLE
Support AndroidX？

### ISSUE THREAD

**Issue by han361769045** [androidannotations/androidannotations#2177]

**Comment by dodgex** [comment]
https://github.com/androidannotations/androidannotations/wiki/ReleaseNotes#4.5.1 ?

**Comment by dodgex** [comment]
If you have concrete problem, make a concrete issue.

**Comment by han361769045** [comment]
Sorry for that，
 
but when i use Androidx ，AA is incorrect

**Comment by dodgex** [comment]
1) do you use the correct version (4.5.2 at the moment)
2) do you have an error log?!
