### ISSUE TITLE
@FocusChange triggered twice when execute clearFocus() on editText

### ISSUE THREAD

**Issue by Saursinet** [androidannotations/androidannotations#2181]
On a view I have a LinearLayout which I want to collapse when I click on the EditText below and then to expand when we unfocus.
```xml
<EditText
            android:layout_width="1000dp"
            android:layout_height="43dp"
            android:layout_centerVertical="true"
            android:textSize="14.4sp"
            android:gravity="center_vertical"
            android:hint="@string/hint_query"
            android:layout_toEndOf="@+id/searchImage"
            android:id="@+id/searchBoxText"
            android:background="@null"
            android:layout_marginStart="16dp"
            android:inputType="text"
            tools:ignore="Autofill" />
```

with a focus change implemented on it :
```java
@FocusChange
void searchBoxText(EditText searchBoxText) {
    Log.d("change focus", "focus has changed with " + searchBoxText.hasFocus());
    if (!searchBoxText.hasFocus()) {
        if(upperView != null)
            upperView.setVisibility(View.VISIBLE);
    } else {
        if(upperView != null)
            upperView.setVisibility(View.GONE);
    }
}
```
And I got a touchListener on the parent which throws :
```java
searchBoxText.clearFocus();
```

The tablet I aim this code for support as the maximum API 24. My problem is that this code works perfectly in API 28 but not on API 24 where it throws the onFocusChange twice when clearFocus is called only once.

**Comment by dodgex** [comment]
Is the given view the first focusable one?

The documentation of [View#clearFocus()](https://developer.android.com/reference/android/view/View#clearFocus()) mentions the following:
> **Note:** When not in touch-mode, the framework will try to give focus to the first focusable View from the top after focus is cleared. Hence, if this View is the first from the top that can take focus, then all callbacks related to clearing focus will be invoked after which the framework will give focus to this view.

I think this is what is happening to you, and I'm pretty sure that is no AA related issue.

**Comment by Saursinet** [comment]
It is the first one indeed. The thing I do not understand is that with API 28 the behaviour works fine and onFocusChange is only called once. It is only on the version 24 that it doesn't behave well.

**Comment by dodgex** [comment]
This might be an issue with android API 24 itself or even with the installed rom / vendor modifications to the OS.
