### ISSUE TITLE
How to handle errors/exceptions on Rest API

### ISSUE THREAD

**Issue by shidcordero12** [androidannotations/androidannotations#2190]
**AndroidAnnotations version**:
4.5.2
**Android compile SDK version**:
28
**Annotated code**:
```java
@Rest(rootUrl = BuildConfig.API_URL,
        converters = { MappingJackson2HttpMessageConverter.class },
        interceptors = { HttpResponseInterceptor.class })
@Accept(MediaType.APPLICATION_JSON)
public interface UserRestService extends RestClientHeaders {

    @Post("/jwt-auth/v1/token")
    ResponseEntity<TokenModel> token(@Body LoginModel loginModel);


    @Post("/jwt-auth/v1/token/validate")
    void validateToken();
}
```

In the documentation, theres no deep discussion on how to create error handling, interceptors, request factory, etc. I look examples in the internet and I found nothing. I'm new to Android Annotation and Spring Boot API. Is it possible to include a project example?

I want to handle all possible errors discuss here. Were using wordpress rest api. https://wordpress.org/plugins/jwt-authentication-for-wp-rest-api/

**Comment by mleffert** [comment]
@shidcordero12 
I generally handle errors for any Rest API when the request is made. 
`
    @Background
    public void createAlert(Body body){
        ResponseRequest req;
        rest.setHeader("Authorization", app.getToken());
        try{
            req = rest.createPost(body);
        } catch(HttpClientErrorException e) {
            Log.d(TAG, e.getMessage());
        } catch (HttpServerErrorException e){
            Log.d(TAG, e.getMessage());
        }
        alerts.postFinished(req, false);
    }
`

**Comment by WonderCsabo** [comment]
I think it is documented pretty well [here](https://github.com/androidannotations/androidannotations/wiki/Rest-API#responseerrorhandler).
