### ISSUE TITLE
AA 4.5.2 with build:gradle: 3.3.0 not work

### ISSUE THREAD

**Issue by KalvinZhuang** [androidannotations/androidannotations#2191]
AndroidAnnotations version: 4.5.2
Android compile SDK version: 1.8
Android SDK Build-Tools: 28.0.3
com.android.tools.build:gradle:3.3.0
Android Studio: 3.3
Gradle using gradlew: 4.10.1

it work fine with 
com.android.tools.build:gradle:3.2.1
Gradle using gradlew: 4.6

**Comment by trr-amsiq** [comment]
Add this to your ```defaultConfig{}``` for now
```
javaCompileOptions {
            annotationProcessorOptions {
                arguments = [
                        "androidManifestFile": "$projectDir/src/main/AndroidManifest.xml".toString()
                ]
            }
        }
```

**Comment by WonderCsabo** [comment]
@dodgex i think we added AGP 3.3 support for AA 4.6

**Comment by dodgex** [comment]
@WonderCsabo yeah, you are right, i remembered doing 3.3 support but forgot that it has not been released. :)

**Comment by KalvinZhuang** [comment]
@WonderCsabo 
added :
```
maven {
            url = 'https://oss.sonatype.org/content/repositories/snapshots'
        }
```
but:
```
ERROR: Failed to resolve: org.androidannotations:androidannotations-api:4.6-SNAPSHOT

```

anybody can help me _(:з」∠)_?

**Comment by WonderCsabo** [comment]
You should have `org.androidannotations:androidannotations-api:4.6.0-SNAPSHOT`

**Comment by KalvinZhuang** [comment]
@WonderCsabo 
(*^▽^*) thank you,
 4.6.0-SNAPSHOT it work for me.
