### ISSUE TITLE
AS 3.3 - Could not find the AndroidManifest.xml file, using generation folder

### ISSUE THREAD

**Issue by davidcr** [androidannotations/androidannotations#2195]
On Android Studio 3.3 with according gradle configuration : gradle-4.10.1-all.
Pretty much something following along the line of : https://github.com/androidannotations/androidannotations/issues/2128.
Working correctly with com.android.tools.build:gradle 3.2.1.
Did not tried 4.6.0-SNAPSHOT as it’s a quite big app in production and I would like to avoid snapshots in production builds as much as possible.

**AndroidAnnotations version**:
4.5.2

**Android compile SDK version**:
28

**com.android.tools.build:gradle:**:
3.3.0

**Stacktrace in case of AA crash**:
e: error: Could not find the AndroidManifest.xml file, using  generation folder [/Users/user/project/appname/library/common/build/generated/source/kapt/debug])

**Comment by dodgex** [comment]
Please use 4.6.0-SNAPSHOT
