### ISSUE TITLE
How to receive the .withOptions bundle on other activity

### ISSUE THREAD

**Issue by shidcordero12** [androidannotations/androidannotations#2201]
**AndroidAnnotations version**: 4.6

**Android compile SDK version**: 28

**Annotated code**:
```java
 private void showFilter(){
        FilterActivity_.IntentBuilder_ intent = FilterActivity_.intent(this);
        if (bundle != null){
            intent.withOptions(bundle);
        }
        intent.startForResult(FILTER_RESULT);
    }
```

In the documentation, I cannot find how to receive the bundle in the Activity. Please help me how.

**Comment by WonderCsabo** [comment]
You have to create `ActivityOptions` and call `toBundle()`. Please see the [official Android docs](https://developer.android.com/reference/android/content/Context#startActivity(android.content.Intent,%20android.os.Bundle)).
