### ISSUE TITLE
Unit testings organization confusing

### ISSUE THREAD

**Issue by smaugho** [androidannotations/androidannotations#2209]
The unit testings for the module "androidannotations" are organized per annotation, and on each "annotation package", we have the Test class and some pre-constructed classes to test. 

Keeping the pre-constructed classes which are in fact a resource for our test (our test should always compile them) in the same folder seems confusing, though it can be understood that it facilitates programming of the Unit Tests. 

But then, when needing to test classes from the Android Support Library, these are placed instead under the "resources", and they should be provided to the compiler. I guess this was done to not make the test dependent on the support library, which is completely ok. 

But then, we have "2 methods" to organize the content of the tests, and that's really not clear. 

I do recommend to move all the "resources classes", including those which use "Android classes" to the "resources"  folder, since they are just "files"  that we are testing (on these test, have them included in the source path of the test itself is not necessary). 

Then, create a method "loadPath", which loads all the ".java"  classes which are there for the current test, in order to provide them to the "test compiler". 

This will make clear the test purpose. If you agree with it @WonderCsabo , @dodgex .. no that it should be done now for old test, but maybe this could be done for all the new created tests?

Maybe I got something wrong, if so, please let me know. Thanks!

**Comment by WonderCsabo** [comment]
@smaugho sorry, i do not agree. Having the annotated classes in the source folder has lots of benefits:

* we can reference them statically from the test cases, which avoids errors, and sometimes necessary
* we can have syntax highlighting etc in the IDE.

The other classes are in the resoures section, beause we can load them dinamically onto the classpath. This allows us to test scenarios with and without the support library. It also has a historical reason: when the test suite was created, the support library was not as widespread as today. It was a common scenario for apps to not include it. Moreover, the library was not easily available for Maven based builds.

We plan a big refactor to move the project over to Gradle, and add mandatory AndroidX support (for example framework Fragment was deprecated, so AndroidX is de facto mandatary for all apps). But we have to find the time for it... :)

Moreover, for this kind of discussions, feel free to open a room in Gitter and ping us. I do not think Github issues is the best way to do this.

**Comment by WonderCsabo** [comment]
And thanks for writing the tests in the current suite, i hope it is not a big deal, reading your comment above you already figured it out. If you need help, please ask on Gitter.
