### ISSUE TITLE
IDE cannot resolve resources with AA

### ISSUE THREAD

**Issue by rehovicova** [androidannotations/androidannotations#2222]
**AndroidAnnotations version**: 4.5.2
**Android compile SDK version**: 28
**Android studio version**: 3.3

I am working on a project using AA and android studio says it cannot resolve symbol R.<anything>.**<resource_name>**. I can build the app and run it just fine, but AS is complaining. It is really annoying. I has been like that for 2 weeks and I can't do it anymore. Everything is red and I have to type all string, layout, drawable names, which requires me to always go and look up the proper name.

I tried to clean the project, delete .gradle, delete .idea/caches, invalidate and restart... nothing is working.

Other projects without android annotations dont have the problem.

Edit: I can find resources from .xml files, but not from .java files.

**Comment by WonderCsabo** [comment]
I am pretty sure this is not related to AA itself. But if you can share the project (or a small reproducing example), we can have a look.

**Comment by rehovicova** [comment]
Sorry I cannot give out any code (job policy). I have never had this issue before, I am using the same AS version everywhere and most of my projects have the same gradle settings. They only differ in (not)using android annotations. I am not sure how to proceed in this issue though.

**Comment by WonderCsabo** [comment]
You can try to create an empty project which reproduces the issue, and
share that.

**Comment by jielundewode** [comment]
try to close instant run

**Comment by xbaker** [comment]
hi 
I have the same issue
****************************
`ERROR: Unable to resolve dependency for ':app@debug/compileClasspath': Could not resolve org.androidannotations:androidannotations-api:4.6.0.
Show Details
Affected Modules: app


ERROR: Unable to resolve dependency for ':app@debugAndroidTest/compileClasspath': Could not resolve org.androidannotations:androidannotations-api:4.6.0.
Show Details
Affected Modules: app


ERROR: Unable to resolve dependency for ':app@debugUnitTest/compileClasspath': Could not resolve org.androidannotations:androidannotations-api:4.6.0.
Show Details
Affected Modules: app
`
*********************************
this is my gradle
`apply plugin: 'com.android.application'
android {
    compileSdkVersion 28
    defaultConfig {
        applicationId "my.package.app"
        minSdkVersion 23
        targetSdkVersion 28
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
}

def AAVersion = "4.6.0"

dependencies {
    implementation 'android.arch.persistence.room:runtime:1.1.1'
    annotationProcessor 'android.arch.persistence.room:compiler:1.1.1'

    // don't forget the core RxJava dependecies
    implementation 'io.reactivex.rxjava2:rxandroid:2.0.2'
    implementation 'io.reactivex.rxjava2:rxjava:2.1.13'

// Room with RxJava support
    implementation 'android.arch.persistence.room:rxjava2:1.1.1'

    annotationProcessor "org.androidannotations:androidannotations:$AAVersion"
    implementation "org.androidannotations:androidannotations-api:$AAVersion"


    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation 'com.android.support:appcompat-v7:28.0.0'
    implementation 'com.android.support:support-v4:28.0.0'
    implementation 'com.android.support:design:28.0.0'

    implementation 'com.android.support.constraint:constraint-layout:1.1.3'
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'com.android.support.test:runner:1.0.2'
    androidTestImplementation 'com.android.support.test.espresso:espresso-core:3.0.2'
}
`

**Comment by rehovicova** [comment]
@jielundewode that seems to solve the issue, thank you!

@xbaker I don't see your post to be related. I noticed you are using the new version, maybe there is something wrong with it? Did you try lower versions?

**Comment by rehovicova** [comment]
And it is back! Instant run still disabled, but after two weeks I opened the code and it is again unable to find resources. This is the only project that uses AA and the only project that has this problem.
