### ISSUE TITLE
how to set viewpager tab item in landscap mod in android

### ISSUE THREAD

**Issue by Husnainchattha** [androidannotations/androidannotations#2223]
This is a template, please adjust it accordingly to your specific issue.<br/>
You may also want to read our [issue guide](https://github.com/androidannotations/androidannotations/wiki/HowToWriteAnIssue).

**AndroidAnnotations version**:

**Android compile SDK version**:

**Annotated code**:
```java
your code
```

**Expected generated code**:
```java
expected generated code
```

**Actual generated code**:
```java
actual generated code
```

**Stacktrace in case of AA crash**:

**Comment by WonderCsabo** [comment]
You did not add any information to the template. But from the title, this issue is not related to AndroidAnnotations at all.
