### ISSUE TITLE
Classes does not generated

### ISSUE THREAD

**Issue by erich1105** [androidannotations/androidannotations#2225]
**4.6.0, 4.7.0 Snapshot**:

**28/28.0.3**:

App has been developed in 3 and it would generate classes with error(due HasView issue, can't use v3 anymore.)
But when i uprade to v4, classes does not generated and compiles failed at app:processDebugAnnotationsWithJavac.

log file also does not generated.
Bug makes me crazy.
Could you please help me to hint any?

PS: If I create simple one with above same versions, it will work.
Thank you.

**Comment by WonderCsabo** [comment]
By v4, you mean AndroidAnnotations 4.x ?

**Comment by thanathos91** [comment]
Same problem, but I've read the huge log text and all errors, but it shows only generated classes errors (cannot find symbol)..

**Comment by mouness2020** [comment]
same problem here with last gradle 5.4.1

**Comment by kemsky** [comment]
Updating com.android.tools.build:gradle:3.4.1 to com.android.tools.build:gradle:3.5.0 breaks everything

**Comment by Hoardon** [comment]
Confirm updating ```com.android.tools.build:gradle:3.4.1``` to ```com.android.tools.build:gradle:3.5.0``` breaks any annotate class generation.

Any solution ? Any new version offering a correction ?

**Comment by WonderCsabo** [comment]
Are you using `4.7.0-SNAPSHOT` ?

Please provide a sample project which reproduces the issue.

**Comment by Hoardon** [comment]
Just test with ```4.7.0-SNAPSHOT```, it works perfectly fine. 

Thanks for your help and the quick answer !

Any idea on the ```4.7.0``` release date ?

**Comment by WonderCsabo** [comment]
Maybe next week.  :) But feel free to use the snapshot, [it will not have any breaking changes](https://github.com/androidannotations/androidannotations/pulls?q=is%3Apr+milestone%3A4.7.0+is%3Aclosed).
