### ISSUE TITLE
Cannot use annotation of view in @EService

### ISSUE THREAD

**Issue by YasutoKobayashi** [androidannotations/androidannotations#2226]
I sometimes create view in service.
This is the reason that I want to check anything the device working; For example, checking the working application, checking the communication, and so on.
On happening the error about those checking, I sometimes show the caution's view on overlay layer.
Now I try to use the annotations about the kind of view, @ViewById @OnClick etc....
But it happens build error because those annotations cannot use in @EService.

I want to use these annotations in @EService.
And I want to set the view like below.
@EService(view = R.layout.sample, width = ViewGroup.LayoutParams.MATCH_PARENT, height = ViewGroup.LayoutParams.MATCH_PARENT, layer = WindowManager.LayoutParams.TYPE_APPLICATION_OVERLAY)

**AndroidAnnotations version**:
4.6.0

**Android compile SDK version**:
Android Oreo

**Comment by WonderCsabo** [comment]
Sorry, this is by design. The overlay is an edge case, and we would rather not support this.
