### ISSUE TITLE
Where is org.androidannotations.api.Lazy after migration from 3.3.2 to 4.6.0?

### ISSUE THREAD

**Issue by nikialeksey** [androidannotations/androidannotations#2228]
`Lazy.java` is missing after migration from 3.3.2 to 4.6.0, and [migration guide](https://github.com/androidannotations/androidannotations/wiki/4.0.0-migration-guide) does not help me with `Lazy`.

**Comment by WonderCsabo** [comment]
I think that file is coming from Dagger, and not AndroidAnnotations.

**Comment by nikialeksey** [comment]
Oh, sorry, I just found it is from our own andropidannotations fork.
