### ISSUE TITLE
[Security] Is it possible to extract annotations from api library?

### ISSUE THREAD

**Issue by XieEDeHeiShou** [androidannotations/androidannotations#2234]
**AndroidAnnotations version**: 4.6.0

**Android compile SDK version**: 28

**Annotated code**:
```java
no code
```

**Expected generated code**:
```java
no generated code
```

**Actual generated code**:
```java
no generated code
```

**Stacktrace in case of AA crash**: 
```
no crash
```

I'm doing some reverse engining with jadx recently, so I'm hoping if the annotations can be extract from api library in some kind of byte code security consideration.

When I decompile a dex file into source code, I could esaily found out which annotation the original author is using (as the default proguard rule keeps all annotations).
```progaurd
-keepattributes *Annotation*
```

Since AA works on compile time, it is possible to remove all AA's annotations from byte code to increase the difficulty of reverse enginering.

**Comment by WonderCsabo** [comment]
I think you can remove it in your build, after the annotation processing is done.

**Comment by XieEDeHeiShou** [comment]
> I think you can remove it in your build, after the annotation processing is done.

Could you please give me an example?

I have no idea about how to 'remove it in build'.

**Comment by WonderCsabo** [comment]
Well, this is totally out of scope of AndroidAnnotations. :) 

However, you can use the Transform API to do that. 
https://speakerdeck.com/mannodermaus/exploring-the-android-transform-api
https://medium.com/grandcentrix/transform-api-a-real-world-example-cfd49990d3e1
