### ISSUE TITLE
Error: Program type already present: net.jcip.annotations.NotThreadSafe

### ISSUE THREAD

**Issue by zhouyong0330** [androidannotations/androidannotations#2238]
This is a template, please adjust it accordingly to your specific issue.<br/>
You may also want to read our [issue guide](https://github.com/androidannotations/androidannotations/wiki/HowToWriteAnIssue).

**AndroidAnnotations version**:
4.6
**Android compile SDK version**:
4.6
**Annotated code**:
```java1.8
your code

 grade version 4.6 

After I upgraded to 4.6, configuration annotations had this problem, and I checked out that there was a conflict in the ormlite implementation ("org. androidannotations: ormlite: $AAVersion"). I tried this implementation ("org. androidannotations: ormlite: $AAVersion").{
// exclude group:'com. google. code. findbugs'
// exclude module:'annotations'
}

It can be compiled successfully, but the public class database Helper extends OrmLiteSqliteOpenHelper class can not be created successfully. My breakpoint is on create.

**Comment by WonderCsabo** [comment]
Are you using the `net.jcip.annotations.NotThreadSafe` annotation? The error message is complaining because of that.

**Comment by WonderCsabo** [comment]
This issue is unrelated to AndroidAnnotations.
