### ISSUE TITLE
How to change build tools version to 3.0+ ????

### ISSUE THREAD

**Issue by Liam6666** [androidannotations/androidannotations#2245]
Current tools version is 2.3.0 , how to change this to higher ??

**Comment by CH-Augustine** [comment]
Can you update 'Documentation' for API?
That's show last update time is 2016 ???? This so old , right?

**Comment by Liam6666** [comment]
Part path of WIKI : androidannotations/wiki/Building-Project-Gradle

**Comment by WonderCsabo** [comment]
You are referring to the Android Gradle Plugin version. AndroidAnnotations works with the latest (3.5.0), if you update to AndroidAnnotations 4.7.0-SNAPSHOT. The stable 4.6.0 AndroidAnnotations works with Android Gradle Plugin 3.4.0.

I updated the wiki page anyway. :)
