### ISSUE TITLE
"Incorrectly typed data found for annotation element" after upgrade to SDK28

### ISSUE THREAD

**Issue by w201** [androidannotations/androidannotations#2246]
Can't understand whats happens but now have stable problem with compiling with AA.
```java
/AddEditEventFragment.java:239: error: Something went wrong: Unexpected error in AndroidAnnotations 4.6.0!
    public void afterViews() {
                ^
....
 Caused by: java.lang.annotation.AnnotationTypeMismatchException: Incorrectly typed data found for annotation element public abstract int org.androidannotations.annotations.EFragment.value() (Found data of type R.layout)
  	at com.sun.tools.javac.model.AnnotationProxyMaker$ValueVisitor$1AnnotationTypeMismatchExceptionProxy.generateException
```
```java
import org.androidannotations.annotations.AfterViews;
import org.androidannotations.annotations.Click;
import org.androidannotations.annotations.EFragment;
import org.androidannotations.annotations.ViewById;
import android.support.v4.app.Fragment;
import android.support.v4.app.FragmentManager;
import com.amicuscreative.zola.R;
@EFragment(R.layout.fragment_event_details_edit)
public class AddEditEventFragment extends Fragment
        implements AdapterView.OnItemLongClickListener, AdapterView.OnItemClickListener, ReminderAddListener {
....
}
```

AA - 4.6.0
gradle plugin - 3.5.0
gradle - 5.4.1

Of course layout is present.

**Comment by WonderCsabo** [comment]
Did you try to clean and build the project. From the error, it seems it was built with a source code like this:
```java
@EFragment(R.layout)
public class AddEditEventFragment extends ...
```

**Comment by w201** [comment]
I tried clean it, manual delete all caches (gradle, build & so on). Without any success.
I created empty project and use my gradle.build files - all compiled fine without problem.

**Comment by WonderCsabo** [comment]
By the way, AA `4.6.0` should not work with Gradle plugin `3.5.0`. For that, you have to use AA `4.7.0-SNAPSHOT` for now.

Did you try to search for other `R.layout` usages in annotations?

**Comment by w201** [comment]
switching AA to 4.7.0 doesn't help
switching gradle plugin to 3.4.0 doesn't help

About searching other R.layout didn't understand. 
Also interesting if I make changes in code to this
```java
@EFragment
public class AddEditEventFragment extends Fragment
...
@Nullable
    @Override
    public View onCreateView(@NonNull LayoutInflater inflater, @Nullable ViewGroup container, @Nullable Bundle savedInstanceState) {
        return inflater.inflate(R.layout.fragment_event_details_edit, container, false);
    }
```
It will not change error report. It will remains the same. 
```java 
Caused by: java.lang.annotation.AnnotationTypeMismatchException: Incorrectly typed data found for annotation element public abstract int org.androidannotations.annotations.EFragment.value() (Found data of type R.layout)
```

**Comment by w201** [comment]
The Problem was in google volley lib. I had in other file import ...volley.* and my_package.*, and R classes conflicted. 
when I change volley.* to couple of volley.class_name it compiled without problem...
Also idea try to optimize imports and could at any moment switch volley.class_name to volley.* but its less problem than was :)

Thank you for your help and patience.

**Comment by WonderCsabo** [comment]
No problem, i am glad you could resolve the issue!
