### ISSUE TITLE
faulty import statement generated when Nullable annotation is used.

### ISSUE THREAD

**Issue by krischik** [androidannotations/androidannotations#2247]
**AndroidAnnotations version**:
4.6.0

**Android compile SDK version**:
28

**Annotated code**:
```java
   @org.jetbrains.annotations.Nullable
   @org.androidannotations.annotations.FragmentById (net.sourceforge.uiq3.hp45.R.id.MainCalculator)
   protected CalculatorFragment Calculator;
```

**Expected generated code**:
```java
import net.sourceforge.uiq3.hp45.Calculator_Fragment;
```

**Actual generated code**:
```java
import(@org.jetbrains.annotations.Nullable :: net.sourceforge.uiq3.hp45.Calculator_Fragment);
```

**Additional note**:
I'm in transition form maven to gradle build. The maven build still works fine.

Removing the `@org.jetbrains.annotations.Nullable` will lead to other problem with the annotation preferences.

**Comment by WonderCsabo** [comment]
This is quite strange, that the Maven build still works for you. As a processor, it does not really matter what build tool is used, and actually the processor is not aware of the build tool at all.

**Comment by krischik** [comment]
> Are you sure the migration was correct?

No. But I also don't know was the problem could be.

So even if the migration is faulty there would be an error hander and a proper understandable error message be missing.

AA should not generate faulty code. 😉
