### ISSUE TITLE
Annotations for interfaces support

### ISSUE THREAD

**Issue by ArtemiyDmtrvch** [androidannotations/androidannotations#2252]
In kotlin I have an interface with an implemented method:
```
interface IFragment {
    
    @OnActivityResult(MY_REQUEST_CODE)
    fun myOnActivityResult(resultCode: Int) {
        print(resultCode)
    }
}
```
 Next, I want to implement it to a class annotated with `EFragment` so that my method works, but I have compilation error.

**Comment by dodgex** [comment]
The compilation error would help to debug your issue.

But I think there is no solution for what you want to achiev. And there are no plans to support a setup like this.
