### ISSUE TITLE
@NonConfigurationInstance problem with AndroidX

### ISSUE THREAD

**Issue by LaurieScheepers** [androidannotations/androidannotations#2254]
I recently upgraded a legacy project that uses AndroidAnnotations to AndroidX (Jetpack). Everything went well so far, but now I'm stuck facing this issue explained below:

Any `@NonConfigurationInstance` annotated object in a class causes the following build error (after AA code generation occurs):

```
error: onRetainNonConfigurationInstance() in MyActivity_ cannot override onRetainNonConfigurationInstance() in ComponentActivity
overridden method is final
```

**AndroidAnnotations version**:
4.6.0

**Android compile SDK version**:
28

Any help would be appreciated, thanks.

**Comment by WonderCsabo** [comment]
It seems the NonConfigurationInstance mechanism is deprecated now.
