### ISSUE TITLE
Using @Click with data binding

### ISSUE THREAD

**Issue by SivaramSS** [androidannotations/androidannotations#2255]
Hi,
I have declared my data in the layout file as follows. I'm trying to pass data object to my ClickHandler method.

`<data>
    <variable
        name="data"
        type="com.siva.sample.Data" />
</data>`
`<View android:id="@+id/myClickView"
         ...
         android:onClick="@{()->ClickHandler.handleViewClick(data)}" />
</layout>`

The problem with above approach is that, i have to repeat this onClick code for different configuration (landscape, sw600 etc). Instead a one time assigning would help me a lot. I'm expecting to do something like this.

`@OnClick(R.id.myClickView) //get data object here public static void handleViewClick(Data data) { ... }`

Is it possible to achieve this somehow?

**Comment by dodgex** [comment]
No, this is not possible with AA.
