### ISSUE TITLE
Upgrading from 3.2 to 4.6.0 now all @Subscribe Method not working?

### ISSUE THREAD

**Issue by attaullahpro** [androidannotations/androidannotations#2259]
After 2 years i upgrade my code to android o now all @Subscribe Method is not working?

**AndroidAnnotations 4.6.0**:

**Android compile SDK 28**:

import com.squareup.otto.Bus;

```
import org.androidannotations.annotations.EBean;
import org.androidannotations.annotations.UiThread;

@EBean(scope = EBean.Scope.Singleton)
public class EventBus extends Bus {

    @Override
    @UiThread(propagation = UiThread.Propagation.REUSE)
    public void post(Object event) {
        super.post(event);
    }
}
```
in acitivity
```
 @Bean
    EventBus bus;

    @Override
    protected void onStart() {
        bus.register(this);
        super.onStart();
    }
```
usage 

`bus.post(new ShareVerseEvent(mSurah.getNo(), mViewPager.getCurrentItem() + 1));`

and 
```
    @Subscribe
    public void onShareVerse(ShareVerseEvent event) {
        if (event.surahNo != surahNo || event.verseNo != verseNo || mverse == null)
            return;
       Log.e(">>>>", "MyMsg");
        AlertDialog dialog = new AlertDialog.Builder(getActivity())
                .setItems(names.toArray(new String[names.size()]), new DialogInterface.OnClickListener() {
                    @Override
                    public void onClick(DialogInterface dialog, int which) {
                    // my code
                    }
                })
                .create();
        dialog.show();
    }
```
and  this
```

public class ShareVerseEvent {
    public final int verseNo;
    public final int surahNo;

    public ShareVerseEvent(int surahNo, int verseNo) {
        this.verseNo = verseNo;
        this.surahNo = surahNo;
    }
}
```

any method of @Subscribe is not working why???

**Comment by WonderCsabo** [comment]
Have you followed the migration guide? You have to add another dependency. Please se here. https://github.com/androidannotations/androidannotations/wiki/4.0.0-migration-guide

**Comment by attaullahpro** [comment]
> 
> 
> Have you followed the migration guide? You have to add another dependency. Please see here. https://github.com/androidannotations/androidannotations/wiki/4.0.0-migration-guide

i did not find any  @subscribe  method in migration link

**Comment by WonderCsabo** [comment]
You can find Otto there.

**Comment by attaullahpro** [comment]
> You can find Otto there.
Yes dear you see my code above I used the same as the following guide, but still @Subscribe method not working. even in android show method never used.

**Comment by attaullahpro** [comment]
> 
> 
> You can find Otto there.

Yes dear you see my code above I used the same as the following guide, but still @subscribe method not working. even in android show method never used.

**Comment by WonderCsabo** [comment]
Did you add this dependency to you build.gradle file?

annotationProcessor "org.androidannotations:otto:4.6.0

**Comment by attaullahpro** [comment]
> 
> 
> Did you add this dependency to you build.gradle file?
> 
> annotationProcessor "org.androidannotations:otto:4.6.0"

No! I forgot to `add annotationProcessor "org.androidannotations:otto:4.6.0"` now its working thanks @WonderCsabo
