### ISSUE TITLE
UI fields not initialized on @afterviews

### ISSUE THREAD

**Issue by Jean-MarcDENIEL** [androidannotations/androidannotations#2268]
Hello,

When using @afterviews to use saved state, I discovered that it is called several times between onCreate and onStart. The first time it is called, my UI fields are not initialized. Please see below my source code and the logs.

In my case, the firstViewEditName is null the first time afterviews method is called.
Looks like a bug.

Regards,
Jean-Marc

**AndroidAnnotations version**: 4.7.0

**Android compile SDK version**: 11

**Annotated code**:
package com.example.example_04;

import android.content.res.Configuration;
import android.os.Bundle;
import android.os.PersistableBundle;
import android.util.Log;
import android.widget.EditText;
import android.widget.Toast;

import org.androidannotations.annotations.AfterViews;
import org.androidannotations.annotations.Click;
import org.androidannotations.annotations.EActivity;
import org.androidannotations.annotations.LongClick;
import org.androidannotations.annotations.ViewById;

import androidx.annotation.NonNull;
import androidx.appcompat.app.AppCompatActivity;

import com.example.example_04.R;

@EActivity(R.layout.first_view)
public class MainActivity extends AppCompatActivity {

    private final String FIRST_VIEW_EDIT_NAME = "firstViewEditName";
    private String firstViewEditNameState;

    @ViewById(R.id.firstViewEditName)
    protected EditText firstViewEditName;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        Log.d("MainActivity", "onCreate");
        super.onCreate(savedInstanceState);

        if (savedInstanceState != null){
            firstViewEditNameState = savedInstanceState.getString(FIRST_VIEW_EDIT_NAME);
        }

        setContentView(R.layout.activity_main);
    }

    @AfterViews
    protected void afterViews(){
        Log.d("MainActivity","afterViews : State = " + firstViewEditNameState +
                " editName = " + firstViewEditName);
    }

    @Override
    protected void onSaveInstanceState(@NonNull Bundle outState) {
        Log.d("MainActivity", "onSaveInstanceState");
        super.onSaveInstanceState(outState);
        outState.putString(FIRST_VIEW_EDIT_NAME, String.valueOf(firstViewEditName.getText()));
    }

    @Override
    protected void onRestoreInstanceState(@NonNull Bundle savedInstanceState) {
        Log.d("MainActivity", "onRestoreInstanceState");
        super.onRestoreInstanceState(savedInstanceState);
        firstViewEditName.setText(savedInstanceState.getString(FIRST_VIEW_EDIT_NAME));
    }

    @Click(R.id.firstViewValidate)
    protected void doValidate(){
        Toast.makeText(this,
                String.format("%s %s",
                        getString(R.string.firstViewToast),
                        firstViewEditName.getText().toString()),
                Toast.LENGTH_SHORT).show();
    }

    @LongClick(R.id.firstViewValidate)
    protected void doValidateLong(){
        Toast.makeText(this,
                String.format("%s %s",
                        getString(R.string.firstViewToastLong),
                        firstViewEditName.getText().toString()),
                Toast.LENGTH_SHORT).show();
    }

    @Override
    protected void onStart() {
        Log.d("MainActivity", "onStart");
        super.onStart();
    }

    @Override
    protected void onRestart() {
        Log.d("MainActivity", "onRestart");
        super.onRestart();
    }

    @Override
    protected void onStop() {
        Log.d("MainActivity", "onStop");
        super.onStop();
    }

    @Override
    protected void onResume() {
        Log.d("MainActivity", "onResume: State = " + firstViewEditNameState +
                " editName = " + firstViewEditName);
        super.onResume();
        if (firstViewEditName!= null &&  firstViewEditNameState != null) {
            firstViewEditName.setText(firstViewEditNameState);
        }
    }

    @Override
    protected void onDestroy() {
        Log.d("MainActivity", "onDestroy");
        super.onDestroy();
    }

    @Override
    public void onConfigurationChanged(@NonNull Configuration newConfig) {
        Log.d("MainActivity", "onConfigurationChanged");
        super.onConfigurationChanged(newConfig);
        setContentView(R.layout.first_view);
    }

    @Override
    protected void onPause() {
        Log.d("MainActivity", "onPause");
        super.onPause();

    }
}

**Execution Log after several turning from portrait to landscape orientation**:
04-05 15:14:33.168 20396-20396/com.example.example_04 D/MainActivity: onCreate
04-05 15:14:33.286 20396-20396/com.example.example_04 D/MainActivity: afterViews : State = null editName = null
04-05 15:14:33.304 20396-20396/com.example.example_04 D/MainActivity: afterViews : State = null editName = androidx.appcompat.widget.AppCompatEditText{ccf69e2 VFED..CL ......I. 0,0-0,0 #7f070057 app:id/firstViewEditName}
04-05 15:14:33.361 20396-20396/com.example.example_04 D/MainActivity: onStart
04-05 15:14:33.363 20396-20396/com.example.example_04 D/MainActivity: onResume: State = null editName = androidx.appcompat.widget.AppCompatEditText{ccf69e2 VFED..CL ......I. 0,0-0,0 #7f070057 app:id/firstViewEditName}
04-05 15:14:36.889 20396-20396/com.example.example_04 D/MainActivity: onPause
04-05 15:14:36.890 20396-20396/com.example.example_04 D/MainActivity: onSaveInstanceState
04-05 15:14:36.895 20396-20396/com.example.example_04 D/MainActivity: onStop
04-05 15:14:36.899 20396-20396/com.example.example_04 D/MainActivity: onDestroy
04-05 15:14:36.943 20396-20396/com.example.example_04 D/MainActivity: onCreate
04-05 15:14:36.960 20396-20396/com.example.example_04 D/MainActivity: afterViews : State =  editName = null
04-05 15:14:36.973 20396-20396/com.example.example_04 D/MainActivity: afterViews : State =  editName = androidx.appcompat.widget.AppCompatEditText{cfe8b50 VFED..CL ......I. 0,0-0,0 #7f070057 app:id/firstViewEditName}
04-05 15:14:36.975 20396-20396/com.example.example_04 D/MainActivity: onStart
04-05 15:14:36.975 20396-20396/com.example.example_04 D/MainActivity: onRestoreInstanceState
04-05 15:14:36.977 20396-20396/com.example.example_04 D/MainActivity: onResume: State =  editName = androidx.appcompat.widget.AppCompatEditText{cfe8b50 VFED..CL .F....I. 0,0-0,0 #7f070057 app:id/firstViewEditName}
04-05 15:14:40.329 20396-20396/com.example.example_04 D/MainActivity: onPause
04-05 15:14:40.329 20396-20396/com.example.example_04 D/MainActivity: onSaveInstanceState
04-05 15:14:40.329 20396-20396/com.example.example_04 D/MainActivity: onStop
04-05 15:14:40.329 20396-20396/com.example.example_04 D/MainActivity: onDestroy
04-05 15:14:40.362 20396-20396/com.example.example_04 D/MainActivity: onCreate
04-05 15:14:40.378 20396-20396/com.example.example_04 D/MainActivity: afterViews : State =  editName = null
04-05 15:14:40.385 20396-20396/com.example.example_04 D/MainActivity: afterViews : State =  editName = androidx.appcompat.widget.AppCompatEditText{1e2ecdbe VFED..CL ......I. 0,0-0,0 #7f070057 app:id/firstViewEditName}
04-05 15:14:40.386 20396-20396/com.example.example_04 D/MainActivity: onStart
04-05 15:14:40.386 20396-20396/com.example.example_04 D/MainActivity: onRestoreInstanceState
04-05 15:14:40.387 20396-20396/com.example.example_04 D/MainActivity: onResume: State =  editName = androidx.appcompat.widget.AppCompatEditText{1e2ecdbe VFED..CL .F....I. 0,0-0,0 #7f070057 app:id/firstViewEditName}
04-05 15:15:48.527 20396-20396/com.example.example_04 D/MainActivity: onPause
04-05 15:15:48.762 20396-20396/com.example.example_04 D/MainActivity: onSaveInstanceState
04-05 15:15:48.763 20396-20396/com.example.example_04 D/MainActivity: onStop
04-05 15:16:28.540 20396-20396/com.example.example_04 D/MainActivity: onRestart
04-05 15:16:28.541 20396-20396/com.example.example_04 D/MainActivity: onStart
04-05 15:16:28.541 20396-20396/com.example.example_04 D/MainActivity: onResume: State =  editName = androidx.appcompat.widget.AppCompatEditText{1e2ecdbe VFED..CL .F....ID 225,657-855,793 #7f070057 app:id/firstViewEditName}

**Comment by dodgex** [comment]
I think your Probleme might be caused because u use two Different Layouts. One im the EActivity annotation and then you call setContentView from your onCreate. Could you test to remove one of those Layout refrences?

You Do Not need to call setContentView when using the Layout in the annotation

**Comment by Jean-MarcDENIEL** [comment]
You are absolutely right :- I removed the second layout (to activity_main), and everything works absolutely fine.- I tried to leave a setContentView(first_view) as in @EActivity, and it calls afterviews twice and the UI field are initializedMaybe it just could be worth to note in @afterviews documentation that the method is called each time setContentView is called (through @EAcitivity or through onCreate).Thank you very much for your help ! :-)Best regards,Jean-Marc DENIELChargé d'étude et recherche en rayonnements optiquesINRSDépartement IET - Laboratoire PTEBureau  213-  Bât 27Rue du MorvanCS 6002754519 VANDOEUVRE CEDEXStandard : 03.83.50.20.00 poste 15.24Ligne directe : +(33)3.83.50.85.24-----"Kay-Uwe Janssen" <notifications@github.com> a écrit : -----A : "androidannotations/androidannotations" <androidannotations@noreply.github.com>De : "Kay-Uwe Janssen" <notifications@github.com>Date : 05/04/2020 21:13Cc: "Jean-Marc DENIEL" <jean-marc.deniel@inrs.fr>, "Author" <author@noreply.github.com>Objet : Re: [androidannotations/androidannotations] UI fields not initialized on @afterviews (#2268)
I think your Probleme might be caused because u use two Different Layouts. One im the EActivity annotation and then you call setContentView from your onCreate. Could you test to remove one of those Layout refrences?
You Do Not need to call setContentView when using the Layout in the annotation
