### ISSUE TITLE
correctErrorTypes = true not work for androidannotations kotlin

### ISSUE THREAD

**Issue by AhmedJAbuSada** [androidannotations/androidannotations#2270]
Hi 
I'm using androidannotation with kotlin but the solution for @SharedPref
kapt {
    correctErrorTypes = true
}
not working

**Comment by WonderCsabo** [comment]
Please share an example project which reproduces the issue.

**Comment by AhmedJAbuSada** [comment]
in gradle:

  dependencies {
        classpath 'com.android.tools.build:gradle:3.6.2'
        classpath "io.realm:realm-gradle-plugin:6.1.0"
        classpath 'com.google.gms:google-services:4.3.3'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
        classpath "org.jetbrains.kotlin:kotlin-allopen:$kotlin_version"
    }

apply plugin: 'kotlin-android'
apply plugin: 'kotlin-android-extensions'
apply plugin: 'kotlin-kapt'
apply plugin: 'kotlin-allopen'

allOpen {
    annotation("org.androidannotations.api.KotlinOpen")
}

kapt {
    correctErrorTypes = true
}


dependencies {
    implementation fileTree(include: ['*.jar'], dir: 'libs')
    testImplementation 'junit:junit:4.13'
    androidTestImplementation 'androidx.test:runner:1.2.0'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.2.0'
    implementation "com.google.android.gms:play-services-analytics:17.0.0"

    implementation 'org.jetbrains:annotations:18.0.0'

    annotationProcessor 'androidx.annotation:annotation:1.1.0'
    annotationProcessor 'org.androidannotations:androidannotations:4.7.0'
    implementation 'org.androidannotations:androidannotations-api:4.7.0'

    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
}

and when a build cannot resolve:

in Application class:
    @Pref
    public MyPrefs_ sMyPrefs;

relative class:
@SharedPref
public interface MyPrefs {
}

**Comment by WonderCsabo** [comment]
What is the exact error message you are getting?

**Comment by AhmedJAbuSada** [comment]
after build:
error: cannot find symbol
    public MyPrefs_ sMyPrefs;
           ^
  symbol:   class MyPrefs_
  location: class MainApplication

**Comment by AhmedJAbuSada** [comment]
this issue not for androidannotation, it is reflected with other library and I solved it thanks for helping.

**Comment by smory** [comment]
I have the same issue. Which lib cause issue in your case?
