### ISSUE TITLE
Android Gradle Plugin 4.0

### ISSUE THREAD

**Issue by chpasha** [androidannotations/androidannotations#2273]
Did anybody try AA with new android gradle plugin 4.0.0? I'm getting 
Could not find the AndroidManifest.xml file, using  generation folder [/xxxx/yyyy/zzz/build/generated/ap_generated_sources/debug/out])

**Comment by amunozg** [comment]
You can try to add this to build.gradle (app)

```
    defaultConfig {
        javaCompileOptions {
            annotationProcessorOptions {
                arguments = ["androidManifestFile": "$projectDir/src/main/AndroidManifest.xml".toString()]
            }
        }
    }
```

**Comment by chpasha** [comment]
I'm not sure that this is generally a good idea - it does the trick, but I think that the right behaviour would be to process merged manifest, not the original one, what AA actually does

**Comment by WonderCsabo** [comment]
We have to update AA to find the manifest with Android Gradle Plugin 4.0. Unfortunately they again changed where they put the merged manifest... Contributions are welcome!

**Comment by chpasha** [comment]
seem that there are several different places now depending on the type of the project for library there are multiple manifest files at 
./build/intermediates/library_manifest/BUILD_TYPE/AndroidManifest.xml
./build/intermediates/aapt_friendly_merged_manifests/BUILD_TYPE/aapt/AndroidManifest.xml
for application at
./build/intermediates/instant_app_manifest/BUILD_TYPE+FLAVOUR/AndroidManifest.xml
./build/intermediates/bundle_manifest/BUILD_TYPE+FLAVOUR/bundle-manifest/AndroidManifest.xml
./build/intermediates/merged_manifests/BUILD_TYPE+FLAVOUR/AndroidManifest.xml

**Comment by chpasha** [comment]
Seems like AGP 4.0.1 is working just fine with current AA version, I think the ticket can be closed

**Comment by jielundewode** [comment]
Good News
4.8.0-SNAPSHOT works fine！
