### ISSUE TITLE
Compile warning after upgrade to AA 4.7.0

### ISSUE THREAD

**Issue by moving-bits** [androidannotations/androidannotations#2274]
This is a link to https://github.com/cgeo/cgeo/issues/8339

With AndroidAnnotations 4.6 and gradle plugin 3.5.0 we encountered the error described in #2229 and used the workaround described there.

After release of AA 4.7.0 we upgraded to 4.7.0 and removed the workaround, and the error described in #2229 vanished.

But now a new compile warning is being generated on each run:

> Task :main:compileBasicDebugJavaWithJavac
> warning: A class activity declared in the AndroidManifest.xml cannot be found in the compile path: [leakcanary.internal.AppWatcherInstaller$MainProcess]

I couldn't find anything for it on either AndroidAnnotations or LeakCanary sites. Can someone shed some light on what to do to fix this bug? Thanks.

**Comment by WonderCsabo** [comment]
You can ignore that warning.
