### ISSUE TITLE
Example code showcases 4.7.0 annotation processor is not incremental

### ISSUE THREAD

**Issue by trod-123** [androidannotations/androidannotations#2277]
Hello,

https://github.com/androidannotations/androidannotations/pull/2264 has added incremental annotation processing which addressed https://github.com/androidannotations/androidannotations/issues/2193, but I don't think this really is the case as of `4.7.0` and the current `4.8.0-SNAPSHOT`.

Building the Kotlin example project provided in this repo, I get the following message:

```
> Task :kaptDebugKotlin
[WARN] Incremental annotation processing requested, but support is disabled because the following processors are not incremental: org.androidannotations.internal.AndroidAnnotationProcessor (DYNAMIC).
```

What does this mean? Is there a known workaround for this? 

I've just ran the Example code provided in this repo. Please let me know if you need additional info.

**Comment by dodgex** [comment]
I'm pretty sure the "problem" is that incremental processing is disabled by default ([see this line](https://github.com/androidannotations/androidannotations/pull/2264/files#diff-14345c85e6410a19fa70472a5b71551fR65))


Please try to enable [incremental](https://github.com/androidannotations/androidannotations/wiki/CustomizeAnnotationProcessing#incremental) in the [annotation processor options](https://github.com/androidannotations/androidannotations/blob/develop/examples/gradle/build.gradle#L35)

**Comment by trod-123** [comment]
Hello @dodgex , confirming that this had done the trick. I had missed this step after confirming in the release notes that incremental annotation processing was supported.

Closing issue out.

Thanks.
