### ISSUE TITLE
AA doesn't work with Kotlin1.4

### ISSUE THREAD

**Issue by ytakahashi1981** [androidannotations/androidannotations#2278]
AndroidAnnotations doesn't work with functions annotated with `@JvmOverloads` and `@UiThread`.
Since Kotlin1.4, jvm codes are seems to changed to given `final` modifier.
(maybe methods with default values are given the modifier.)

Any way to avoid this error?
Thanks.

**AndroidAnnotations version**: 4.6.0
**Android compile SDK version**: 28

**Annotated code**:
```kotlin
@UiThread
@JvmOverloads
fun test(arg1: String, arg2: String = "default") {}
```

**Stacktrace in case of AA crash**:
```
org.androidannotations.annotations.UiThread cannot be used on a final element
    @org.androidannotations.annotations.UiThread()
```

**jvm code with kotlin1.4**:
```java
@org.androidannotations.annotations.UiThread
public final void test(@org.jetbrains.annotations.NotNull() String arg1) {}

@org.androidannotations.annotations.UiThread
public void test(@org.jetbrains.annotations.NotNull() String arg1, @org.jetbrains.annotations.NotNull() String arg2) {}

```

**jvm code with kotlin1.3**:
```java
@org.androidannotations.annotations.UiThread
public void test(@org.jetbrains.annotations.NotNull() String arg1) {}

@org.androidannotations.annotations.UiThread
public void test(@org.jetbrains.annotations.NotNull() String arg1, @org.jetbrains.annotations.NotNull() String arg2) {}

```

**Comment by dodgex** [comment]
Try to define the method as open?

```
@UiThread
@JvmOverloads
open fun test(arg1: String, arg2: String = "default") {}
```

Otherwise i have no idea unfortunately.

**Comment by ytakahashi1981** [comment]
> Try to define the method as open?

Yes, tried. But doesn't work...(the same error occured)

It seems to:
* the default(full) method is defined as open(non-final) in jvm code.
* the generated(arguments abbreviated) methods are defined as final.

maybe, `open` modifier doesn't change these behavior.

**Comment by ytakahashi1981** [comment]
FYI: Dirty way to avoid this issue.
(divide function.)

```kotlin
@JvmOverloads
fun test(arg1: String, arg2: String = "default") {
  _internalTest(arg1, arg2)
}

@UiThread
protected fun _internalTest(arg1: String, arg2: String) {
  // do something.
}
```

**Comment by dodgex** [comment]
I'm glad you found a workaround for this problem. Unfortunately we can't fix that issue on our side as it is compiler generated code.

Would you open an Issue in the Kotlin Tracker to ask if that behaviour is desired or maybe a bug?

**Comment by dodgex** [comment]
In case you open an issue at Kotlin feel free to link it here so we can vote on it. :)

**Comment by ytakahashi1981** [comment]
See https://youtrack.jetbrains.com/issue/KT-33240
This behaviour is seems to be desired...😢

I opened https://youtrack.jetbrains.com/issue/KT-41235.
Could you complement our intention if necessary?
(It's hard to tell them in English for me because I'm not native English speaker...)

**Comment by dodgex** [comment]
I'm now watching the issue so I'll get a mail when they comment and if necessary I comment there too.

But yeah, KT-33240 does not make hope for a fix there. At least you have found a workaround, although it is not a nice solution

**Comment by WonderCsabo** [comment]
I am afraid we cannot "fix" this on AA-side. AndroidAnnotations fundamentally works using method overrides.
