### ISSUE TITLE
AA / Kotlin 1.4 / Gradle plugin warning

### ISSUE THREAD

**Issue by peterplamenovpenchev** [androidannotations/androidannotations#2281]
Hi,

I just updated the tooling of my playground project & the following warning appeared:

<img width="853" alt="Screenshot 2020-10-18 at 17 46 18" src="https://user-images.githubusercontent.com/22145248/96371366-1b783380-116a-11eb-8ea1-2b9dfe7e13a0.png">

Could you please advise?

Versions:
- Kotlin: 1.4.10
- Gradle plugin: 4.1.0
- AA: 4.7.0

**Comment by dodgex** [comment]
All annotations should have a [resName](https://github.com/androidannotations/androidannotations/blob/develop/AndroidAnnotations/androidannotations-core/androidannotations-api/src/main/java/org/androidannotations/annotations/EActivity.java#L107) attribute that does runtime lookup.

it is not as compile time safe as the id but if those id's are no longer final I'm afraid we can't do much about it
