### ISSUE TITLE
Why is String not a “preference simple type” and what should I use instead?

### ISSUE THREAD

**Issue by krischik** [androidannotations/androidannotations#2298]
Trying to compile my old code I came across the _”error: Method Version_Name should only return preference simple types in an org.androidannotations.annotations.sharedpreferences.SharedPref annotated interface”_ error.

That previously worked. So why was it changed? And what should I use instead. `String` is a pretty basic type and not being able to store string in the preferences makes the preference class useless.

And where is the documentation? Tacking circles in the Wiki finding no in depth info and no reference info on SharedPreferences.

Right not I'm at the point where I consider dumping AndroidAnnotations. For over a year I'm trying to get my old program to compile again and AA has become one of the mayor pains. The other pain would be Gradle — but I can't dump Gradle.

**AndroidAnnotations version**:

4.8.0

**Android compile SDK version**:

30

**Annotated code**:
```java
   /**
    * <p>
    * last version number used to detect updates
    * </p>
    *
    * @return last version number
    */
   @NotNull
   @DefaultString ("0.0(0)")
   public String Version_Name ();
```

**Expected generated code**:

N/A

**Actual generated code**:

N/A

**Comment by WonderCsabo** [comment]
String should be allowed, please continue our ongoing discussion here: https://github.com/androidannotations/androidannotations/issues/2248#issuecomment-747478084
