### ISSUE TITLE
androidx.viewbinding.ViewBinding vs ViewDataBinding

### ISSUE THREAD

**Issue by BlueCobold** [androidannotations/androidannotations#2300]
I've just tried to switch to DataBinding, because the 'kotlin-android-extensions' plugin I've been using is deprecated and I don't want to re-add all imported views with AndroidAnnotations to my code again. I added these to my gradle file:
```
    buildFeatures {
        viewBinding true
    }
...
kapt {
    correctErrorTypes = true
}
```
However, I'm getting a compile-error from AndroidAnnotations, because a different type of parent-class is being expected for data binding by AndroidAnnotations than what is being generated from DataBindings (androidx.viewbinding.ViewBinding base class). I'm not sure where to go from here.

** Error **
org.androidannotations.annotations.BindingObject can only be used on an element that extends one of the following classes: [androidx.databinding.ViewDataBinding, androidx.databinding.ViewDataBinding]

**AndroidAnnotations version**: 4.8.0

**Android compile SDK version**: 30

**Annotated code**:

```kotlin
@DataBound
@EActivity(R.layout.activity_main)
class MainActivity : BaseActivity() {

    @BindingObject
    internal lateinit var binding: ActivityMainBinding
````

**Comment by WonderCsabo** [comment]
AndroidAnnotations does not support view binding, only data binding.

**Comment by BlueCobold** [comment]
Thanks, that's what I've been missing. I enabled viewBinding, not dataBinding. Good to know it doesn't support it (yet) though.
