### ISSUE TITLE
 Resource IDs will be non-final in Android Gradle Plugin version 5.0, avoid using them as annotation attributes

### ISSUE THREAD

**Issue by FilipObornik** [androidannotations/androidannotations#2302]
When passing id to the annotation, Android Studio shows this warning:
> Resource IDs will be non-final in Android Gradle Plugin version 5.0, avoid using them as annotation attributes

For example: 
```java
@DataBound
@OptionsMenu(R.menu.menu_account)
@EFragment(R.layout.fragment_account)
```

Is there any solution to this warning. Butter Knife solved this as follows https://github.com/JakeWharton/butterknife/issues/1634

**Comment by WonderCsabo** [comment]
AndroidAnnotations also supports the R2 class. See [here](https://github.com/androidannotations/androidannotations/wiki/Library-projects#using-r2-class).

**Comment by FilipObornik** [comment]
Sorry, I missed that section, thank you

**Comment by WonderCsabo** [comment]
No problem! :)
