### ISSUE TITLE
Use @Prefs in Fragment

### ISSUE THREAD

**Issue by mserioli** [androidannotations/androidannotations#333]
I think that would be useful to add support of getting @Pref in @EFragment annotated class!

**Comment by ahmadalibaloch** [comment]
I am not using the EmployeeJobFragment class but `EmployeeJobFragment_` in my layout and also using 
`EmployeeJobFragment_.builder().arg("projectId",project.Id).build()`
and have the `@EFragment` on my Fragment class
but still In my `onCreateView `method of the fragment I am getting empty string for my token that is working right in the LogicActivity. There I get the token string value.
`String token = myPrefs.token().get();`

**Comment by WonderCsabo** [comment]
@ahmadalibaloch did you try using `@SharedPref(SharedPref.Scope.UNIQUE)`?
