### ISSUE TITLE
Unable to load annotation processor factory

### ISSUE THREAD

**Issue by Heneman** [androidannotations/androidannotations#359]
Hello,

 haven't been able to get Eclipse to load the AndroidAnnotations properly.  I've followed all of the bug fixes suggested by the AndroidAnnotations team to no avail.  I'm getting errors that `ArticleReaderActivity_` and `CommentsActivity_` cannot be resolved to a type, and in the Problems view there is this error :

```
Unable to load annotation processor factory '/HN-Android/androidannotations-2.5.jar' for project com.manuelmaly.hn.MainActivity_    com.manuelmaly.hn.MainActivity_
```

**Comment by DiogoSouza** [comment]
That's write @matthewmichihara, the ```.factorypath``` must have its reference pointing to the exactly project name it is located.
