### ISSUE TITLE
create Provider for Beans (lazy Loading)

### ISSUE THREAD

**Issue by alosdev** [androidannotations/androidannotations#399]
It would be nice to have Providers for Beans, which has the possibility for lazy loading of the real singleton, so it's not creates automatically an instance. Like the Provider in RoboGuice.

**Comment by athkalia** [comment]
Is there any way to load @Beans at a later time, only when it's actually used ?

**Comment by WonderCsabo** [comment]
There is no way to do that.

**Comment by athkalia** [comment]
Cool, thanks for the reply.
