### ISSUE TITLE
@ItemClick not working for AutoCompleteTextView

### ISSUE THREAD

**Issue by veelck** [androidannotations/androidannotations#472]
When trying to use @ItemClick for AutoCompleteTextView I get following exception:

java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example/com.example.activities.WithAutocompleteActivity_}: java.lang.ClassCastException: android.widget.AutoCompleteTextView

This is probably caused, since AutoCompleteTextView is not subclass of AdapterView<?>, and current implementation is trying to cast on it.

Is this issue known and are you trying/willing to fix it in future releases?
At least it might be nice to put an info in docs, that @ItemClick is not working for objects, that doesn't inherit from AdapterView.

Best regards,
Damian

**Comment by lukesleeman** [comment]
I recently ran into this issue as well, so I think it would definitely be a useful feature to have.  I'm not quite sure what @pyricau means by 

> We could consider implementing @ItemClick for AutoCompleteTextView, if you provide us with an example of what the implementation should look like.

Do you mean you want an example of what defining a `OnItemSelectedListener` for a `AutoCompleteTextView` looks like?  Or do you actually want a pull request that implements the requested functionality into Android Annotations?

If you are just after an example, it's really very simple.   `AutoCompleteTextView.setOnItemSelectedListener()` just takes a `AdapterView.OnItemSelectedListener` so really, it's exactly the same as `AdapterView.	setOnItemSelectedListener()` .  The only difference is `AutoCompleteTextView` doesn't extend from `AdapterView` it instead extends `EditText`.  Here is a simple example of using `AutoCompleteTextView` to call a method:

        autocomplete.setOnItemSelectedListener(new AdapterView.OnItemSelectedListener() {
            @Override
            public void onItemSelected(AdapterView<?> parent, View view, int position, long id) {
                autocompleteSelected(adapter.getItem(position));
            }

            @Override
            public void onNothingSelected(AdapterView<?> parent) {

            }
        });

**Comment by lukesleeman** [comment]
Actually, it turns out that doesnt work.  See:
https://stackoverflow.com/questions/9249919/autocompletetextview-onitemselectedlistener-does-not-work

Instead the code should look like this:

        autocomplete.setOnItemClickListener(new AdapterView.OnItemClickListener() {

            @Override
            public void onItemClick(AdapterView<?> parent, View view, int position, long id) {
                String item = adapter.getItem(position);
                autocompleteSelected(item);
            }
        });

**Comment by WonderCsabo** [comment]
@lukesleeman well, that means you could just add `@ItemClick` to a method with `id` referring to an `AutoCompleteTextView` and that is it.
