### ISSUE TITLE
SharedPref suggestions: default to unique and allow specifying preference file name

### ISSUE THREAD

**Issue by devesh** [androidannotations/androidannotations#534]
In the vanilla Android world, you look up a preference by a string key, which can lead to bugs if you have SharedPreferences in multiple Activities and accidentally use the same key for a preference that is local to each Activity. It arguably might make sense to default to local preferences in this case unless you know that you want to share a value across your application.

In the enhanced AndroidAnnotations world where you invoke a named method to get the preference, you can't run into this problem. I would argue that in this world, sharing the same preferences in all activities actually leads to fewer bugs for first-time users who see the "Shared" prefix and assume a certain meaning. Also, I think it would be cleaner for the developer to just create different preference interfaces for different Activities if the data shouldn't be shared instead of sharing all preference method names but not preference values.

Additionally, to simplify upgrading a legacy application to AndroidAnnotations, the annotation should take an optional value for the name of the preference file.

**Comment by WonderCsabo** [comment]
`@SharedPref.name()` was already added.
