### ISSUE TITLE
Powermock + Robolectric + AA

### ISSUE THREAD

**Issue by atali** [androidannotations/androidannotations#585]
In these page you are talking about using PowerMock + Robolectric:

https://github.com/excilys/androidannotations/wiki/Unit-test-your-application

But I am unable to get this works.

I try to mock MyClass_.getInstance() but the agent provided by powermock doesn't seems to work.

Do you have a sample ?

**Comment by jaredsburrows** [comment]
Does anyone have a `Gradle` Example?
