### ISSUE TITLE
A bug If I have the same method name 

### ISSUE THREAD

**Issue by Tanlet** [androidannotations/androidannotations#591]
Sorry for my awful English.
Thanks to your work!AndroidAnnotation is a great project.I like this so muck.But I think I find a bug in my project.

Class 1:

``` java
@EActivity
public class Test1 extends Activity {
    @AfterViews
    public void init() {
        Log.v("","Word");
    }
}
```

Class 2:

``` java
@EActivity
public class Test2 extends Test1 {
    @AfterViews
    public void init() {
        Log.v("","Hello");
    }
}
```

The result is twice "Hello".
The reason is easy to find. 
In the Test2_,We find this:

``` java
private void afterSetContentView_() {
      text = ((TextView) findViewById(id.text));
      init();
      init();
}
```

The right result is :

```
private void afterSetContentView_() {
     text = ((TextView) findViewById(id.text));
     init();
     supper.init();
}
```

Of course ,If you rename init() in Test2 to init2().It will work well.

**Comment by lukasz-plominski-PGS** [comment]
In base class I have

@AfterViews
protected void afterViews() {
...
}

Then in descendants 

@Override
protected void afterViews() {
    super.afterViews();
...
}

Fixes both problems with only one method called twice, and order of execution (issue #810).

One thing that is missing, is an Android Annotation error if it detects this problem, two annotated methods with same name in same class hierarchy. 
It would prevent this error, and it will give programmers hint how to fix it.

**Comment by hospitalitarian** [comment]
Half of this check can be performed with the `@CallSuper` support annotation.  The other half would be to ensure that `@AfterViews` is not put on a method and an override of that method.
