### ISSUE TITLE
@Rest: The converter class must be a subtype of org.springframework.http.converter.HttpMessageConverter	RestClient.java

### ISSUE THREAD

**Issue by studio4development** [androidannotations/androidannotations#611]
When trying to define a rest template using the @Rest annotation, and when providing one or more "converters" in that annotation, I receive the following compile error:

> The converter class must be a subtype of org.springframework.http.converter.HttpMessageConverter RestClient.java

When, in fact, I have tried to pass in GsonHttpMessageConverter.class and MappingJacksonHttpMessageConverter.class which are both such subtypes.

I have the following libraries included in my /libs directory

```
androidannotations-api-2.7.1.jar
gson-2.2.4.jar
jackson-core-asl-1.9.12.jar
jackson-mapper-asl-1.9.12.jar
spring-android-auth-1.0.1.RELEASE.jar
spring-android-core-1.0.1.RELEASE.jar
spring-android-rest-template-1.0.1.RELEASE.jar
```

I'm not sure if this is an issue with AndroidAnnotations or with my own setup, but help would be appreciated.

**Comment by satyaranjan** [comment]
its not working

**Comment by WonderCsabo** [comment]
@satyaranjan please elaborate...
