### ISSUE TITLE
Provide a way to specify a timeout in Rest Services

### ISSUE THREAD

**Issue by mnesarco** [androidannotations/androidannotations#651]
It would be nice if we can set the timeout in Rest method declarations. Something like:

``` java
@Get(value="/myresource", timeout=3000)
public Event getEvent(); 
```

or

``` java
@Get(value="/myresource")
@HttpOptions(timeout=3000)
public Event getEvent(); 
```

or

``` java
@Get(value="/myresource")
@Timeout(3000)
public Event getEvent(); 
```

**Comment by pedro-dzs** [comment]
Create a custom RequestFactory:

```
import org.springframework.http.client.SimpleClientHttpRequestFactory;

public class CustomRequestFactory extends SimpleClientHttpRequestFactory {

    public CustomRequestFactory() {
        setConnectTimeout(2000);
        setReadTimeout(2000);
    }
}
```

And put to `@Rest` annotation:

`@Rest(requestFactory = CustomRequestFactory.class)`

**Comment by UmeshNebhani7303** [comment]
is this issue fixed? as i dont understand a final solution on it. @Rest is part of which library?

**Comment by WonderCsabo** [comment]
`@Rest` is part of the AndroidAnnotations REST library.

**Comment by UmeshNebhani7303** [comment]
okay but how about if someone is not using AndroidAnnotations, do we have any solution for SpringBoot in general?

**Comment by WonderCsabo** [comment]
Sorry, this is AndroidAnnotations' repository. For Spring Boot questions, go to the relevant Spring Boot channels.
