### ISSUE TITLE
@Background ThreadFactory and Thread priority

### ISSUE THREAD

**Issue by arvola** [androidannotations/androidannotations#685]
Any thoughts on controlling the `ThreadFactory` for the Executor?

I needed a way to set priority on the background tasks, which was fairly easy to achieve by adding a priority parameter to the `@Background` annotation and using a custom `ThreadFactory`.

If it seems like a good addition to AA, I can clean up my changes and make a pull request. Being able to manipulate the Thread when it's created has other uses as well.

**Comment by gauravsak** [comment]
@WonderCsabo @yDelouis @dodgex Please review this issue and change the issue state accordingly. Thanks!

**Comment by WonderCsabo** [comment]
You can [set](https://github.com/androidannotations/androidannotations/blob/develop/AndroidAnnotations/androidannotations-core/androidannotations-api/src/main/java/org/androidannotations/api/BackgroundExecutor.java#L225) the `Executor` itself, so this is already supported.
