### ISSUE TITLE
@ViewById ineffective in fragment after orientation change

### ISSUE THREAD

**Issue by Timores** [androidannotations/androidannotations#811]
Hi,

I could not find a mention of this problem.

I have a simple fragment with 'ViewById' annotations. When the fragment is first displayed, everything is OK. If I rotate my phone, my application crashes as the fragment is recreated by Android (4.1.2), but onViewCreated is not called, thus the bindings are not re-established.
Am I missing anything ?

Edit: my issue is not with AA, I am creating fragments dynamically and in a specific case, one of them is created but not shown, so the AA code does not run. My fault. This "issue" can be closed.

**Comment by Rainer-Lang** [comment]
@Timores Thanks, that helped me.
