### ISSUE TITLE
Suggestion: lifecycle aware beans

### ISSUE THREAD

**Issue by PerfectCarl** [androidannotations/androidannotations#843]
Hello, 

I was writing an tutorial for [Otto](https://github.com/PerfectCarl/androidannotations/wiki/OttoIntegration) and was thinking about #335.
(Pretty much at the same time, I can be pretty badass on weekends)

In the Otto example, the `bus` needs to be aware of the Activity lifecyle (to register and unregister).
In #335's case, the `dbHelper` has the same needs: it needs to be notified of the Activity lifecycle to create and destroy instances.

At the moment, one needs to duplicate the register/unregister or creation/destruction code each time an activity uses a `bus`, or a `dbHelper`.

A solution would be to implement lifecycle hooks at the bean level.

``` java

@EBean
public class OttoBus implements BasicBus {

        public void onCreate(Activity parent, Bundle savedInstanceState) {
                this.register(parent);
        }

        public void onDestroy(Activity parent) {
                this.unregister(parent);
        }
}
```

Any activity using the bus would have only inject the bean, AA being responsible for calling the lifecycle methods (if defined, of course)

``` java
@EActivity(R.layout.hello_activity)
public class HelloAndroidActivity extends FragmentActivity {

        @Bean
        OttoBus bus;

    @Subscribe
    public void onUpdateTitle(UpdateTitleEvent event) {
        setTitle(event.title);
    }

}
```

Instead of this: 

``` java
@EActivity(R.layout.hello_activity)
public class HelloAndroidActivity extends FragmentActivity {

        @Bean
        OttoBus bus;

        @Override
        protected void onCreate(Bundle savedInstanceState) {
                super.onCreate(savedInstanceState);
                bus.register(this);
        }

        @Override
        protected void onDestroy() {
                super.onDestroy();
                bus.unregister(this);
        }

    @Subscribe
    public void onUpdateTitle(UpdateTitleEvent event) {
        setTitle(event.title);
    }

}
```

And the same goes for the `dbHelper`.

There may be other use cases for this, and let developer to integrate other framework with AA without having to subclass Activity classes, or submit patches to AA.

What do you think?

**Comment by Artyomcool** [comment]
Hey, guys!
Don't you think, that @NotifyLifecycle enforce any component that uses the bean to know its internal implementation details? It makes everything tightly coupled, but a reason to implement the feature is decoupling beans from Android components, right?

**Comment by WonderCsabo** [comment]
Rising issue from the dead? :)

Maybe we should do some subscriber-listener based event notification, lie RoboGuice do?

**Comment by Artyomcool** [comment]
> Maybe we should do some subscriber-listener based event notification, lie RoboGuice do?

I like idea of separate annotations for attach/dettach/create/destroy/start/stop/resume/pause. And start only with Activity and Fragment. After that, if everything looks good, think about other components.

**Comment by WonderCsabo** [comment]
I see. And how you call bind those annotated methods to the methods in the component?

**Comment by Artyomcool** [comment]
```
public class MyActivity_ extends MyActivity {

    public void onCreate(Bundle savedInstanceState) {
        ...
        super.onCreate(savedInstanceState);
        myBean.onCreate();
        ...
    }

    ....

    public void onDestroy() {
        myBean.onDestroy();
        super.onDestroy();
    }
}
```
Looks good for me :+1:

**Comment by WonderCsabo** [comment]
And what happens if you have multiple beans of the same type is injected to the activity? You call both? Also the bean maybe injected to multiple components!

Also this is not easy about the implementation: the `AnnotationHandler` which handles the `@OnCreate` etc annotations will have an `EBeanHolder`, and does not know abut `EActivityHolder`(s) at all.

**Comment by Artyomcool** [comment]
> And what happens if you have multiple beans of the same type is injected to the activity? You call both? Also the bean maybe injected to multiple components!

Yep, call both, what is wrong here?

> Also this is not easy about the implementation: the AnnotationHandler which handles the @OnCreate etc annotations will have an EBeanHolder, and does not know abut EActivityHolder(s) at all.

Yeah, this is a problem, especially with incremental compilation. What if we will generate empty methods for every bean? And call appropriate annotated methods from there, if they exist?

**Comment by WonderCsabo** [comment]
That a solution, but somewhat ugly. Also it meas still `BeanHandler` has to generate all method calls from the component to the bean. As @yDelouis said it is unfortunate (i assume you read all the previous discussion, but i still feel we telling the same things again?).

**Comment by Artyomcool** [comment]
Well, current architecture doesn't support direct interaction between different annotations. In this case there are always only two options: change an architecture or hack it.
In case of generation every method with ```BeanHandler``` we are smudging responsibility, true. But what options do we really have?

**Comment by Artyomcool** [comment]
Oh, there is a better workaround, I think.
What if we will create an interface:
```
interface LifecycleAware {
  void onCreate(Bundle bundle);
  //and so on
}
```
Then with ```BeanHolder``` lazily implement it on the first usage. Then in components initialization check beans for implementing the interface and add it into the list. Then notify the every element with lifecycle methods.
Wdyt?

**Comment by WonderCsabo** [comment]
Yeah, we already considered an approach like this, see the previous comments.

I think the listener approach is better:

In the Activity:
if (any injected bean has at least one lifecycle annotation):
override all lifecycle method and notify the listeners in them

In the bean:
for every event annotaion:
subsribe to to that event in `init_` to the `Context`.

This way we do not have to hack the architecture, (almost) all annotations are just responsible for their true purpose. The only bad thing that `EActivityHandler` has to generate the methods.

I did not think about applying this approach to fragments.

**Comment by Artyomcool** [comment]
> if (any injected bean has at least one lifecycle annotation):

But you can't know, can you?

**Comment by Artyomcool** [comment]
> subsribe to to that event in init_ to the Context.

Will not do the job for singletons

**Comment by Artyomcool** [comment]
> I did not think about applying this approach to fragments

And this is the main problem (for me). In our project we do almost nothing in activities. So, the feature will be useless for us :(

**Comment by WonderCsabo** [comment]
> Will not do the job for singletons

Well, `rebind` can help us. But i am not sure we should support his at all with singletons.

> But you can't know, can you?

In full build, we definitely can. In incremental build, i think we can, too: if the Activity changes, the Bean classes will also will be available to us, since they are referenced.

> And this is the main problem (for me). In our project we do almost nothing in activities. So, the feature will be useless for us :(

We can just change the init_ method:

`Bean.init_(context, listener)` and pass the `Fragment` in the second param.

**Comment by Artyomcool** [comment]
Seems good, but lets consider one another way. What if will use some combination of suggestions discussed before.
```@NotifyLifecycle(Lifecycle.OnCreateOnDestroy)```
The annotation is good, actually. We should know that the bean hooks the lifecycle.
The bad thing here is the ```Lifecycle``` enum. And we already know, that we can escape it.
This approach will let us generate one common method ```bind``` (and maybe ```unbind```, if we will support singletons). Also it makes things more obvious.

**Comment by WonderCsabo** [comment]
I thought your problem was actually that the `@NotifyLifecycle` is a very-very bad thing, because that will make the activity know the bean internals.

**Comment by Artyomcool** [comment]
The details of internal implementation, not just the fact of hooking.

**Comment by Artyomcool** [comment]
I mean, lets assume that I hook just one method, let it be ```onCreate```. Tomorrow I'll decide to do it with ```onDestroy``` and will be enforce to change every component.

**Comment by WonderCsabo** [comment]
I see! I think this is not a good approach. @yDelouis WDYT?

This feature still needs tremendous much work though. :smile:

**Comment by Artyomcool** [comment]
I mean... The purpose of lifecycle aware beans is slightly different from simple beans, and when you read the code, you should see, that lifecycle is hooked. But you should change a half of the app, when you add some implementation details.

**Comment by yDelouis** [comment]
I was thinking of the same solution than @Artyomcool's one (if I understood it correctly) :
- In the `Bean`, annotate some methods with `@OnCreate`, `@OnDestroy`, ... to declare that these methods should be called if the component wants to notify its lifecycle. The corresponding handler can validate the method and its parameters.
- In the `Activity`, `Fragment`, etc.., we annotate the `@Bean` annotated field with `@NotifyLifecycle` (or we add a parameter to `@Bean`) to specify that we want the field to be notified of the lifecycle. The corresponding handler will search in the class for methods annotated with `@OnCreate`, etc.. and will add the needed calls. It could also add a warning or an error if the field doesn't have any method with these annotations.

About adding an annotation `@NotifyLifecycle` or adding a parameter in `@Bean`, I prefer adding an annotation for several reason : 
- In the architecture, one annotation == one purpose == one handler. It will be cleaner in code for validation and processing, IMHO.
- We could want to notify a `View`, `Application` that the activity has been resumed/paused. So we will be able to reuse this annotation.

About the implementation : (even it's a bit too early to discuss about it :-)
In the method `process` of `NotifyLifecycleHandler`, we should just search in the class for the annotated methods and the code for the injection should be in a static method of each `OnXXXXHandler` (`OnCreateHandler` for example). So that, validation of method is in the same class than the generation of the call of this method.

**Comment by Artyomcool** [comment]
Agree about main idea, but maybe it is better to use ```@OnCreate```, ```@OnDestroy```, etc. handlers to generate the code? It is better suits to the current architecture, isn't it?

**Comment by yDelouis** [comment]
Yes and no.
Yes, the code to generate the code should be in `@OnCreate`, `@OnDestroy` handlers.
No, it should be in a static method, not in the method `process` method, because the `OnCreateHandler` will expect a `EBeanHolder` and not a `HasLifecyle` (the interface implemented by both `EActivityHolder`, `EFragmentHolder`, etc...).

**Comment by Artyomcool** [comment]
Well, EBeanHolder will be enough, if we will lazily implement an interface like:
```
interface LifecycleAware {
  void onCreate(Bundle bundle);
  //and so on
}
```
```NotifyLifecycleHandler``` may assume that the interface is implemented by generated bean and just call corresponding methods.

**Comment by WonderCsabo** [comment]
@yDelouis i think you missed my listener-based suggestion which @Artyomcool is referring to (i think :smile: ).

So basically `@OnCreate`, `@OnDestroy` handlers will generate listener subscriber method calls to the passed listener in the `getInstance_`  method.
`@NotifyLifecycle` will generate listener event fire actions in the lifecycle methods of the component, but only in the needed ones.

Implementation note:
if we put `@OnCreate` and co handlers before `@NotifyLifecycle` handler in `AnnotationHandler`s, we do not have to scan the bean classes in `@NotifyLifecycle` handler (scanning should deal with inheritance, too!). We can create a static map in `BeanHandler`, and `@OnCreate` will add <BeanClass [event, event]> to that map. `@NotifyLifecycle` handler  can use the map and only generate event firings which are needed.

**Comment by Artyomcool** [comment]
Well, I wasn't referring exactly to this suggestion, but it is an option too :smile_cat: 
Looks like, we have a good way to choose an implementation: "It’s the early bird that gets the worm", or like we say in Russia: "who first stood up takes the sneakers" (more funny version, I think).
Lets the one who will prepare the PR decide the way to implement the feature. "There are may ways to the mountain top, but the sight is the same".

**Comment by WonderCsabo** [comment]
@Artyomcool: @yDelouis and me have already lots of work assigned. :wink:

**Comment by Artyomcool** [comment]
I know, I would never play a game, if it is not proven, that I'll win :smile_cat:

**Comment by Artyomcool** [comment]
BTW: shouldn't we provide ```@ViewById``` annotation for beans in the case this feature will be implemented?

**Comment by WonderCsabo** [comment]
I think not. Beans are sort of model or logic layer, Activity (Fragment) is the controller, and XML files are the view.  Also, the context of the bean can be a Service, too. 
I would not mix `@ViewById` to bean.

**Comment by yDelouis** [comment]
Neither do I.

**Comment by mdumrauf** [comment]
Reviving this. Otto has been [deprecated](https://github.com/square/otto/commit/008bd6e3bf979522fee36a5c73036dcf0a7fa486). So we may either use another EventBus framework ([greenrobot?](https://github.com/greenrobot/EventBus)) or use a different approach.

**Comment by dodgex** [comment]
With newly announced [Lifecycle features](https://developer.android.com/topic/libraries/architecture/lifecycle.html) as part of the [Arcitecture Components](https://developer.android.com/topic/libraries/architecture/index.html) this might be easy - if necessary in AndroidAnnotations at all.

**Comment by WonderCsabo** [comment]
I agree, that library gives much flexibility, and easy to use. We do not have to reinvent the wheel. :)
