### ISSUE TITLE
Using androidAnnotations in custom views

### ISSUE THREAD

**Issue by PerfectCarl** [androidannotations/androidannotations#859]
I'm running into a peculiar issue: I'm writing a custom view that is composed of other views and using R.strings.

Here is a sample of the code: 

``` java
@EViewGroup(R.layout.reborn_section_view)
public class SectionView extends RelativeLayout {

    @StringRes(android.R.string.copy)
    String dont_crash;

    @StringRes(R.string.expand_less)
    String crash;

    private final AttributeSet attrs;

    public SectionView(Context context, AttributeSet attrs) {
        super(context, attrs);
        this.attrs = attrs;
    }
    ...
}
```

The thing is when the Eclipse visual editor displays the layout that is using my custom view, the population of the field `crash`... well crashes.
It seems that the string cannot be found at design time if the string is defined by the app/library that holds that custom view. 
The field `dont_crash` is populated allright.

For reference, here's the complete stack trace: 

```
android.content.res.Resources$NotFoundException: Could not resolve resource value: 0x7F080072.
    at android.content.res.BridgeResources.throwException(BridgeResources.java:693)
    at android.content.res.BridgeResources.getString(BridgeResources.java:506)
    at de.robv.android.xposed.installer.reborn.ui.module.SectionView_.init_(SectionView_.java:70)
    at de.robv.android.xposed.installer.reborn.ui.module.SectionView_.<init>(SectionView_.java:39)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
```

To be honest, this is such an edge case that I don't know if something should be done. 
And if that's the case, what could be done. 
Maybe swallow the exception while retrieving string values if `view.isInEditMode()`? 

Meanwhile, the workaround is obvious: do the stuff the old way.

``` java
if (!isInEditMode()) {
    Resources resources = getContext().getResources();
    more = resources.getString(R.string.expand_less);
}
```

**Comment by hswope** [comment]
I am encountering a related issue. I have a custom ViewGroup using @EViewGroup, it has references to various beans injected with @Bean. Some of these beans call into things in @AfterInject that throw exceptions when in edit mode. I have no good way to know if I am in edit mode from the @Bean classes to avoid the bad behavior. I wish there was some type of hook or annotation in the creation process that allowed me to conditionally initialize things based on edit mode.

**Comment by hswope** [comment]
My work around was from within @EViewGroup

@AfterViews
protected void init() {

  if (!isInEditMode()) {
    myBean = MyBean_.getInstance_(getContext());
  }
}
