### ISSUE TITLE
@Get arbitrary parameters 

### ISSUE THREAD

**Issue by jkbbwr** [androidannotations/androidannotations#900]
It seems that I am unable to set arbitrary query parameters to a @Get declaration

My endpoint looks like 

`http://api.lmiforall.org.uk/api/v1/ashe/estimateHours?soc=2349&coarse=true`

There are a non trivial amount of parameters to this query, is there a declaration I can use to indicate this to the @Rest interface?

**Comment by vincentjames501** [comment]
This would be super useful. I'm surprised more people haven't requested this for more complex querying.  +1.

**Comment by WonderCsabo** [comment]
Unfortunately this is not a priority for us now, and our queue is very-very long. However, we always gladly accept pull requests.

**Comment by WonderCsabo** [comment]
BTW, we should also add `@Query` which could be added to the fields directly.

**Comment by WonderCsabo** [comment]
This could be easily done if we generate calls to the `UriComponentsBuilder` API.

**Comment by demonito** [comment]
When I needed to create @Get request with many dynamic parameteres, and some of them could be duplicated, I had resolved that problem so:

```java
@Rest(rootUrl = "http://example.com:9080/",
        converters = { GsonHttpMessageConverter.class },
        interceptors = { ApiInterceptor.class })
public interface ExampleApi {

   @Get("content/home/product-type/list?{filters}&domain={domain}") //filters is String like "param1=value1&param1=value2&param3=value3"
   ProductTypeListResponse getProductTypeList(int domain, String filters);

 }

public class ApiInterceptor implements ClientHttpRequestInterceptor {

    private static final String TAG = ApiInterceptor.class.getSimpleName();

    @Override
    public ClientHttpResponse intercept(final HttpRequest request, byte[] body, ClientHttpRequestExecution execution) throws IOException {
        final QueryMultiParamsHttpRequest modifiedRequest = new QueryMultiParamsHttpRequest(request);
        return execution.execute(modifiedRequest, body);
    }
}

public class QueryMultiParamsHttpRequest implements HttpRequest {

    private static final String TAG = QueryParametersBuilder.class.getSimpleName();
    private HttpRequest httpRequest;

    public QueryMultiParamsHttpRequest(final HttpRequest httpRequest) {
        this.httpRequest = httpRequest;
    }

    @Override
    public HttpMethod getMethod() {
        return httpRequest.getMethod();
    }

    @Override
    public URI getURI() {
        final URI originalURI = httpRequest.getURI();
        final String query = originalURI.getQuery() != null ? originalURI.getQuery().replace("%3D", "=").replace("%26", "&") : null;
        URI newURI = null;
        try {
            newURI = new URI(originalURI.getScheme(), originalURI.getUserInfo(), originalURI.getHost(), originalURI.getPort(), originalURI.getPath(),
                    query, originalURI.getFragment());
        } catch (URISyntaxException e) {
            Log.e(TAG, "Error while creating URI of QueryMultiParamsHttpRequest", e);
        }
        return newURI;
    }

    @Override
    public HttpHeaders getHeaders() {
        return httpRequest.getHeaders();
    }
}

```
So, I created a wrapper for HttpRequest, that can decode symbols "=" and "&". And this wrapper replace original HttpRequest in ApiInterceptor. This is some hacky solution, but it works.

**Comment by WonderCsabo** [comment]
@demonito thanks for sharing your solution, it will help others as well. I am sorry that you have to use a hack. I have this feature in my queue, but that is very long unfortunetly. I am planning to include this in AA 4.0. though. Stay tuned!

**Comment by kihaki** [comment]
Hey everyone, I was just wondering if there is any update on this?

**Comment by WonderCsabo** [comment]
Unfortunately we have limited to to work an AA, feel free to contribute!
