### ISSUE TITLE
Support RoboGuice for EGroupView

### ISSUE THREAD

**Issue by alberskib** [androidannotations/androidannotations#916]
Actually RoboGuice and AndroidAnnotations can cooperate each other by marking class with @RoboGuice annotation. It works only for classes annotated by @EActivity. It will be great if classes annotated by @EViewGroup could benefit from RoboGuice functionalities

**Comment by dodgex** [comment]
While we have Plugins now and RoboGuice support has been moved to a plugin I think this one can be closed for two reasons:

- no one else asked for it as far as i know
- RoboGuice has been retired/deprecated as of August 2016


@WonderCsabo wdyt?

**Comment by WonderCsabo** [comment]
I agree.
