### ISSUE TITLE
@ViewById inside @EBean using android annotations

### ISSUE THREAD

**Issue by nazr** [androidannotations/androidannotations#985]
Can't get @ViewById to work inside an @EBean.

@EActivity(R.layout.data_layout)
public class MyActivity extends Activity {
   @Bean
   MyEbean bean;

   @AfterViews
   public void setupView() {
     bean.loadData("Test name");
   }
}

@EBean
public class MyEbean {
   @RootContext
   context;

   @ViewById(R.id.name_field)
   TextView nameField;

  public void loadData(String name) {
    name.setText(name); 
  }
}

"name" in loadData() is null. At the same time if I do this inside loadData()

 name = (TextView)((Activity) context).findViewById(R.id.name_field);

it's all good. So the view is definitely there. Also if I call this method from a retrofit callback (i.e. after a delay) "name" is auto populated. 
I'm using Android Annotations 3.0.1.

**Comment by Smeet123** [comment]
I can use @AfterViews in Bean and in that, there is not an issue. e.g.

@AfterViews
public void init()
{
   textSum.setText("Sum:");
}

**Comment by gerardo-navarro** [comment]
This also means that @ViewById cannot be used inside an @EViewGroup? 

In my case it is instantiated with a layoutinflater `layoutInflater.inflate(mContentResource, null)`

**Comment by WonderCsabo** [comment]
You are using it wrong. If you inflate `layoutInflater.inflate(R.layout.card_layout, null)`, a layout will be inflated, which is in the XML file. If you want to use the generated view, you must use it directly:

```java
view = SwipingRecipeCardView_.build(context);
```

Or inflate a layout which contains the generated view.
